import { readFile } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { describe, erDiagramFrom } from '../brownfield/assemble.js';
import { inspect } from '../brownfield/detect.js';
import { exists, writeText } from '../fsutil.js';
import { PROJECT_FILE, saveProject } from '../project.js';
import { normalize } from '../schema.js';

const REPORT_FILE = 'assessment/adopt.md';
const bullets = (values, empty) => (values.length ? values.map((value) => `- ${value}`).join('\n') : `- ${empty}`);

/** The as-is project, marked so the rest of the workflow knows this code predates its specs. */
export function adoptedProject(name, described) {
  const project = normalize({
    project: { name, description: 'Adopted from an existing codebase. The stack below is as-is, not a target.' },
    stack: described.stack,
    commands: described.commands,
  });
  project.origin = 'adopted';
  return project;
}

export function adoptReport(name, described) {
  const share = described.share.map((entry) => `- ${entry.language} — ${entry.share}% (${entry.files} files)`).join('\n');
  const evidence = described.evidence.map((entry) => `| \`${entry.file}\` | ${entry.found} |`).join('\n');
  const commands = Object.entries(described.commands)
    .map(([key, value]) => `| ${key} | ${value ? `\`${value}\`` : '**not found**'} |`)
    .join('\n');

  return `# Adopt report — ${name}

Generated by \`vibekit adopt\`. This describes the repository **as it is today**, not a target.
Nothing here is guessed: anything that could not be found is marked as not found.

## Languages

${share || '- No files with a recognised extension were found.'}

## Frameworks and runtimes

${bullets([...described.runtimes, ...described.frameworks], 'None recognised. The manifests below are what was inspected.')}

## Commands

| Command | Detected |
|---|---|
${commands}

## Manifests inspected

| File | Found |
|---|---|
${evidence || '| _none_ | no manifests were found |'}

## Other signals

- CI workflows: ${described.ci.length ? described.ci.map((path) => `\`${path}\``).join(', ') : '**none found**'}
- Container files: ${described.containers.length ? described.containers.map((path) => `\`${path}\``).join(', ') : '**none found**'}
- Migration sources: ${described.migrations.length ? `${described.migrations.length} file(s)` : '**none found**'}

## Not determined

${bullets(described.unknown, 'Everything looked for was found.')}

These are left empty in \`specs/project.json\` rather than filled with a guess. Fill them in and
run \`vibekit sync\`. Until \`commands.test\` is set, \`vibekit check\` will report it, because
agents have no way to verify their work without it.
`;
}

export function asIsArchitecture(name, described, dirs) {
  const modules = dirs.length
    ? dirs.map((dir) => `| \`${dir}/\` | TODO: describe what this holds |`).join('\n')
    : '| _none_ | no top-level source folders were found |';
  const nodes = dirs.length ? dirs.map((dir, index) => `  m${index}["${dir}/"]`).join('\n') : '  repo["repository root"]';

  return `---
title: "Architecture (as-is)"
kind: "architecture"
sources: ["specs/project.json"]
---

# Architecture (as-is) — ${name}

> Generated by \`vibekit adopt\` from the repository structure. It records what is **there**,
> not what is intended. Correct it by hand, then run \`vibekit docs stamp docs/architecture.md\`.

## Detected stack

${bullets([...described.runtimes, ...described.frameworks], 'No frameworks recognised.')}

## Top-level structure

\`\`\`mermaid
flowchart TB
${nodes}
\`\`\`

| Folder | Responsibility |
|---|---|
${modules}

## Known gaps

${bullets(described.unknown, 'None recorded.')}
`;
}

export function asIsDataModel(name, diagram, migrations) {
  const body = diagram
    ? `\`\`\`mermaid\n${diagram}\n\`\`\`\n\nRelationships are **not** inferred: migrations give columns, not intent. Add them by hand.`
    : 'No table definitions could be parsed from the migration sources below. That does not mean\nthere is no schema, only that `vibekit adopt` could not read it. Describe it by hand.';

  return `---
title: "Data model (as-is)"
kind: "data-model"
sources: [${migrations.map((path) => `"${path}"`).join(',') || '"specs/project.json"'}]
---

# Data model (as-is) — ${name}

> Generated by \`vibekit adopt\` from migration sources, and stamped against them, so it goes
> stale when they change.

${body}

## Sources read

${bullets(migrations.map((path) => `\`${path}\``), 'No migration sources were found.')}
`;
}

export async function adopt({ root, force, json }) {
  const name = basename(root);
  const inspection = await inspect(root);
  const described = describe(inspection);

  if (json) {
    return console.log(JSON.stringify({
      name, origin: 'adopted', languages: described.share, runtimes: described.runtimes,
      frameworks: described.frameworks, testFrameworks: described.testFrameworks,
      commands: described.commands, ci: described.ci, containers: described.containers,
      migrations: described.migrations, evidence: described.evidence, unknown: described.unknown,
    }, null, 2));
  }

  if ((await exists(join(root, PROJECT_FILE))) && !force) {
    console.log(`${PROJECT_FILE} already exists — nothing was changed.\n`);
    console.log('Adopt would have recorded:');
    console.log(`  languages: ${described.languages.join(', ') || 'none detected'}`);
    console.log(`  stack:     ${[...described.runtimes, ...described.frameworks].join(', ') || 'none detected'}`);
    console.log(`  test:      ${described.commands.test || 'not found'}`);
    console.log('\nRe-run with --force to overwrite it.');
    return;
  }

  await saveProject(root, adoptedProject(name, described));
  await writeText(join(root, REPORT_FILE), adoptReport(name, described));
  await writeText(join(root, 'docs/architecture.md'), asIsArchitecture(name, described, inspection.dirs));

  const sources = [];
  for (const path of described.migrations.slice(0, 200)) {
    try {
      sources.push(await readFile(join(root, path), 'utf8'));
    } catch { /* unreadable: listed as a source, absent from the diagram */ }
  }
  await writeText(join(root, 'docs/data-model.md'), asIsDataModel(name, erDiagramFrom(sources), described.migrations));

  console.log(`✔ Adopted ${name}`);
  console.log(`  languages: ${described.languages.join(', ') || 'none detected'}`);
  console.log(`  stack:     ${[...described.runtimes, ...described.frameworks].join(', ') || 'none detected'}`);
  console.log(`✔ Wrote ${PROJECT_FILE}, ${REPORT_FILE}, docs/architecture.md, docs/data-model.md`);
  if (described.unknown.length) console.log(`! Not determined: ${described.unknown.join(', ')} — see ${REPORT_FILE}`);
  console.log('\nNext: correct the as-is docs, then run "vibekit sync". New work goes through features as usual.');
}
