import { join } from 'node:path';
import { readText, writeMissing, writeText } from '../fsutil.js';
import { GENERATED_MARK, buildManagedFiles, buildSeedFiles } from '../generators/index.js';
import { projectDocs } from '../docs/catalog.js';
import { docsEnabled, roadmapFile } from '../docs/index.js';
import { renderDocTemplate } from '../docs/templates.js';
import { assertValid, loadProject } from '../project.js';
import { rememberProject } from '../registry.js';

export async function managedFiles(root, project) {
  return [...buildManagedFiles(project), ...(docsEnabled(project) ? [await roadmapFile(root, project)] : [])];
}

const docSeeds = (project) => (docsEnabled(project) ? projectDocs(project).map((doc) => ({ path: doc.path, content: renderDocTemplate(project, doc) })) : []);

function stateOf(current, expected) {
  if (current === null) return 'missing';
  if (current === expected) return 'current';
  return current.includes(GENERATED_MARK) ? 'stale' : 'foreign';
}

async function inspect(root, project) {
  return Promise.all(
    (await managedFiles(root, project)).map(async (file) => ({ file, state: stateOf(await readText(join(root, file.path)), file.content) })),
  );
}

export async function findDrift(root, project) {
  const messages = {
    missing: 'is missing — run "vibecheck sync"',
    stale: 'is out of date — run "vibecheck sync"',
    foreign: 'exists but was not generated by Vibe-check-cli — run "vibecheck sync --force" to take it over',
  };
  const states = await inspect(root, project);
  return states.filter(({ state }) => messages[state]).map(({ file, state }) => `${file.path} ${messages[state]}`);
}

function printGroup(symbol, heading, paths) {
  if (!paths.length) return;
  console.log(`${symbol} ${heading}`);
  paths.forEach((path) => console.log(`    ${path}`));
}

export async function sync({ root, force = false }) {
  const project = await loadProject(root);
  assertValid(project);
  await rememberProject(root, project.project.name);
  const states = await inspect(root, project);
  const writable = new Set(['missing', 'stale', ...(force ? ['foreign'] : [])]);
  const toWrite = states.filter(({ state }) => writable.has(state)).map(({ file }) => file);
  const skipped = states.filter(({ state }) => state === 'foreign' && !force).map(({ file }) => file.path);

  await Promise.all(toWrite.map((file) => writeText(join(root, file.path), file.content)));
  const seeded = await writeMissing(root, [...buildSeedFiles(project), ...docSeeds(project)]);

  printGroup('✔', 'Generated', toWrite.map((file) => file.path));
  printGroup('+', 'Created (yours to edit)', seeded);
  printGroup('!', 'Skipped — not generated by Vibe-check-cli (use --force to overwrite)', skipped);
  if (!toWrite.length && !seeded.length && !skipped.length) console.log('✔ Everything is up to date.');
}
