import { join } from 'node:path';
import { rm } from 'node:fs/promises';
import { readText, writeMissing, writeText } from '../fsutil.js';
import { GENERATED_MARK, buildManagedFiles, buildSeedFiles, unusedEditorFiles } from '../generators/index.js';
import { projectDocs } from '../docs/catalog.js';
import { docsEnabled, roadmapFile } from '../docs/index.js';
import { renderDocTemplate } from '../docs/templates.js';
import { assertValid, loadProject } from '../project.js';
import { rememberProject } from '../registry.js';

export async function managedFiles(root, project) {
  return [...buildManagedFiles(project), ...(docsEnabled(project) ? [await roadmapFile(root, project)] : [])];
}

const docSeeds = (project) => (docsEnabled(project) ? projectDocs(project).map((doc) => ({ path: doc.path, content: renderDocTemplate(project, doc) })) : []);

function stateOf(current, expected) {
  if (current === null) return 'missing';
  if (current === expected) return 'current';
  return current.includes(GENERATED_MARK) ? 'stale' : 'foreign';
}

async function inspect(root, project) {
  return Promise.all(
    (await managedFiles(root, project)).map(async (file) => ({ file, state: stateOf(await readText(join(root, file.path)), file.content) })),
  );
}

export async function findDrift(root, project) {
  const messages = {
    missing: 'is missing — run "vibecheck sync"',
    stale: 'is out of date — run "vibecheck sync"',
    foreign: 'exists but was not generated by Vibe-check-cli — run "vibecheck sync --force" to take it over',
  };
  const states = await inspect(root, project);
  return states.filter(({ state }) => messages[state]).map(({ file, state }) => `${file.path} ${messages[state]}`);
}

/**
 * Take away the adapters for editors this project no longer lists.
 *
 * Only files this tool generated are removed, and only ones still byte-for-byte as generated: a
 * file someone has edited is theirs, and silently deleting it because a list changed would be the
 * worst thing this command could do. Those are reported instead, for a person to decide about.
 */
async function removeUnusedEditors(root, project) {
  const removed = [];
  const kept = [];
  for (const file of unusedEditorFiles(project)) {
    const current = await readText(join(root, file.path));
    if (current === null) continue;
    if (current === file.content || current.includes(GENERATED_MARK)) {
      await rm(join(root, file.path), { force: true });
      removed.push(file.path);
    } else {
      kept.push(file.path);
    }
  }
  return { removed, kept };
}

function printGroup(symbol, heading, paths) {
  if (!paths.length) return;
  console.log(`${symbol} ${heading}`);
  paths.forEach((path) => console.log(`    ${path}`));
}

export async function sync({ root, force = false }) {
  const project = await loadProject(root);
  assertValid(project);
  await rememberProject(root, project.project.name);
  const states = await inspect(root, project);
  const writable = new Set(['missing', 'stale', ...(force ? ['foreign'] : [])]);
  const toWrite = states.filter(({ state }) => writable.has(state)).map(({ file }) => file);
  const skipped = states.filter(({ state }) => state === 'foreign' && !force).map(({ file }) => file.path);

  await Promise.all(toWrite.map((file) => writeText(join(root, file.path), file.content)));
  const seeded = await writeMissing(root, [...buildSeedFiles(project), ...docSeeds(project)]);
  const { removed, kept } = await removeUnusedEditors(root, project);

  printGroup('✔', 'Generated', toWrite.map((file) => file.path));
  printGroup('+', 'Created (yours to edit)', seeded);
  printGroup('−', 'Removed — this project does not list that editor', removed);
  printGroup('!', 'Kept — you have edited these, and this project no longer lists that editor', kept);
  printGroup('!', 'Skipped — not generated by Vibe-check-cli (use --force to overwrite)', skipped);
  if (![toWrite.length, seeded.length, skipped.length, removed.length, kept.length].some(Boolean)) console.log('✔ Everything is up to date.');
}
