import { join } from 'node:path';
import { ROLES, humansPath, loadHumans } from '../humans.js';
import { readText, writeText } from '../fsutil.js';
import { folderName } from './folder.js';

/**
 * `vibekit team`. Specification §67, §47 and §51.
 *
 *   team                          who may approve what, from agents/humans.md
 *   team add "<Name> <email>" --role "tech lead"     name an approver (also what invites them to the tracker)
 *   team codeowners               write CODEOWNERS from humans.md and the layer rules in map.md
 *
 * The file records it; the tracker and the provider enforce it. Nothing here is stored anywhere
 * else, so a team that never runs this command can edit humans.md by hand and get the same result.
 */
export async function team(options) {
  const { root, args, folder: chosen, json } = options;
  const folder = chosen ?? (await folderName(root));
  const [verb, ...rest] = args;

  if (verb === 'add') return add(root, folder, rest, options);
  if (verb === 'codeowners') return codeowners(root, folder, options);
  if (verb && verb !== 'status') throw new Error('Usage: vibekit team [add "<Name> <email>" --role "<role>" | codeowners]');

  const humans = await loadHumans(root, folder);
  if (json) return void console.log(JSON.stringify(humans, null, 2));
  console.log(`Team · ${folder}/agents/humans.md`);
  console.log('');
  if (!humans.approvers.length) console.log('  No approvers named yet. Until someone is, every gate waits on a name nobody has.');
  for (const person of humans.approvers) console.log(`  ${person.role.padEnd(14)} ${person.name}${person.email ? ` <${person.email}>` : '   (no email: the tracker cannot map a login to them)'}`);
  if (!humans.approvers.some((person) => person.role === 'security')) console.log('  security       — none named; the tech lead holds the role and the security report says so');
  console.log('');
  console.log('  vibekit team add "Ada Lovelace <ada@example.com>" --role "tech lead"');
  console.log('  vibekit team codeowners      CODEOWNERS from humans.md and map.md, so the provider enforces the human-review rule');
}

/** Add or replace a row in the `## Approvers` table. */
async function add(root, folder, rest, options) {
  const who = rest.join(' ').trim();
  const role = String(options.role ?? '').trim().toLowerCase();
  const matched = who.match(/^(.+?)\s*<([^>]+)>\s*$/);
  if (!matched) throw new Error('Usage: vibekit team add "<Name> <email@example.com>" --role "<product owner | tech lead | security>"');
  if (!ROLES.includes(role)) throw new Error(`--role takes one of: ${ROLES.join(', ')}.`);
  const [, name, email] = matched;
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new Error(`"${email}" is not an email address.`);

  const path = humansPath(root, folder);
  const text = (await readText(path)) ?? '# Humans\n\n## Approvers\n\n| Role | Name | May approve |\n| --- | --- | --- |\n';
  const row = `| ${role} | ${name.trim()} <${email}> | ${MAY_APPROVE[role]} |`;
  const rowPattern = new RegExp(`^\\|\\s*${role}\\s*\\|[^\\n]*$`, 'm');
  const next = rowPattern.test(text) ? text.replace(rowPattern, row) : text.replace(/(\| --- \| --- \| --- \|\n)/, `$1${row}\n`);
  await writeText(path, next);
  if (options.json) return void console.log(JSON.stringify({ role, name: name.trim(), email }, null, 2));
  console.log(`✔ ${name.trim()} <${email}> is the ${role}. The tracker maps a Cloudflare Access login for that email to this row.`);
}

const MAY_APPROVE = {
  'product owner': 'plan, scope, requirement priority, prod promotion',
  'tech lead': 'architecture, standards changes, gate policy, stale holds',
  security: 'security.md, access.md, the dependency allow-list, L requirements touching secret or financial data',
};

/**
 * §51 — "Writes a CODEOWNERS file from `agents/humans.md` and the layer rules in `map.md`:
 * `standards/`, `invariants.md` and `guardrails.md` owned by the tech lead; `product/` by the
 * product owner; application layers by whoever `humans.md` names."
 */
export async function codeowners(root, folder, options = {}) {
  const humans = await loadHumans(root, folder);
  const handle = (role) => {
    const person = humans.approvers.find((entry) => entry.role === role) ?? (role === 'security' ? humans.approvers.find((entry) => entry.role === 'tech lead') : null);
    return person?.email ? person.email : null;
  };
  const techLead = handle('tech lead');
  const owner = handle('product owner');
  const securityOwner = handle('security');
  if (!techLead && !owner) throw new Error('humans.md names nobody with an email; CODEOWNERS needs a handle per row. `vibekit team add` first.');

  const map = (await readText(join(root, folder, 'product/map.md'))) ?? '';
  const layers = [...map.matchAll(/^(src\/[\w./-]+\/)\s{2,}/gm)].map((match) => match[1]);
  const lines = [
    '# generated by vibekit · do not edit · source: team',
    '# From agents/humans.md and the layer rules in product/map.md. The provider enforces the human-review rule natively.',
    '',
    ...(techLead ? [`${folder}/standards/ ${techLead}`, `${folder}/product/invariants.md ${techLead}`, `${folder}/standards/guardrails.md ${techLead}`, `${folder}/workflow/architecture.md ${techLead}`] : []),
    ...(owner ? [`${folder}/product/ ${owner}`] : []),
    ...(securityOwner ? [`${folder}/standards/security.md ${securityOwner}`, `${folder}/product/access.md ${securityOwner}`] : []),
    ...layers.map((layer) => `${layer} ${techLead ?? owner}`),
    '',
  ];
  const path = join(root, 'CODEOWNERS');
  await writeText(path, lines.join('\n'));
  if (options.json) return void console.log(JSON.stringify({ path, rows: lines.filter((line) => line && !line.startsWith('#')).length }, null, 2));
  console.log(`✔ CODEOWNERS written · ${lines.filter((line) => line && !line.startsWith('#')).length} rule(s)`);
  if (!securityOwner || securityOwner === techLead) console.log('  No security approver named: the tech lead holds security.md and access.md, and the report says so.');
}
