import { strict as assert } from 'node:assert';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import { DEFAULT_BRAND } from '../src/docs/arch/brand.js';
import { coloursFrom, disallows, extractBrand, logoFrom, typefacesFrom, wordmarkSvg } from '../src/docs/arch/extract.js';
import { convert, converterFor, inlineImages, markdownToHtml, toHtml } from '../src/docs/arch/formats.js';
import { generateDocs } from '../src/docs/arch/generate.js';
import { atCommit, commitDate, compareModels, diffDocs } from '../src/docs/arch/history.js';
import { renderApi, renderData, renderLld, renderRunbook } from '../src/docs/arch/library.js';
import { buildModel } from '../src/docs/arch/model.js';
import { generateFolder } from '../src/folder/generate.js';
import { run } from '../src/cli.js';
import { gitInit, sh } from './helpers.js';

/**
 * The half of the Documentation Feature Spec that leaves the repository: the document library
 * (§4), a brand read off a website (§5), history and diffs (§7), and the output formats (§4).
 *
 * These are the parts where being wrong is expensive and quiet — a logo taken from the wrong
 * site, a PDF missing its diagrams, a diff that omits a classification change a reviewer was
 * looking for. Each test below is one of those failures.
 */

const CONFIG = {
  name: 'bookings',
  description: 'A booking system for gyms.',
  architecture: 'clean',
  stack: { language: '.NET 10', web: 'Vue 3', database: 'PostgreSQL 17' },
  commands: { build: 'dotnet build', test: 'dotnet test' },
  entities: [
    { name: 'Booking', class: 'internal', fields: [{ name: 'id', type: 'uuid' }] },
    { name: 'Member', class: 'personal', fields: [{ name: 'email', type: 'string', class: 'personal' }] },
  ],
};

async function project(config = CONFIG) {
  const root = await mkdtemp(join(tmpdir(), 'vibekit-out-'));
  await generateFolder(root, config);
  await writeFile(join(root, 'vibekit/product/access.md'), '# Access\n\n| Role \\ Entity | Booking |\n| --- | --- |\n| member | CRU own |\n');
  return root;
}

// ------------------------------------------------------------ the document library (§4)

test('every document in the library renders, and each one says it is generated', async () => {
  const root = await project();
  const { documents } = await generateDocs(root, { commit: 'abc1234' });

  assert.deepEqual(documents, ['hld.md', 'lld.md', 'api-reference.md', 'data-model.md', 'runbook.md', 'srs.md', 'tech-spec.md']);
  for (const name of documents) {
    const body = await readFile(join(root, 'docs', name), 'utf8');
    assert.match(body, /^<!-- generated by vibekit/, `${name} must declare itself, or somebody edits it and loses the edit`);
  }
});

test('the API reference says there is nothing to list rather than inventing endpoints', async () => {
  const root = await project();
  const model = await buildModel(root);
  const body = await renderApi(root, model, DEFAULT_BRAND, { docs: 'docs', commit: 'abc' });

  assert.match(body, /No contract tests exist yet/, 'an empty table reads as "no endpoints", which is a different claim');
  assert.doesNotMatch(body, /GET \/api/);
});

test('an endpoint appears only with the contract test that proves it', async () => {
  const root = await project();
  const { mkdir } = await import('node:fs/promises');
  await mkdir(join(root, 'tests/contract'), { recursive: true });
  await writeFile(join(root, 'tests/contract/bookings.test.js'), "test('books', () => request('POST /api/bookings'));\n");

  const body = await renderApi(root, await buildModel(root), DEFAULT_BRAND, { docs: 'docs', commit: 'abc' });
  assert.match(body, /POST/);
  assert.match(body, /\/api\/bookings/);
  assert.match(body, /bookings\.test\.js/, 'the proof is the point: an endpoint with no test is not pinned');
});

test('the data model carries each entity classification, which is what a reviewer reads it for', async () => {
  const root = await project();
  const body = await renderData(root, await buildModel(root), DEFAULT_BRAND, { docs: 'docs', commit: 'abc' });

  assert.match(body, /Classification: \*\*Personal\*\*/);
  assert.match(body, /\| email \| string \| Personal \|/, 'a field classification that does not reach the document is a control nobody can audit');
});

test('the runbook and the low level design fill from the folder, not from prose nobody wrote', async () => {
  const root = await project();
  const model = await buildModel(root);
  const options = { docs: 'docs', commit: 'abc' };

  const lld = await renderLld(root, model, DEFAULT_BRAND, options);
  const runbook = await renderRunbook(root, model, DEFAULT_BRAND, options);

  assert.match(lld, /bookings/);
  assert.doesNotMatch(lld, /\{\{[a-z]/, 'an unresolved placeholder in a shipped document is worse than a missing section');
  assert.doesNotMatch(runbook, /\{\{[a-z]/);
  assert.match(runbook, /health/i, 'a runbook with no health check is not a runbook');
});

test('a template of your own wins for that document and leaves the others alone', async () => {
  const root = await project();
  const { mkdir } = await import('node:fs/promises');
  await mkdir(join(root, 'docs/templates'), { recursive: true });
  await writeFile(join(root, 'docs/templates/lld.md'), '# House LLD for {{project.name}}\n');

  await generateDocs(root, { commit: 'abc' });
  assert.match(await readFile(join(root, 'docs/lld.md'), 'utf8'), /House LLD for bookings/);
  assert.doesNotMatch(await readFile(join(root, 'docs/api-reference.md'), 'utf8'), /House/);
});

// ------------------------------------------------------------ output formats (§4)

test('the HTML carries its diagrams inside it, so it opens offline in five years', async () => {
  const root = await project();
  await generateDocs(root, { commit: 'abc' });
  const markdown = await readFile(join(root, 'docs/hld.md'), 'utf8');

  const images = await inlineImages(markdown, join(root, 'docs'));
  assert.ok(images.size > 0, 'the HLD references diagrams; none were found to inline');

  const html = await toHtml(markdown, { docsRoot: join(root, 'docs'), brand: DEFAULT_BRAND, title: 'HLD' });
  assert.match(html, /<svg/, 'the diagrams are inlined, not linked');
  assert.doesNotMatch(html, /<img\s/, 'a linked image is a broken image on somebody else’s machine');
  assert.doesNotMatch(html, /src="https?:/);
});

test('the Markdown a document actually contains survives the trip to HTML', () => {
  const html = markdownToHtml([
    '# Title',
    '',
    'A paragraph with **bold** and `code`.',
    '',
    '| Method | Path |',
    '| --- | --- |',
    '| GET | /api |',
    '',
    '- one',
    '- two',
    '',
    '```',
    'raw <not> markup',
    '```',
  ].join('\n'));

  assert.match(html, /<h1>Title<\/h1>/);
  assert.match(html, /<strong>bold<\/strong>/);
  assert.match(html, /<code>code<\/code>/);
  assert.match(html, /<th>Method<\/th>/);
  assert.match(html, /<td>\/api<\/td>/);
  assert.match(html, /<li>one<\/li>/);
  assert.match(html, /&lt;not&gt;/, 'content is escaped, never rendered as markup it did not ask for');
});

test('a missing converter is reported with what to install, and nothing half-written is left behind', async () => {
  const { existsSync } = await import('node:fs');
  const output = join(tmpdir(), `vibekit-nonexistent-${Date.now()}.docx`);
  const saved = process.env.PATH;
  process.env.PATH = '';
  try {
    assert.equal(converterFor('docx'), null);
    const outcome = convert('/nowhere/input.html', output, 'docx');
    assert.equal(outcome.ok, false);
    assert.match(outcome.reason, /pandoc/, 'telling somebody it failed without telling them what to install wastes their afternoon');
    assert.equal(existsSync(output), false, 'a docx without its diagrams would be worse than none');
  } finally {
    process.env.PATH = saved;
  }
});

// ------------------------------------------------------------ brand extraction (§5)

test('a colour the team named beats a colour that merely appears often', () => {
  const css = ':root { --brand: #1a4d7a; --accent: #E8A317; } .x { color: #cccccc } .y { color: #cccccc } .z { color: #cccccc }';
  const colours = coloursFrom(css);
  assert.equal(colours.brand, '#1A4D7A', 'naming --brand is the team telling you which colour is the brand');
  assert.equal(colours.accent, '#E8A317');
});

test('with nothing named, the most prominent colour is used and black and white are ignored', () => {
  const colours = coloursFrom('a{color:#fff}b{color:#123456}c{color:#123456}d{color:#abc}');
  assert.equal(colours.brand, '#123456');
  assert.ok(!colours.ranked.includes('#FFFFFF'));
});

test('typefaces are read in the order the page declares them', () => {
  const type = typefacesFrom('body { font-family: "Inter", sans-serif } code { font-family: Menlo, monospace }');
  assert.equal(type.heading, 'Inter, sans-serif');
  assert.match(type.mono, /Menlo/);
});

test('the logo is found in the order the spec prefers, and always as an absolute address', () => {
  const link = logoFrom('<link rel="icon" href="/favicon.svg">', 'https://example.test/about');
  assert.equal(link.url, 'https://example.test/favicon.svg');

  const og = logoFrom('<meta property="og:image" content="img/card.png">', 'https://example.test/a/b');
  assert.equal(og.url, 'https://example.test/a/img/card.png');

  const image = logoFrom('<img src="/i/wordmark.svg" alt="Acme logo">', 'https://example.test/');
  assert.match(image.from, /logo or wordmark/);
  assert.equal(logoFrom('<img src="/i/hero.jpg" alt="a gym">', 'https://example.test/'), null);
});

test('robots.txt is honoured, including a rule that only applies to another agent', () => {
  assert.equal(disallows('User-agent: *\nDisallow: /private', '/private/page'), true);
  assert.equal(disallows('User-agent: *\nDisallow: /private', '/about'), false);
  assert.equal(disallows('User-agent: googlebot\nDisallow: /', '/about'), false);
  assert.equal(disallows('User-agent: *\nDisallow:', '/anything'), false, 'an empty Disallow permits everything');
});

test('a page with no logo gets a wordmark and a line saying so, never a logo from somewhere else', async () => {
  const fetchPage = async () => ({
    html: '<title>Acme | Gyms</title><meta property="og:description" content="Book a class.">',
    css: ':root{--brand:#0B5}',
    base: 'https://acme.test/',
  });
  const result = await extractBrand('https://acme.test/', { fetchPage, now: () => new Date('2026-01-02') });

  assert.equal(result.logo, null);
  assert.ok(result.missing.some((note) => /no logo found/.test(note)));
  assert.equal(result.notice, null, 'there is no third-party mark to warn about');
  assert.equal(result.source, 'acme.test', 'provenance is recorded, so nobody wonders where the colour came from');
  assert.equal(result.brand.company.name, 'Acme');
  assert.equal(result.brand.company.tagline, 'Book a class.');
  assert.equal(result.fetchedAt, '2026-01-02');
  assert.match(wordmarkSvg(result.brand.company.name, result.brand), /Acme/);
});

test('when a logo is found, whose it is gets recorded rather than assumed', async () => {
  const fetchPage = async () => ({
    html: '<title>Acme</title><link rel="icon" href="/logo.svg">',
    css: '',
    base: 'https://acme.test/',
  });
  const result = await extractBrand('https://acme.test/', { fetchPage });
  assert.equal(result.logo.url, 'https://acme.test/logo.svg');
  assert.match(result.notice, /responsible for having permission/);
});

test('extraction reaches the network only for a URL', async () => {
  const path = join(await mkdtemp(join(tmpdir(), 'vibekit-brand-')), 'page.html');
  await writeFile(path, '<style>:root{--brand:#334455}</style><title>Local</title>');
  const result = await extractBrand(path, { fetchPage: () => { throw new Error('a local file must not be fetched'); } });
  assert.equal(result.brand.colour.brand, '#334455');
  assert.equal(result.source, path);
});

// ------------------------------------------------------------ history and diffs (§7)

const model = (over = {}) => ({
  containers: [], externals: [], entities: [], components: [], requirements: [], ...over,
});

test('the diff says what changed architecturally, in the words a reviewer would use', () => {
  const before = model({ containers: [{ name: 'API' }], entities: [{ name: 'Member', class: 'internal', fields: [{ name: 'id' }] }] });
  const after = model({
    containers: [{ name: 'API' }, { name: 'Worker' }],
    externals: [{ name: 'Stripe' }],
    entities: [{ name: 'Member', class: 'personal', fields: [{ name: 'id' }, { name: 'email' }] }, { name: 'Refund', class: 'financial', fields: [] }],
    requirements: [{ id: 'R-001', title: 'take payments', status: 'done' }],
  });

  const { markdown, unchanged } = compareModels(before, after, { from: 'v0.1.0', to: 'v0.2.0' });
  assert.equal(unchanged, false);
  assert.match(markdown, /\*\*Worker\*\* added/);
  assert.match(markdown, /now calls \*\*Stripe\*\*/);
  assert.match(markdown, /\*\*Refund\*\* added/);
  assert.match(markdown, /Member gained email/);
  assert.match(markdown, /\*\*Member is now classified personal, was internal\*\*/, 'the classification change is the line a security reviewer is looking for');
  assert.match(markdown, /R-001 take payments/);
});

test('two points with the same architecture say so, instead of printing empty headings', () => {
  const same = model({ containers: [{ name: 'API' }] });
  const { markdown, unchanged } = compareModels(same, same, { from: 'a', to: 'b' });
  assert.equal(unchanged, true);
  assert.match(markdown, /Nothing changed architecturally/);
});

test('the past is rebuilt without touching what somebody is working on', async () => {
  const root = await project();
  gitInit(root);
  sh(root, 'git', 'tag', 'v0.1.0');
  await writeFile(join(root, 'work-in-progress.txt'), 'half finished');

  const seen = await atCommit(root, 'v0.1.0', async (tree) => {
    const { readdir } = await import('node:fs/promises');
    return readdir(tree);
  });

  assert.ok(seen.includes('vibekit'), 'the worktree is the repository as it was');
  assert.ok(!seen.includes('work-in-progress.txt'), 'the tag predates it');
  assert.equal(await readFile(join(root, 'work-in-progress.txt'), 'utf8'), 'half finished', 'the working tree was left alone');
  assert.match(commitDate(root, 'v0.1.0'), /^\d{4}-\d{2}-\d{2}$/);
});

test('a ref that does not exist is refused by name, not with a git error', async () => {
  const root = await project();
  gitInit(root);
  await assert.rejects(() => atCommit(root, 'v9.9.9', async () => {}), /"v9.9.9" is not a commit or a tag/);
});

test('an external dependency added between two tags is reported as a call that is now made', async () => {
  const root = await project();
  gitInit(root);
  sh(root, 'git', 'tag', 'v0.1.0');

  // Externals are read from `## Dependencies` in the architecture record — the same place a
  // person writes them, so the diff follows the decision rather than a separate list.
  const architecture = join(root, 'vibekit/workflow/architecture.md');
  const before = await readFile(architecture, 'utf8');
  await writeFile(architecture, before.replace(/^## Dependencies$/m, '## Dependencies\n\n- Stripe · card payments'));
  sh(root, 'git', 'add', '-A');
  sh(root, 'git', 'commit', '-qm', 'feat: take payments');
  sh(root, 'git', 'tag', 'v0.2.0');

  const { markdown } = await diffDocs(root, 'v0.1.0', 'v0.2.0');
  assert.match(markdown, /Architecture changes · v0\.1\.0 → v0\.2\.0/);
  assert.match(markdown, /now calls \*\*Stripe\*\*/);
});

test('a document handed to somebody can be reproduced from its tag, byte for byte', async () => {
  // §8 acceptance 4, and the one the spec singles out as most likely to fail. Being able to
  // regenerate last quarter's document exactly is the difference between a document and a
  // claim about a document.
  //
  // The tag is taken before the document is written, because the stamp names the commit the
  // *code* came from: no file can contain the hash of the commit that carries it.
  const root = await project();
  gitInit(root);
  sh(root, 'git', 'tag', 'v1.0.0');
  await run(['arch-docs', 'hld', '--dir', root]);
  const asShipped = await readFile(join(root, 'docs/hld.md'), 'utf8');

  // The code moves on, which is the whole point: the tag must not follow it.
  await writeFile(join(root, 'vibekit/workflow/architecture.md'), '# Architecture\n\n## Dependencies\n\n- Stripe · card payments\n');
  sh(root, 'git', 'add', '-A');
  sh(root, 'git', 'commit', '-qm', 'feat: payments');
  await run(['arch-docs', 'hld', '--dir', root]);
  assert.match(await readFile(join(root, 'docs/hld.md'), 'utf8'), /Stripe/, 'today\u2019s document follows today\u2019s code');

  await run(['arch-docs', 'hld', '--dir', root, '--at', 'v1.0.0']);
  assert.equal(await readFile(join(root, 'docs/hld@v1.0.0.md'), 'utf8'), asShipped);
});

// ------------------------------------------------------------ the weak spots, now covered

test('when a converter is there, the document is converted and the tool that did it is named', async () => {
  const { delimiter } = await import('node:path');
  const { mkdtemp: makeTemp, readFile: read } = await import('node:fs/promises');
  const { installFakeBin } = await import('./helpers.js');
  const bin = await makeTemp(join(tmpdir(), 'fake-pandoc-'));
  // A stand-in for pandoc: takes `<input> -o <output>`, which is the contract convert() relies on.
  await installFakeBin(bin, 'pandoc', `#!/usr/bin/env node
const fs = require('fs');
const args = process.argv.slice(2);
fs.writeFileSync(args[args.indexOf('-o') + 1], 'DOCX ' + fs.readFileSync(args[0], 'utf8').length);
`);

  const root = await project();
  await generateDocs(root, { commit: 'abc' });
  const saved = process.env.PATH;
  process.env.PATH = [bin, saved].join(delimiter);
  try {
    assert.equal(converterFor('docx')?.command, 'pandoc');
    const outcome = convert(join(root, 'docs/hld.md'), join(root, 'docs/hld.docx'), 'docx');
    assert.equal(outcome.ok, true);
    assert.equal(outcome.by, 'pandoc', 'which tool produced a document is part of being able to reproduce it');
    assert.match(await read(join(root, 'docs/hld.docx'), 'utf8'), /^DOCX \d+$/);
  } finally {
    process.env.PATH = saved;
  }
});

test('a converter that fails reports its own first line, rather than a guess', async () => {
  const { delimiter } = await import('node:path');
  const { mkdtemp: makeTemp } = await import('node:fs/promises');
  const { installFakeBin } = await import('./helpers.js');
  const bin = await makeTemp(join(tmpdir(), 'broken-pandoc-'));
  await installFakeBin(bin, 'pandoc', '#!/usr/bin/env node\nconsole.error("pandoc: cannot produce docx from that");\nprocess.exit(3);\n');

  const saved = process.env.PATH;
  process.env.PATH = [bin, saved].join(delimiter);
  try {
    const outcome = convert('/in.html', '/out.docx', 'docx');
    assert.equal(outcome.ok, false);
    assert.match(outcome.reason, /pandoc: cannot produce docx/);
  } finally {
    process.env.PATH = saved;
  }
});

test('the real fetch reads one page and its stylesheet, and stops at robots.txt', async () => {
  const { createServer } = await import('node:http');
  const pages = {
    '/robots.txt': 'User-agent: *\nDisallow: /private\n',
    '/': '<title>Acme | Gyms</title><link rel="stylesheet" href="/site.css"><link rel="icon" href="/logo.svg">',
    '/site.css': ':root { --brand: #2266aa; } body { font-family: "Inter", sans-serif }',
  };
  const asked = [];
  const server = createServer((request, response) => {
    asked.push(request.url);
    const body = pages[request.url];
    response.writeHead(body === undefined ? 404 : 200, { 'content-type': 'text/plain' });
    response.end(body ?? 'no');
  });
  await new Promise((ready) => server.listen(0, '127.0.0.1', ready));
  const base = `http://127.0.0.1:${server.address().port}`;

  try {
    // No injected fetcher: this is the path that actually runs when somebody passes a URL. The
    // server is on loopback, which the guard refuses by default — so the refusal is asserted first
    // and the flag that says "internal is the point" is what lets the rest of the test run.
    await assert.rejects(() => extractBrand(`${base}/`), /loopback.*--allow-private/);
    const result = await extractBrand(`${base}/`, { allowPrivate: true });
    assert.equal(result.brand.colour.brand, '#2266AA');
    assert.match(result.brand.type.heading, /Inter/);
    assert.equal(result.logo.url, `${base}/logo.svg`);
    assert.ok(asked.includes('/robots.txt'), 'robots.txt is read before the page, not after');
    assert.ok(asked.includes('/site.css'), 'the stylesheet is where the colours are');

    await assert.rejects(() => extractBrand(`${base}/private/deck`, { allowPrivate: true }), /robots\.txt disallows \/private/);
  } finally {
    await new Promise((closed) => server.close(closed));
  }
});



test('an unfilled lead-in does not adopt the next paragraph as its own answer', async () => {
  // `\s*` crossed the newline, so an empty "**What this is.**" reported the "**Who uses it.**"
  // line as the description of the system — in the HLD, the SRS and the technical specification.
  const root = await project();
  const path = join(root, 'vibekit/product/context.md');
  await writeFile(path, '# Context\n\n**What this is.** \n\n**Who uses it.** members\n');

  const model = await buildModel(root);
  assert.equal(model.description, '');
});

