import assert from 'node:assert/strict';
import { mkdtemp, readdir, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, test } from 'node:test';
import { run } from '../src/cli.js';
import { EXAMPLE, exitCodeOf, fillSpec, newProject, read } from './helpers.js';

afterEach(() => {
  process.exitCode = 0;
});

test('init generates shared context; plugin mode leaves skills to the plugin', async () => {
  const root = await newProject('--yes');
  assert.match(await read(root, 'AGENTS.md'), /Spec-driven workflow/);
  assert.match(await read(root, 'CLAUDE.md'), /\/vibe-check-cli:run/);
  assert.match(await read(root, '.cursor/rules/vibecheck-workflow.mdc'), /alwaysApply: true/);
  assert.match(await read(root, '.claude/settings.json'), /vibe-check-cli@vibe-check-cli/);
  await assert.rejects(read(root, '.claude/skills/run/SKILL.md'));
  assert.equal(await exitCodeOf(['check', '--dir', root]), 0);
});

test('project mode writes unprefixed skills into .claude/skills', async () => {
  const root = await mkdtemp(join(tmpdir(), 'vibecheck-'));
  const specPath = join(root, 'spec.json');
  await writeFile(specPath, JSON.stringify({ project: { name: 'api' }, targets: ['api'], stack: { languages: ['Python'] }, workflow: { skills: 'project' } }));
  await run(['init', '--dir', root, '--from', specPath]);
  assert.match(await read(root, 'AGENTS.md'), /uv run pytest/);
  assert.match(await read(root, '.claude/skills/run/SKILL.md'), /\/implement-feature/);
  assert.doesNotMatch(await read(root, '.claude/skills/run/SKILL.md'), /vibe-check-cli:/);
});

test('status gates block unfinished specs and unfinished work', async () => {
  const root = await newProject('--from', EXAMPLE);
  await run(['feature', '--dir', root, 'Shared shopping list']);
  await assert.rejects(run(['status', '--dir', root, '001', 'approved']), /still contains TODOs/);
  await fillSpec(root, '001-shared-shopping-list', { tasks: ['- [ ] T-1 [impl] build it (AC-1)'] });
  await run(['status', '--dir', root, '001', 'approved']);
  await assert.rejects(run(['status', '--dir', root, 'shopping', 'done']), /acceptance criteria are checked/);
});

test('check detects drift after project.json changes and sync repairs it', async () => {
  const root = await newProject('--from', EXAMPLE);
  const projectPath = join(root, 'specs/project.json');
  const project = JSON.parse(await readFile(projectPath, 'utf8'));
  project.architecture.style = 'hexagonal';
  await writeFile(projectPath, JSON.stringify(project));
  assert.equal(await exitCodeOf(['check', '--dir', root]), 1);
  await run(['sync', '--dir', root]);
  assert.match(await read(root, 'AGENTS.md'), /Hexagonal/);
  assert.equal(await exitCodeOf(['check', '--dir', root]), 0);
});

test('sync never overwrites hand-written files without --force', async () => {
  const root = await mkdtemp(join(tmpdir(), 'vibecheck-'));
  await writeFile(join(root, 'AGENTS.md'), '# My own rules\n');
  await run(['init', '--dir', root, '--yes']);
  assert.equal(await read(root, 'AGENTS.md'), '# My own rules\n');
  await run(['sync', '--dir', root, '--force']);
  assert.match(await read(root, 'AGENTS.md'), /Generated by Vibe-check-cli/);
});

test('subagents ship in the plugin; projects only generate their own in standalone mode', async () => {
  const pluginAgents = await readdir(new URL('../agents/', import.meta.url));
  for (const builtIn of ['architect.md', 'implementer.md', 'reviewer.md', 'test-engineer.md']) assert.ok(pluginAgents.includes(builtIn), builtIn);
  const pluginMode = await newProject('--yes');
  await assert.rejects(read(pluginMode, '.claude/agents/architect.md'));
  assert.match(await read(pluginMode, 'CLAUDE.md'), /Subagents from the Vibe-check-cli plugin/);
  const standalone = await mkdtemp(join(tmpdir(), 'vibecheck-'));
  const specPath = join(standalone, 'spec.json');
  await writeFile(specPath, JSON.stringify({ project: { name: 'solo' }, workflow: { skills: 'project' } }));
  await run(['init', '--dir', standalone, '--from', specPath]);
  assert.match(await read(standalone, '.claude/agents/architect.md'), /You are the architect for solo/);
});
