import assert from 'node:assert/strict';
import { mkdtemp, readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, test } from 'node:test';
import { run } from '../src/cli.js';
import { toolChecks } from '../src/machine/health.js';
import { TOOLS } from '../src/machine/tools.js';
import { newProject, read, runHook } from './helpers.js';

const CHANGED = ['VIBEKIT_CURSOR_DIR', 'AGENTMEMORY_URL', 'VIBEKIT_REPO_DIR'];
const saved = Object.fromEntries(CHANGED.map((key) => [key, process.env[key]]));
let home;

beforeEach(async () => {
  home = await mkdtemp(join(tmpdir(), 'vc-home-'));
  process.env.VIBEKIT_CURSOR_DIR = join(home, '.cursor');
  process.env.VIBEKIT_REPO_DIR = join(home, 'empty-kit');
  process.env.AGENTMEMORY_URL = 'http://127.0.0.1:9';
});

afterEach(() => {
  for (const key of CHANGED) {
    if (saved[key] === undefined) delete process.env[key];
    else process.env[key] = saved[key];
  }
  process.exitCode = 0;
});

const frontMatterOf = (text) => Object.fromEntries(text.split('---')[1].trim().split('\n').map((line) => line.split(/:\s(.*)/s).slice(0, 2)));

test('every project gets the four subagents in Cursor\'s format', async () => {
  const root = await newProject('--yes');
  assert.deepEqual((await readdir(join(root, '.cursor/agents'))).sort(), ['architect.md', 'implementer.md', 'reviewer.md', 'test-engineer.md']);
  const reviewer = frontMatterOf(await read(root, '.cursor/agents/reviewer.md'));
  const implementer = frontMatterOf(await read(root, '.cursor/agents/implementer.md'));
  assert.deepEqual([reviewer.name, reviewer.readonly, reviewer.model, reviewer.is_background], ['reviewer', 'true', 'inherit', 'false']);
  assert.equal(implementer.readonly, 'false');
  assert.match(await read(root, '.cursor/agents/architect.md'), /read `AGENTS\.md`/);
  assert.match(await read(root, 'AGENTS.md'), /Cursor from `\.cursor\/agents\/`/);
  const edit = await runHook(root, 'pre-edit', { tool_name: 'Edit', tool_input: { file_path: join(root, '.cursor/agents/reviewer.md') } });
  assert.match(edit.stderr, /generated by VibeKit/, 'generated agent files are protected like other managed files');
});

test('user-level Cursor subagents install, stay current, respect your own files, and can be removed', async () => {
  const dir = join(home, '.cursor', 'agents');
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, 'reviewer.md'), '---\nname: reviewer\ndescription: my own reviewer\n---\nMine.\n');
  await writeFile(join(dir, 'debugger.md'), '---\nname: debugger\ndescription: unrelated\n---\n');

  const cursorTool = TOOLS.find((tool) => tool.id === 'cursor-agents');
  assert.equal((await cursorTool.check()).ok, false);
  await run(['cursor-agents']);
  assert.match(await readFile(join(dir, 'architect.md'), 'utf8'), /Reinstall with `vibekit cursor-agents`/);
  assert.equal(await readFile(join(dir, 'reviewer.md'), 'utf8'), '---\nname: reviewer\ndescription: my own reviewer\n---\nMine.\n', 'your own reviewer is kept');

  await run(['cursor-agents', '--remove']);
  assert.deepEqual((await readdir(dir)).sort(), ['debugger.md', 'reviewer.md'], 'only VibeKit files are removed');
});

test('health reports Cursor subagents, and setup installs them', async () => {
  const [before] = await toolChecks(null, 'linux', TOOLS.filter((tool) => tool.id === 'cursor-agents'));
  assert.equal(before.ok, false);
  await run(['setup', '--yes', '--only', 'cursor-agents']);
  const [after] = await toolChecks(null, 'linux', TOOLS.filter((tool) => tool.id === 'cursor-agents'));
  assert.equal(after.ok, true);
  assert.equal((await readdir(join(home, '.cursor', 'agents'))).length, 4);
});
