import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { afterEach, test } from 'node:test';
import { fileURLToPath } from 'node:url';
import { run } from '../src/cli.js';
import { worktreeBase } from '../src/git.js';
import { nextAction } from '../src/next.js';
import { loadProject } from '../src/project.js';
import { pluginSkillFiles } from '../src/team.js';
import { EXAMPLE, commitAll, exitCodeOf, fillSpec, gitInit, newProject, read, runHook, setDocsEnabled, sh, writeFileIn } from './helpers.js';

const FEATURE = '001-shared-list';
const TASKS = [
  '- [ ] T-1 [impl] shared contract types (AC-1) — packages/core/list.ts',
  '- [ ] T-2 [impl] API endpoint (AC-1) — apps/api/list.ts [P]',
  '- [ ] T-3 [impl] web screen (AC-1) — apps/web/list.tsx [P]',
  '- [ ] T-4 [test] e2e (AC-1) — e2e/list.spec.ts',
];

afterEach(() => {
  process.exitCode = 0;
});

async function plannedProject() {
  const root = await newProject('--from', EXAMPLE);
  await setDocsEnabled(root, false);
  await run(['feature', '--dir', root, 'Shared list']);
  await fillSpec(root, FEATURE, { tasks: TASKS });
  return root;
}

const next = async (root) => nextAction(root, await loadProject(root));

test('next walks the lifecycle and stops at human gates', async () => {
  const root = await plannedProject();
  assert.deepEqual(await next(root), { step: 'spec', gate: 'spec-approval', reason: 'spec needs completing and your approval', feature: FEATURE, command: `/vibe-check-cli:spec-feature ${FEATURE}` });
  await run(['status', '--dir', root, FEATURE, 'approved']);
  assert.equal((await next(root)).step, 'plan');
  await run(['status', '--dir', root, FEATURE, 'planned']);
  assert.equal((await next(root)).gate, 'plan-approval');
  await run(['status', '--dir', root, FEATURE, 'in-progress']);
  assert.deepEqual([(await next(root)).step, (await next(root)).gate], ['implement', null]);
});

test('pre-edit hook blocks code without an in-progress feature and protects generated files', async () => {
  const root = await plannedProject();
  const edit = (path) => runHook(root, 'pre-edit', { tool_name: 'Write', tool_input: { file_path: join(root, path) } });

  const blocked = await edit('apps/api/list.ts');
  assert.equal(blocked.code, 2);
  assert.match(blocked.stderr, /no feature is in progress/);
  assert.equal((await edit('specs/features/001-shared-list/plan.md')).code, 0);
  assert.match((await edit('AGENTS.md')).stderr, /generated by Vibe-check-cli/);

  await run(['status', '--dir', root, FEATURE, 'approved']);
  await run(['status', '--dir', root, FEATURE, 'in-progress', '--force']);
  assert.equal((await edit('apps/api/list.ts')).code, 0);
});

test('session-start injects protocol and state; stop hook enforces check once', async () => {
  const root = await plannedProject();
  const start = JSON.parse((await runHook(root, 'session-start', { source: 'startup' })).stdout);
  assert.match(start.hookSpecificOutput.additionalContext, /orchestrator protocol[\s\S]*001-shared-list · draft[\s\S]*Next: \/vibe-check-cli:spec-feature/);

  await writeFile(join(root, 'AGENTS.md'), '<!-- Generated by Vibe-check-cli --> tampered\n');
  assert.equal((await runHook(root, 'stop', {})).code, 2);
  assert.equal((await runHook(root, 'stop', { stop_hook_active: true })).code, 0);
});

test('hooks are silent outside vibecheck projects', async () => {
  const result = await runHook('/tmp', 'pre-edit', { tool_input: { file_path: '/tmp/x.ts' } });
  assert.deepEqual([result.code, result.stderr], [0, '']);
});

test('dispatch creates a worktree per lane and merge integrates their commits', async () => {
  const root = await plannedProject();
  await run(['status', '--dir', root, FEATURE, 'approved']);
  await run(['status', '--dir', root, FEATURE, 'in-progress', '--force']);
  const tasksPath = join(root, 'specs/features', FEATURE, 'tasks.md');
  await writeFile(tasksPath, (await read(root, `specs/features/${FEATURE}/tasks.md`)).replace('- [ ] T-1', '- [x] T-1'));
  gitInit(root);

  await run(['dispatch', '--dir', root, FEATURE, '--engine', 'manual']);
  const base = worktreeBase(root);
  const lanes = [1, 2].map((n) => join(base, `${FEATURE}-lane-${n}`));
  assert.ok(lanes.every((lane) => existsSync(lane)));
  assert.match(await read(base, `${FEATURE}-lane-1.prompt.md`), /T-2 \[impl\] API endpoint[\s\S]*Do not edit anything under specs/);
  await assert.rejects(run(['dispatch', '--dir', root, FEATURE, '--engine', 'manual']), /already dispatched/);

  lanes.forEach((lane, index) => {
    writeFileIn(lane, `apps/lane${index}.ts`, `lane${index}
`);
    commitAll(lane, `feat: T-${index + 2} lane work`);
  });
  assert.equal(await exitCodeOf(['merge', '--dir', root, FEATURE]), 0);
  assert.ok(existsSync(join(root, 'apps/lane0.ts')) && existsSync(join(root, 'apps/lane1.ts')));
  assert.ok(lanes.every((lane) => !existsSync(lane)));
});

test('committed plugin skills match the generator (run npm run build)', async () => {
  const pluginRoot = fileURLToPath(new URL('..', import.meta.url));
  for (const file of pluginSkillFiles()) {
    assert.equal(await read(join(pluginRoot, 'skills'), file.path), file.content, `${file.path} is stale`);
  }
});
