import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { chmod, mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { commitMsg, highEntropyTokens, hookScript, installHooks, preCommit, prePush, shannon } from '../src/githooks.js';
import { convertSpecKit, readSpecKit } from '../src/speckit.js';
import { ownerOnly } from '../src/fsutil.js';
import { parseRates, priceInCurrency } from '../src/models/registry.js';
import { sandboxCommand } from '../src/serve/sandbox.js';
import { changedBetween, commitToTracker, snapshot, trackerBranch } from '../src/trackerbranch.js';
import { serviceWorker, webManifest } from '../src/dashboard-view.js';
import { normaliseEvidence, seeded, stepFromCheckpoint } from '../src/recovery.js';
import { Changed, apply } from '../src/control.js';
import { generateFolder } from '../src/folder/generate.js';
import { tempDir } from './helpers.js';

const git = (root, ...args) => execFileSync('git', args, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();

async function repo() {
  const root = tempDir('vibekit-hooks-');
  git(root, 'init', '-q', '-b', 'main');
  git(root, 'config', 'user.email', 't@example.com');
  git(root, 'config', 'user.name', 'T');
  await writeFile(join(root, 'README.md'), '# x\n');
  git(root, 'add', '-A');
  git(root, 'commit', '-q', '-m', 'init');
  return root;
}

// ------------------------------------------------------------------ §50 hooks

test('init-style install writes four scripts, points core.hooksPath at them, and keeps a hand-written one', async () => {
  const root = await repo();
  await mkdir(join(root, '.githooks'), { recursive: true });
  await writeFile(join(root, '.githooks/pre-push'), '#!/bin/sh\necho mine\n');
  const result = await installHooks(root);
  assert.deepEqual(result.installed.sort(), ['commit-msg', 'post-merge', 'pre-commit']);
  assert.deepEqual(result.kept, ['pre-push']);
  assert.equal(git(root, 'config', 'core.hooksPath'), '.githooks');
  const script = await readFile(join(root, '.githooks/commit-msg'), 'utf8');
  assert.match(script, /generated by vibekit/);
  assert.match(script, /vibekit githook commit-msg/);
  // a clone without the binary warns and passes rather than refusing every commit
  assert.match(script, /not installed on this machine/);
  assert.match(script, /^exit 0$/m);
  assert.equal(hookScript('pre-commit').split('\n')[0], '#!/bin/sh');
});

test('commit-msg: refused on main; on req/* it needs the id and the trailer', async () => {
  const root = await repo();
  const onMain = await commitMsg(root, 'tidy up', { branch: 'main' });
  assert.equal(onMain.length, 1);
  assert.match(onMain[0], /straight onto main is refused/);
  assert.match(onMain[0], /--no-verify/);

  const bare = await commitMsg(root, 'tidy up', { branch: 'req/REQ-014' });
  assert.equal(bare.length, 2);
  assert.match(bare[0], /REQ-014/);
  assert.match(bare[1], /VibeKit-Requirement/);

  const good = await commitMsg(root, 'feat(REQ-014): cancel\n\nVibeKit-Requirement: REQ-014\n', { branch: 'req/REQ-014' });
  assert.deepEqual(good, []);
  const elsewhere = await commitMsg(root, 'anything', { branch: 'docs/tidy' });
  assert.deepEqual(elsewhere, []);
});

test('pre-commit: a staged live key, a private key and an email are refused; a sha and a lock file are not', async () => {
  const root = await repo();
  await writeFile(join(root, 'settings.json'), '{ "stripe": "sk_live_4eC39HqLyjWDarjtT1zdp7dc" }\n');
  await writeFile(join(root, 'notes.md'), 'ask ops@example.com\ncommit 3f786850e387550fdab836ed7e6dc881de23001b\n');
  await writeFile(join(root, 'package-lock.json'), '{ "integrity": "sha512-Ab3dEf9GhIjKlMnOpQrStUvWxYz0123456789AbCdEfGhIjKlMnOpQrStUvWxYz==" }\n');
  await writeFile(join(root, 'id_rsa'), '-----BEGIN RSA PRIVATE KEY-----\nabc\n-----END RSA PRIVATE KEY-----\n');
  git(root, 'add', '-A');
  const refusals = await preCommit(root);
  assert.ok(refusals.some((line) => /settings\.json.*live credential/.test(line)), refusals.join('\n'));
  assert.ok(refusals.some((line) => /id_rsa.*private key/.test(line)), refusals.join('\n'));
  assert.ok(refusals.some((line) => /notes\.md: an email/.test(line)), refusals.join('\n'));
  assert.ok(!refusals.some((line) => /package-lock/.test(line)), 'lock files are skipped');
  assert.ok(!refusals.some((line) => /3f786850/.test(line)), 'a git sha is not a secret');
});

test('pre-push: a force push to main is refused, a fast-forward is not, and req/* needs a holder', async () => {
  const root = await repo();
  const first = git(root, 'rev-parse', 'HEAD');
  await writeFile(join(root, 'README.md'), '# y\n');
  git(root, 'commit', '-qam', 'second');
  const second = git(root, 'rev-parse', 'HEAD');
  const zeros = '0'.repeat(40);

  const forward = await prePush(root, `refs/heads/main ${second} refs/heads/main ${first}`);
  assert.deepEqual(forward, []);
  const force = await prePush(root, `refs/heads/main ${first} refs/heads/main ${second}`);
  assert.equal(force.length, 1);
  assert.match(force[0], /force push to main is refused/);
  const create = await prePush(root, `refs/heads/main ${second} refs/heads/main ${zeros}`);
  assert.deepEqual(create, []);
  const unheld = await prePush(root, `refs/heads/req/REQ-001 ${second} refs/heads/req/REQ-001 ${zeros}`);
  assert.equal(unheld.length, 1);
  assert.match(unheld[0], /not held by this session/);
});

// ------------------------------------------------------------------ entropy

test('entropy: a base64 secret scores, hex and prose do not', () => {
  assert.ok(shannon('aaaa') < 1);
  const hits = highEntropyTokens('token=Zm9vYmFyYmF6cXV4MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1O key');
  assert.equal(hits.length, 1);
  assert.deepEqual(highEntropyTokens('commit 3f786850e387550fdab836ed7e6dc881de23001b'), []);
  assert.deepEqual(highEntropyTokens('internationalisationinternationalisation'), []);
});

// ------------------------------------------------------------------ owner-only files

test('ownerOnly makes a file 0600 on POSIX and reports how', async (t) => {
  if (process.platform === 'win32') return t.skip('icacls path exercised on Windows CI');
  const root = tempDir('vibekit-mode-');
  const path = join(root, 'token');
  await writeFile(path, 'x');
  await chmod(path, 0o644);
  const result = await ownerOnly(path);
  assert.deepEqual(result, { ok: true, by: 'chmod' });
  assert.equal((await stat(path)).mode & 0o777, 0o600);
});

// ------------------------------------------------------------------ rates.yml

test('rates.yml: a team currency prices a session in it, from its own table or from per-usd', async () => {
  const rates = parseRates([
    '# what we pay',
    'currency: zar',
    'per-usd: 18.0',
    'models:',
    '  house-model:',
    '    input: 36',
    '    output: 180',
    '',
  ].join('\n'));
  assert.equal(rates.currency, 'ZAR');
  assert.equal(rates.perUsd, 18);
  assert.deepEqual(rates.models['house-model'], { input: 36, output: 180 });

  const own = await priceInCurrency('anthropic', 'house-model', { input: 1_000_000, output: 0 }, rates);
  assert.equal(own.currency, 'ZAR');
  assert.equal(own.amount, 36);
  assert.equal(own.from, 'rates.yml');

  const none = await priceInCurrency('anthropic', 'unpriced', { input: 1000 }, { currency: null, perUsd: null, models: {} });
  assert.equal(none, null);
});

// ------------------------------------------------------------------ sandbox egress proxy

test('sandbox: an egress proxy is handed to the container only when the network is on', () => {
  const off = sandboxCommand('/repo', 'npm test', { proxy: 'http://egress:3128' });
  assert.equal(off.network, 'none');
  assert.equal(off.proxy, null);
  assert.ok(!off.argv.some((arg) => /HTTPS_PROXY/.test(arg)));

  const on = sandboxCommand('/repo', 'npm test', { registries: ['registry.npmjs.org'], proxy: 'http://egress:3128' });
  assert.equal(on.network, 'bridge');
  assert.equal(on.proxy, 'http://egress:3128');
  assert.ok(on.argv.includes('HTTPS_PROXY=http://egress:3128'));
  assert.ok(on.argv.includes('NO_PROXY=localhost,127.0.0.1'));
  assert.match(on.caveat, /proxy's allow-list is the rule/);

  const bare = sandboxCommand('/repo', 'npm test', { registries: ['registry.npmjs.org'], proxy: null });
  assert.match(bare.caveat, /VIBEKIT_EGRESS_PROXY/);
});

// ------------------------------------------------------------------ Spec Kit conversion

test('init --from-speckit writes the folder: principles become rules, EARS criteria are carried, the rest are asks', async () => {
  const root = tempDir('vibekit-speckit-');
  await mkdir(join(root, 'memory'), { recursive: true });
  await mkdir(join(root, 'specs/001-cancel'), { recursive: true });
  await writeFile(join(root, 'memory/constitution.md'), '# Constitution\n\n## Principles\n\n- Tests before code\n- No secrets in the repo\n');
  await writeFile(join(root, 'specs/001-cancel/spec.md'), [
    '# Feature: Cancel a booking',
    'Members cancel confirmed bookings and get refunds.',
    '',
    '## Acceptance Criteria',
    '- When a member cancels a confirmed booking, the system shall issue a refund.',
    '- It should feel fast.',
    '',
  ].join('\n'));
  const read = await readSpecKit(root);
  const result = await convertSpecKit(root, read, { folder: 'vibekit' });

  assert.equal(result.rules, 2);
  assert.equal(result.requirements.length, 1);
  assert.equal(result.requirements[0].carried, 1);
  assert.equal(result.requirements[0].skipped, 1);
  const rules = await readFile(join(root, 'vibekit/standards/rules.md'), 'utf8');
  assert.match(rules, /From the Spec Kit constitution/);
  assert.match(rules, /- Tests before code/);
  const requirement = await readFile(join(root, `vibekit/product/requirements/${result.requirements[0].id}.md`), 'utf8');
  assert.match(requirement, /^confidence: low$/m);
  assert.match(requirement, /AC-1  When a member cancels a confirmed booking/);
  assert.ok(!/feel fast/.test(requirement), 'a criterion that is not EARS is not carried as one');
  assert.match(requirement, /converted from specs\/001-cancel\/spec\.md/);
});

// ------------------------------------------------------------------ tracker/<user> merge-back

test('a tracker decision is committed on tracker/<user> with trailers and merged back when clean', async () => {
  const root = await repo();
  await mkdir(join(root, 'vibekit/workflow/asks'), { recursive: true });
  await writeFile(join(root, 'vibekit/workflow/asks/A-001.md'), 'status: open\n');
  git(root, 'add', '-A');
  git(root, 'commit', '-qm', 'folder');

  const before = await snapshot(root, 'vibekit');
  await new Promise((wait) => setTimeout(wait, 20));
  await writeFile(join(root, 'vibekit/workflow/asks/A-001.md'), 'status: answered\n');
  const paths = changedBetween(before, await snapshot(root, 'vibekit'));
  assert.deepEqual(paths, ['vibekit/workflow/asks/A-001.md']);

  const landed = await commitToTracker(root, {
    user: 'j.naidoo@example.com', name: 'J. Naidoo', paths,
    message: 'ask.answer A-001: answered', trailers: ['VibeKit-Role: human', 'VibeKit-Via: tracker'],
  });
  assert.equal(landed.committed, true);
  assert.equal(landed.branch, 'tracker/j.naidoo');
  assert.equal(landed.merged, true);
  assert.equal(landed.into, 'main');
  assert.equal(landed.pushed, false);

  const shown = git(root, 'show', '-s', '--format=%an <%ae>%n%B', landed.commit);
  assert.match(shown, /^J\. Naidoo <j\.naidoo@example\.com>/);
  assert.match(shown, /VibeKit-Via: tracker/);
  // a fast-forward: main is now the tracker commit, and the working tree is clean for that path
  assert.equal(git(root, 'rev-parse', 'main'), landed.commit);
  assert.equal(git(root, 'status', '--porcelain', '--', 'vibekit/'), '');
  assert.equal(trackerBranch('Some One@corp.example'), 'tracker/some-one');
});

test('a tracker commit that would not merge cleanly stays on its branch, and the page is told', async () => {
  const root = await repo();
  await mkdir(join(root, 'vibekit/workflow'), { recursive: true });
  await writeFile(join(root, 'vibekit/workflow/plan.md'), 'line one\n');
  git(root, 'add', '-A');
  git(root, 'commit', '-qm', 'folder');

  // the tracker branch records one change to the plan…
  await writeFile(join(root, 'vibekit/workflow/plan.md'), 'line one — from the phone\n');
  const first = await commitToTracker(root, { user: 'a@example.com', paths: ['vibekit/workflow/plan.md'], message: 'first' });
  assert.equal(first.merged, true);

  // …then main moves on the same line by hand, and a second tracker change lands on the old base.
  await writeFile(join(root, 'vibekit/workflow/plan.md'), 'line one — from the terminal\n');
  git(root, 'commit', '-qam', 'terminal edit');
  git(root, 'update-ref', 'refs/heads/tracker/a', first.commit); // the branch never saw the terminal edit
  await writeFile(join(root, 'vibekit/workflow/plan.md'), 'line one — from the phone again\n');
  const second = await commitToTracker(root, { user: 'a@example.com', paths: ['vibekit/workflow/plan.md'], message: 'second' });
  assert.equal(second.committed, true);
  assert.equal(second.merged, false);
  assert.equal(second.left, 'tracker/a');
  assert.match(second.why, /pull request/);
  assert.notEqual(git(root, 'rev-parse', 'main'), second.commit);
  assert.equal(git(root, 'rev-parse', 'tracker/a'), second.commit);
});

test('outside a repository nothing is committed and nothing throws', async () => {
  const root = tempDir('vibekit-norepo-');
  await writeFile(join(root, 'x.md'), 'x');
  const landed = await commitToTracker(root, { user: 'a@example.com', paths: ['x.md'], message: 'm' });
  assert.deepEqual(landed, { committed: false, why: 'not a git repository' });
});

// ------------------------------------------------------------------ offline queue

test('a queued action whose target moved is refused with a 409 the page may re-confirm', async () => {
  const root = tempDir('vibekit-queue-');
  await generateFolder(root, { name: 'q', description: null, architecture: 'layered', stack: {}, commands: {}, entities: [] }, { folder: 'vibekit' });
  const { createRequirement } = await import('../src/folder/requirements.js');
  await createRequirement(root, { id: 'REQ-001', title: 'x', kind: 'requirement', size: 'S', source: null }, 'vibekit');

  await assert.rejects(
    apply(root, null, { action: 'req.status', id: 'REQ-001', status: 'ready', expect: { status: 'in-progress' } }),
    (error) => error instanceof Changed && /now "draft", not "in-progress"/.test(error.message),
  );
  // the same request without an expectation is a live one and meets the ordinary gates instead
  await assert.rejects(
    apply(root, null, { action: 'req.status', id: 'REQ-001', status: 'ready' }),
    (error) => !(error instanceof Changed),
  );
});

test('the tracker ships a service worker scoped to its secret path and an installable manifest', () => {
  const worker = serviceWorker('/abc123');
  assert.match(worker, /var SHELL = "\/abc123\/";/);
  assert.match(worker, /if \(event\.request\.method !== 'GET'\) return;/);
  assert.match(worker, /caches\.match\(SHELL\)/);
  const manifest = webManifest({ name: 'Gym bookings', start: '/abc123/' });
  assert.equal(manifest.start_url, '/abc123/');
  assert.equal(manifest.scope, '/abc123/');
  assert.equal(manifest.display, 'standalone');
});

// ------------------------------------------------------------------ recovery fixture helpers

test('the recovery fixture reads its next step from the checkpoint alone and compares evidence without the volatile parts', () => {
  assert.equal(stepFromCheckpoint('## Checkpoint\ndone: x\nnext: write src/cancel.js for AC-1\n'), 2);
  assert.equal(stepFromCheckpoint('next: commit on req/REQ-001 and run vibekit verify'), 4);
  assert.equal(stepFromCheckpoint('next: set REQ-001 tested'), 5);
  assert.equal(stepFromCheckpoint('next: something else'), null);

  const a = normaliseEvidence('## Evidence\n\ncommit abc1234 · 2026-09-24T10:00:00Z\n\n- build `node -e ok`  exit 0  1s\n- test `node --test`  exit 0  12s\n\n## Log\n');
  const b = normaliseEvidence('## Evidence\n\ncommit def5678 · 2026-09-25T10:00:00Z\n\n- build `node -e ok`  exit 0  0s\n- test `node --test`  exit 0  9s\n');
  assert.equal(a, b);
  assert.notEqual(a, normaliseEvidence('## Evidence\n\n- build `node -e ok`  exit 1  0s\n'));

  const one = seeded(42);
  const two = seeded(42);
  assert.equal(one(), two());
  assert.ok(one() >= 0 && one() < 1);
});

// ------------------------------------------------------------------ generated files keep their local tail

test('a human approval below <!-- local --> in a generated folder file survives regeneration', async () => {
  const root = tempDir('vibekit-local-');
  const config = { name: 'p', description: null, architecture: 'layered', stack: {}, commands: {}, entities: [] };
  await generateFolder(root, config, { folder: 'vibekit' });
  const path = join(root, 'vibekit/product/design/tokens.md');
  const first = await readFile(path, 'utf8');
  assert.match(first, /^<!-- generated by vibekit/);
  await writeFile(path, `${first.trimEnd()}\n\n<!-- local -->\napproved: 2026-09-24 by You\n`);

  await generateFolder(root, config, { folder: 'vibekit' });
  const second = await readFile(path, 'utf8');
  assert.match(second, /^<!-- generated by vibekit/, 'still generated, still ours');
  assert.match(second, /<!-- local -->\napproved: 2026-09-24 by You/, 'the approval is still there');
  const { approvalOf } = await import('../src/folder/workflow.js');
  assert.equal(approvalOf(second)?.by, 'You');
});
