# Removes every trace of VibeKit from this machine, then installs it fresh from this copy.
# Leaves Claude Code, your Claude sign-in, Cursor, your other plugins and your projects alone.
#
# Usage (from Claude or PowerShell):
#   Expand-Archive "$HOME\Downloads\vibekit.zip" -DestinationPath "$env:TEMP\vibekit-fresh" -Force
#   & "$env:TEMP\vibekit-fresh\vibekit\plugin\scripts\reset.ps1"
$ErrorActionPreference = 'Continue'
$source = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path.TrimEnd('\', '/')
$target = [IO.Path]::Combine($HOME, 'tools', 'vibekit')
$pluginsDir = [IO.Path]::Combine($HOME, '.claude', 'plugins')

function Write-Step($message) { Write-Host ''; Write-Host "== $message" }

Write-Step 'Removing the old VibeKit plugin from Claude Code'
if (Get-Command claude -ErrorAction SilentlyContinue) {
  & claude plugin uninstall vibekit@vibekit 2>&1 | Out-Host
  & claude plugin marketplace remove vibekit 2>&1 | Out-Host
}
foreach ($leftover in @([IO.Path]::Combine($pluginsDir, 'cache', 'vibekit'), [IO.Path]::Combine($pluginsDir, 'marketplaces', 'vibekit'))) {
  if (Test-Path $leftover) { Remove-Item -Recurse -Force $leftover -ErrorAction SilentlyContinue; Write-Host "removed $leftover" }
}

Write-Step 'Removing VibeKit subagents from Cursor'
$cursorAgentsDir = [IO.Path]::Combine($HOME, '.cursor', 'agents')
$cursorTeamSkills = [IO.Path]::Combine($HOME, '.cursor', 'skills', 'vibekit')
if (Test-Path $cursorTeamSkills) { Remove-Item -Recurse -Force $cursorTeamSkills; Write-Host "removed $cursorTeamSkills" }
if (Test-Path $cursorAgentsDir) {
  Get-ChildItem -Path $cursorAgentsDir -Filter '*.md' | Where-Object { (Get-Content -Raw -Path $_.FullName) -match 'Generated by VibeKit' } | ForEach-Object { Remove-Item -Force $_.FullName; Write-Host "removed $($_.FullName)" }
}

Write-Step 'Removing the old vibekit command'
if (Get-Command npm -ErrorAction SilentlyContinue) { & npm uninstall -g vibekit 2>&1 | Out-Host }

Write-Step 'Removing old files and saved preferences'
$sameFolder = (Test-Path $target) -and ((Resolve-Path $target).Path.TrimEnd('\', '/') -eq $source)
if (-not $sameFolder) {
  if (Test-Path $target) { Remove-Item -Recurse -Force $target; Write-Host "removed $target" }
  New-Item -ItemType Directory -Force -Path (Split-Path $target) | Out-Null
  Copy-Item -Recurse -Force -Path $source -Destination $target
  Write-Host "copied the fresh version to $target"
}
foreach ($saved in @('preferences.json', 'components.json')) {
  $file = [IO.Path]::Combine($HOME, '.vibekit', $saved)
  if (Test-Path $file) { Remove-Item -Force $file; Write-Host "removed $file" }
}
Write-Host 'kept your list of projects (~/.vibekit/projects.json)'

Write-Step 'Installing fresh'
& ([IO.Path]::Combine($target, 'plugin', 'scripts', 'bootstrap.ps1')) --minimal --yes

Write-Step 'What Claude Code now has'
if (Get-Command claude -ErrorAction SilentlyContinue) { & claude plugin details vibekit@vibekit 2>&1 | Select-Object -First 12 | Out-Host }
Write-Host ''
Write-Host 'Done. In Claude Code: type /reload-plugins (or fully restart Cursor), then run /vibekit:setup'
