#!/usr/bin/env bash
# Removes every trace of VibeKit from this machine, then installs it fresh from this copy.
# Leaves Claude Code, your Claude sign-in, Cursor, your other plugins and your projects alone.
# Usage: unzip vibekit.zip -d /tmp/vibekit-fresh && bash /tmp/vibekit-fresh/vibekit/plugin/scripts/reset.sh
if [ -z "${BASH_VERSION:-}" ]; then exec bash "$0" "$@"; fi
set -o pipefail
SOURCE=$(cd "$(dirname "$0")/../.." && pwd)
TARGET="$HOME/tools/vibekit"
PLUGINS="$HOME/.claude/plugins"
step() { printf '\n== %s\n' "$1"; }

step 'Removing the old VibeKit plugin from Claude Code'
if command -v claude >/dev/null 2>&1; then
  claude plugin uninstall vibekit@vibekit || true
  claude plugin marketplace remove vibekit || true
fi
rm -rf "$PLUGINS/cache/vibekit" "$PLUGINS/marketplaces/vibekit"

step 'Removing VibeKit subagents from Cursor'
rm -rf "$HOME/.cursor/skills/vibekit"
if [ -d "$HOME/.cursor/agents" ]; then
  grep -l 'Generated by VibeKit' "$HOME"/.cursor/agents/*.md 2>/dev/null | while read -r agent; do rm -f "$agent" && echo "removed $agent"; done
fi

step 'Removing the old vibekit command'
command -v npm >/dev/null 2>&1 && npm uninstall -g vibekit || true

step 'Removing old files and saved preferences'
if [ "$(cd "$TARGET" 2>/dev/null && pwd)" != "$SOURCE" ]; then
  rm -rf "$TARGET"
  mkdir -p "$(dirname "$TARGET")"
  cp -R "$SOURCE" "$TARGET"
  echo "copied the fresh version to $TARGET"
fi
rm -f "$HOME/.vibekit/preferences.json" "$HOME/.vibekit/components.json"
echo 'kept your list of projects (~/.vibekit/projects.json)'

step 'Installing fresh'
bash "$TARGET/plugin/scripts/bootstrap.sh" --minimal --yes

step 'What Claude Code now has'
command -v claude >/dev/null 2>&1 && claude plugin details vibekit@vibekit | head -12
printf '\nDone. In Claude Code: type /reload-plugins (or restart it), then run /vibekit:setup\n'
