#!/usr/bin/env bash
# Removes every trace of Vibe-check-cli from this machine, then installs it fresh from this copy.
# Leaves Claude Code, your Claude sign-in, Cursor, your other plugins and your projects alone.
# Usage: unzip vibe-check-cli.zip -d /tmp/vibecheck-fresh && bash /tmp/vibecheck-fresh/vibe-check-cli/plugin/scripts/reset.sh
if [ -z "${BASH_VERSION:-}" ]; then exec bash "$0" "$@"; fi
set -o pipefail
SOURCE=$(cd "$(dirname "$0")/../.." && pwd)
TARGET="$HOME/tools/vibe-check-cli"
PLUGINS="$HOME/.claude/plugins"
step() { printf '\n== %s\n' "$1"; }

step 'Removing the old Vibe-check-cli plugin from Claude Code'
if command -v claude >/dev/null 2>&1; then
  claude plugin uninstall vibe-check-cli@vibe-check-cli || true
  claude plugin marketplace remove vibe-check-cli || true
fi
rm -rf "$PLUGINS/cache/vibe-check-cli" "$PLUGINS/marketplaces/vibe-check-cli"

step 'Removing Vibe-check-cli subagents from Cursor'
rm -rf "$HOME/.cursor/skills/vibe-check-cli"
if [ -d "$HOME/.cursor/agents" ]; then
  grep -l 'Generated by Vibe-check-cli' "$HOME"/.cursor/agents/*.md 2>/dev/null | while read -r agent; do rm -f "$agent" && echo "removed $agent"; done
fi

step 'Removing the old vibecheck command'
command -v npm >/dev/null 2>&1 && npm uninstall -g vibe-check-cli || true

step 'Removing old files and saved preferences'
if [ "$(cd "$TARGET" 2>/dev/null && pwd)" != "$SOURCE" ]; then
  rm -rf "$TARGET"
  mkdir -p "$(dirname "$TARGET")"
  cp -R "$SOURCE" "$TARGET"
  echo "copied the fresh version to $TARGET"
fi
rm -f "$HOME/.vibe-check-cli/preferences.json" "$HOME/.vibe-check-cli/components.json"
echo 'kept your list of projects (~/.vibe-check-cli/projects.json)'

step 'Installing fresh'
bash "$TARGET/plugin/scripts/bootstrap.sh" --minimal --yes

step 'What Claude Code now has'
command -v claude >/dev/null 2>&1 && claude plugin details vibe-check-cli@vibe-check-cli | head -12
printf '\nDone. In Claude Code: type /reload-plugins (or restart it), then run /vibe-check-cli:setup\n'
