const control = (id, title, rule, acceptance, asvs, impl) => ({ id, title, rule, acceptance, asvs, impl });

export const CONTROLS = [
  control('bff-cookie', 'Cookie sessions via the backend',
    'Browser clients never hold tokens: the backend keeps sessions in Secure, HttpOnly, SameSite cookies and protects state changes against CSRF.',
    'Given a signed-in browser session, when cookies are inspected, then the session cookie is Secure, HttpOnly and SameSite, and a state-changing request without a valid anti-forgery token is rejected',
    'V3.4, V4.2.2',
    { dotnet: 'ASP.NET Core cookie auth (BFF pattern) + antiforgery', php: 'Laravel Sanctum SPA cookie auth + CSRF', node: 'Server session cookies + csrf-csrf', python: 'Django sessions + CSRF middleware', java: 'Spring Security session + CSRF token' }),
  control('jwt-rotation', 'Short-lived tokens with refresh rotation',
    'Access tokens live at most 15 minutes; refresh tokens rotate on every use and are revoked on reuse or sign-out.',
    'Given a refresh token that was already used, when it is presented again, then the request is rejected and the whole token family is revoked',
    'V3.5',
    { dotnet: 'JWT bearer + refresh-token rotation table', php: 'Laravel Sanctum/Passport token expiry + rotation', node: '@nestjs/jwt + rotating refresh tokens', python: 'djangorestframework-simplejwt with rotation and blacklist', java: 'Spring Authorization Server token settings' }),
  control('oauth-pkce', 'OAuth 2.0 with PKCE for mobile and API clients',
    'Mobile, desktop and third-party clients use the authorization-code flow with PKCE; no client secrets ship inside apps.',
    'Given a mobile sign-in, when the authorization code is exchanged without the matching PKCE verifier, then the exchange fails',
    'V51 (OAuth)',
    { dotnet: 'OpenIddict or Duende with PKCE', php: 'Laravel Passport with PKCE', node: 'oidc-provider with PKCE', python: 'django-oauth-toolkit with PKCE', java: 'Spring Authorization Server with PKCE' }),
  control('lockout', 'Login throttling and lockout',
    'Throttle and temporarily lock accounts after repeated failed sign-ins; never reveal whether an account exists.',
    'Given 5 failed sign-ins within 15 minutes, when another attempt is made, then the account is locked for 15 minutes, the attempt is logged, and the response does not reveal whether the account exists',
    'V2.2.1',
    { dotnet: 'ASP.NET Core Identity lockout + rate limiting middleware', php: 'Laravel RateLimiter + Fortify throttling', node: '@nestjs/throttler + per-account failure counter', python: 'django-axes', java: 'Spring Security + Bucket4j' }),
  control('mfa-all', 'MFA for all users',
    'Every account enrols a second factor (TOTP or WebAuthn); recovery codes are single-use and hashed.',
    'Given a user without a second factor, when they sign in, then they must enrol TOTP or WebAuthn before reaching the app',
    'V2.7, V2.8',
    { dotnet: 'ASP.NET Core Identity TOTP + WebAuthn (Fido2.AspNet)', php: 'Laravel Fortify 2FA', node: 'otplib + @simplewebauthn/server', python: 'django-otp + django-webauthn', java: 'Spring Security MFA + WebAuthn4J' }),
  control('password-policy', 'Modern password policy',
    'Passwords follow NIST 800-63B: at least 12 characters, checked against breached-password lists, no forced periodic rotation; hashed with a slow adaptive algorithm.',
    'Given a password found in a breached-password list, when a user tries to set it, then it is rejected with a clear message',
    'V2.1',
    { dotnet: 'Identity password options + HIBP k-anonymity check; PasswordHasher (PBKDF2)', php: 'Laravel Password::uncompromised(); bcrypt/argon2id', node: 'argon2id + HIBP k-anonymity check', python: 'Django validators + pwned-passwords-django; Argon2 hasher', java: 'Spring Security Argon2PasswordEncoder + HIBP check' }),
  control('session-timeout', 'Idle timeout and re-authentication',
    'Sessions expire after inactivity and sensitive actions (role changes, exports, deletions) require recent re-authentication.',
    'Given a session idle for longer than the configured timeout, when the user acts, then they must sign in again; and a role change requires re-authentication within the last 5 minutes',
    'V3.3',
    { dotnet: 'Cookie sliding expiration + re-auth policy', php: 'Laravel session lifetime + password.confirm middleware', node: 'Session TTL + step-up guard', python: 'SESSION_COOKIE_AGE + sudo-mode decorator', java: 'Spring session timeout + step-up auth' }),
  control('idp-mfa', 'MFA enforced at the identity provider',
    'The identity provider enforces MFA and conditional access; the app rejects tokens without the expected authentication context (amr/acr).',
    'Given a token whose amr claim lacks MFA, when it is presented to an admin endpoint, then access is denied',
    'V2.7',
    { dotnet: 'Entra ID Conditional Access + amr/acr claim policy', generic: 'IdP MFA policy + amr/acr claim check' }),
  control('least-privilege', 'Least privilege and access reviews',
    'Users get the smallest role that works; roles are reviewed on a schedule and dormant accounts are disabled.',
    'Given an account unused for 90 days, when the nightly job runs, then the account is disabled and the event is audited',
    'V4.1.3',
    { generic: 'Role catalogue + scheduled dormant-account job' }),
  control('rbac', 'Role- and policy-based authorization',
    'Every endpoint declares its policy; authorization is enforced on the server, deny by default. UI checks are cosmetic only.',
    'Given a user without the required role, when they call a protected endpoint directly, then the API returns 403 and the attempt is logged',
    'V4.1',
    { dotnet: 'ASP.NET Core policy-based authorization, fallback policy = authenticated', php: 'Laravel Gates and Policies', node: 'NestJS guards + CASL', python: 'DRF permission classes + django-rules', java: 'Spring Security method security' }),
  control('object-level', 'Object-level access checks (no IDOR)',
    'Every read and write checks that the caller may access that specific record, not just that type of record.',
    'Given user A, when they request a record owned by user B by changing its id, then the API returns 404 or 403 and never the record',
    'V4.2.1',
    { dotnet: 'Resource-based authorization handlers', php: 'Policies with model arguments', node: 'CASL ability checks per entity', python: 'Object-level permissions (django-rules)', java: 'Spring @PostAuthorize / ACL checks' }),
  control('admin-separation', 'Separated admin area',
    'Administrative functions live behind a separate policy (and route prefix), with stricter session rules and full auditing.',
    'Given a non-admin user, when they access any /admin route, then access is denied and audited',
    'V4.3',
    { generic: 'Admin route group + stricter policy + audit' }),
  control('tenant-isolation', 'Tenant isolation',
    'Every query is scoped to the caller\'s tenant at the data layer; cross-tenant access is impossible by construction.',
    'Given two tenants, when tenant A queries any list or record endpoint, then no tenant B data is ever returned',
    'V4.2',
    { dotnet: 'EF Core global query filters + PostgreSQL row-level security', php: 'Global scopes + tenant middleware', node: 'Prisma middleware + PostgreSQL RLS', python: 'django-tenants or RLS', java: 'Hibernate filters + PostgreSQL RLS' }),
  control('openbao', 'Secrets in OpenBao',
    'Secrets live in OpenBao (open-source Vault fork) and are injected at runtime; nothing secret is committed or baked into images.',
    'Given the repository and built images, when scanned for secrets, then none are found, and the app starts only with secrets provided by OpenBao',
    'V6.4',
    { generic: 'OpenBao KV + AppRole; injected at startup' }),
  control('platform-secrets', 'Platform secret store',
    'Secrets come from the platform\'s secret store, never from committed files; config is validated at startup.',
    'Given a missing required secret, when the app starts, then it fails fast with a clear error and no default value is used',
    'V6.4',
    { generic: 'Docker secrets / systemd credentials / Windows DPAPI / Kubernetes secrets' }),
  control('cloud-kms', 'Cloud secrets manager',
    'Secrets and keys live in the cloud provider\'s secrets manager, accessed by managed identity; no secrets in config.',
    'Given the deployed app, when its configuration is inspected, then it contains only secret references resolved via managed identity',
    'V6.4',
    { dotnet: 'Azure Key Vault + Managed Identity (Azure.Extensions.AspNetCore.Configuration.Secrets)', generic: 'Cloud secrets manager + workload identity' }),
  control('env-files', 'Environment variables only',
    'Secrets come from environment variables that are never committed; .env files are git-ignored and an .env.example documents keys.',
    'Given the repository, when scanned, then no .env file with values is committed and .env.example lists every required key',
    'V6.4',
    { generic: 'Environment variables + .env.example' }),
  control('field-encryption', 'Field-level encryption for personal data',
    'Personal and sensitive fields are encrypted at rest with keys held outside the database; access is logged.',
    'Given a stored record with personal data, when the database is read directly, then those fields are ciphertext',
    'V6.2, V8.3',
    { dotnet: 'ASP.NET Core Data Protection / EF Core value converters', php: 'Laravel encrypted casts', node: 'Envelope encryption with a KMS key', python: 'django-fernet-fields / pgcrypto', java: 'JPA AttributeConverter with KMS key' }),
  control('backups', 'Encrypted, tested backups',
    'Backups are encrypted, stored off-host, and restores are tested on a schedule.',
    'Given last night\'s backup, when the scheduled restore test runs, then the database restores and a smoke test passes',
    'V8.1',
    { generic: 'pg_dump/pgBackRest (or native) + encryption + monthly restore test' }),
  control('retention', 'Data retention and purge',
    'Each data category has a retention period; expired personal data is deleted or anonymised automatically, and data-subject requests can be fulfilled.',
    'Given personal data past its retention period, when the purge job runs, then it is deleted or anonymised and the job is audited',
    'V8.3.8',
    { generic: 'Retention policy table + scheduled purge job' }),
  control('audit-append-only', 'Tamper-evident audit log',
    'Security-relevant events are written to an append-only audit log that application users cannot edit or delete.',
    'Given an audit entry, when any application role tries to update or delete it, then the operation is refused',
    'V7.3',
    { generic: 'Append-only table (no UPDATE/DELETE grants) + hash chaining' }),
  control('headers-csp', 'Security headers and CSP',
    'Responses send HSTS, a strict Content-Security-Policy, X-Content-Type-Options, frame-ancestors and Referrer-Policy.',
    'Given any page or API response, when headers are inspected, then HSTS, CSP without unsafe-inline scripts, nosniff and frame-ancestors are present',
    'V14.4',
    { dotnet: 'NetEscapades.AspNetCore.SecurityHeaders + UseHsts', php: 'Middleware or spatie/laravel-csp', node: 'helmet', python: 'SecurityMiddleware + django-csp', java: 'Spring Security headers()' }),
  control('rate-limit', 'API rate limiting',
    'Public and authenticated endpoints are rate-limited per client and per user, with stricter limits on expensive operations.',
    'Given a client exceeding the rate limit, when it sends another request, then it receives 429 with Retry-After',
    'V11.1.4',
    { dotnet: 'ASP.NET Core rate limiting middleware', php: 'Laravel throttle middleware', node: '@nestjs/throttler', python: 'django-ratelimit / DRF throttling', java: 'Bucket4j' }),
  control('waf', 'Web application firewall',
    'A WAF with the OWASP Core Rule Set sits in front of the app.',
    'Given a request carrying a common SQL-injection payload, when it reaches the edge, then the WAF blocks it',
    'V13',
    { generic: 'Coraza or ModSecurity + OWASP CRS in Nginx (or a cloud WAF)' }),
  control('cors-allowlist', 'CORS allow-list',
    'Only explicitly listed origins may call the API with credentials; no wildcard origins.',
    'Given a request from an origin not on the allow-list, when it calls the API, then the browser receives no CORS permission',
    'V14.5.3',
    { generic: 'Explicit CORS policy with configured origins' }),
  control('sast', 'Static analysis in CI',
    'Every pull request runs SAST; high-severity findings fail the build.',
    'Given code with a known injection pattern, when CI runs, then the SAST job fails the build',
    'V1.14, V10',
    { generic: 'Semgrep Community Edition (semgrep scan --config auto --error)' }),
  control('deps', 'Dependency vulnerability audit',
    'Dependencies are audited on every build; known high-severity vulnerabilities fail CI.',
    'Given a dependency with a known high-severity vulnerability, when CI runs, then the build fails',
    'V14.2',
    { dotnet: 'dotnet list package --vulnerable + npm audit', php: 'composer audit + npm audit', node: 'npm audit --audit-level=high', python: 'pip-audit', java: 'OWASP Dependency-Check' }),
  control('containers', 'Container and IaC scanning',
    'Images and infrastructure files are scanned for vulnerabilities and misconfigurations before deploy.',
    'Given a Dockerfile running as root or an image with a critical CVE, when CI runs, then the scan fails the build',
    'V14.1',
    { generic: 'Trivy (fs + image, vuln and misconfig scanners)' }),
  control('secrets-scan', 'Secret scanning',
    'Commits are scanned for secrets in CI (and ideally a pre-commit hook); a leaked secret fails the build and is rotated.',
    'Given a commit containing a credential, when CI runs, then the secret-scan job fails',
    'V6.4',
    { generic: 'gitleaks' }),
  control('security-logs', 'Security event logging',
    'Sign-ins, failures, permission denials, admin actions and configuration changes are logged as structured events with a correlation id.',
    'Given a failed sign-in and a denied request, when logs are queried, then both appear as structured security events with user, IP, time and correlation id',
    'V7.1, V7.2',
    { dotnet: 'Serilog structured logging + correlation id middleware', php: 'Monolog JSON channel', node: 'pino', python: 'structlog', java: 'Logback JSON encoder' }),
  control('pii-redaction', 'PII redaction in logs',
    'Logs never contain passwords, tokens or unmasked personal data; redaction is enforced centrally.',
    'Given a request containing a password and an ID number, when it is logged, then both values are masked',
    'V7.1.1',
    { dotnet: 'Serilog destructuring policies / Microsoft.Extensions.Compliance.Redaction', generic: 'Central log redaction processor' }),
  control('alerts', 'Alerting on security anomalies',
    'Spikes in failed sign-ins, lockouts, permission denials and admin actions raise alerts to a monitored channel.',
    'Given 20 failed sign-ins in 5 minutes, when monitoring evaluates, then an alert is sent to the security channel',
    'V7.4',
    { generic: 'Grafana + Loki (or equivalent) alert rules' }),
  control('dast', 'Dynamic scan against staging',
    'An automated DAST baseline scan runs against staging before release; new high findings block the release.',
    'Given the staging URL, when the release pipeline runs, then a ZAP baseline scan completes with no new high-risk findings',
    'V1.14',
    { generic: 'ZAP baseline scan (ghcr.io/zaproxy/zaproxy:stable)' }),
];

CONTROLS.push(
  control('secure-storage', 'OS keystore for secrets on devices',
    'Tokens and secrets on devices live in the OS keystore (Keychain, Android Keystore, DPAPI / Credential Manager, libsecret), never in plain files or preferences.',
    'Given a signed-in app, when its local files, databases and preferences are inspected, then no tokens or secrets appear in plain text',
    'MASVS-STORAGE-1',
    { generic: 'flutter_secure_storage / expo-secure-store / MAUI SecureStorage / Tauri stronghold or keyring / Keychain + Android Keystore' }),
  control('code-signing', 'Signed releases',
    'Every release binary, app bundle and installer is code-signed in CI with keys held outside the repository; unsigned artefacts are never published.',
    'Given a release build, when its signature is verified, then it is signed with the organisation\'s certificate',
    'MASVS-RESILIENCE-2',
    { generic: 'Apple notarisation, Play App Signing, Authenticode / signtool, codesign + notarytool; keys in the CI secret store' }),
  control('signed-updates', 'Verified auto-updates',
    'Desktop auto-updates are served over TLS and their signature is verified before installation.',
    'Given an update package with an invalid signature, when the app checks for updates, then it refuses to install it',
    'V10.3',
    { generic: 'Tauri updater signatures / electron-updater with code signing / MSIX or Sparkle' }),
  control('cert-pinning', 'Certificate or key pinning',
    'Mobile and desktop clients pin the API\'s public key, with a backup pin and a rotation plan.',
    'Given a TLS-intercepting proxy with a trusted but different certificate, when the app calls the API, then the connection is refused',
    'MASVS-NETWORK-2',
    { generic: 'Platform network security config (Android) / URLSession pinning (iOS) / HTTP client pinning' }),
);

export const findControl = (id) => CONTROLS.find((item) => item.id === id);

const FAMILY_BY_COMPONENT = { aspnetcore: 'dotnet', laravel: 'php', nestjs: 'node', fastapi: 'python', django: 'python', spring: 'java', 'dotnet-vue': 'dotnet', 'dotnet-blazor': 'dotnet', 'php-laravel': 'php', 'node-ts': 'node', 'python-django': 'python', 'java-spring': 'java' };
const FAMILY_BY_LANGUAGE = { 'c#': 'dotnet', php: 'php', typescript: 'node', javascript: 'node', python: 'python', java: 'java' };

export function stackFamily(project) {
  if (FAMILY_BY_COMPONENT[project.security?.stack]) return FAMILY_BY_COMPONENT[project.security.stack];
  if (project.security?.stack) return 'generic';
  const language = project.stack.languages.map((name) => name.toLowerCase()).find((name) => FAMILY_BY_LANGUAGE[name]);
  return FAMILY_BY_LANGUAGE[language] ?? 'generic';
}

export const implementationFor = (item, family) => item.impl[family] ?? item.impl.generic ?? Object.values(item.impl)[0];
