import { accessSync, constants } from 'node:fs';
import { homedir } from 'node:os';
import { delimiter, dirname, join } from 'node:path';
import { mkdir } from 'node:fs/promises';
import { exists, readText, writeText } from '../fsutil.js';
import { pointerBody } from '../folder/templates.js';

/**
 * Detection, not selection (Init Spec §3). VibeKit finds which coding tools are on this machine
 * and writes a pointer file for every one of them, and AGENTS.md regardless, because the day
 * somebody opens the project in a tool that was not ticked, it has no rules and starts guessing.
 * Each file is about 150 tokens; writing them all has no symmetric downside.
 */

export const TOOLS = Object.freeze([
  { id: 'claude', label: 'Claude Code', bins: ['claude'], homes: ['.claude'], files: [] },
  { id: 'cursor', label: 'Cursor', bins: ['cursor', 'cursor-agent'], homes: ['.cursor'], files: ['.cursor/rules/vibekit.mdc'] },
  { id: 'codex', label: 'Codex', bins: ['codex'], homes: ['.codex'], files: [] },
  { id: 'gemini', label: 'Gemini CLI', bins: ['gemini'], homes: ['.gemini'], files: ['GEMINI.md'] },
  { id: 'copilot', label: 'GitHub Copilot', bins: [], homes: [], repo: ['.github'], files: ['.github/copilot-instructions.md'] },
  { id: 'windsurf', label: 'Windsurf', bins: ['windsurf'], homes: ['.codeium/windsurf', '.windsurf'], files: ['.windsurfrules'] },
  { id: 'cline', label: 'Cline', bins: [], homes: ['.cline', 'Documents/Cline'], files: ['.clinerules'] },
  { id: 'zed', label: 'Zed', bins: ['zed'], homes: ['.config/zed'], files: ['.rules'] },
  { id: 'aider', label: 'Aider', bins: ['aider'], homes: ['.aider'], files: ['.aider.conf.yml'] },
  { id: 'amazonq', label: 'Amazon Q', bins: ['q'], homes: ['.aws/amazonq'], files: ['.amazonq/rules/vibekit.md'] },
]);

/** Is a binary on PATH? Walked by hand: `which` itself is not on a PATH a test narrows to one folder. */
const onPath = (name, env) => {
  const entries = String(env.PATH ?? env.Path ?? '').split(delimiter).filter(Boolean);
  const names = process.platform === 'win32' ? [name, ...String(env.PATHEXT ?? '.EXE;.CMD;.BAT').split(';').map((ext) => `${name}${ext.toLowerCase()}`)] : [name];
  for (const dir of entries) {
    for (const candidate of names) {
      try {
        accessSync(join(dir, candidate), constants.X_OK);
        return true;
      } catch { /* not here */ }
    }
  }
  return false;
};

/** Which tools are here: a binary on PATH, a config folder under home, or a marker in the repo. */
export async function detectTools({ root, env = process.env, home = env.HOME ?? homedir(), only = null } = {}) {
  const found = [];
  for (const tool of TOOLS) {
    if (only && !only.includes(tool.id)) continue;
    const byBin = tool.bins.some((name) => onPath(name, env));
    const byHome = (await Promise.all(tool.homes.map((dir) => exists(join(home, dir))))).some(Boolean);
    const byRepo = (await Promise.all((tool.repo ?? []).map((dir) => exists(join(root, dir))))).some(Boolean);
    if (byBin || byHome || byRepo || (only && only.includes(tool.id))) found.push(tool);
  }
  return found;
}

const HEADER = '<!-- generated by vibekit · pointer file · the rules live in the vibekit/ folder -->';

function bodyFor(tool, file, config, folder) {
  const pointer = pointerBody(config, folder);
  if (file.endsWith('.mdc')) return ['---', 'description: VibeKit — the rules for changing this project', 'alwaysApply: true', '---', HEADER, '', pointer].join('\n');
  if (file === '.aider.conf.yml') return ['# generated by vibekit · Aider reads AGENTS.md for the rules', 'read:', '  - AGENTS.md', ''].join('\n');
  return `${HEADER}\n${pointer}`;
}

/** Only files VibeKit wrote before, or that do not exist, are written; a team's own file is left alone. */
async function ours(path) {
  if (!(await exists(path))) return true;
  const text = (await readText(path)) ?? '';
  return text.includes('generated by vibekit');
}

export const toolsStatePath = (root, folder) => join(root, folder, '.state/tools.json');

/**
 * Write the pointer files for the detected tools and remember which. Returns what was written and
 * which tools are new since the last run, so a later run can say so in one line.
 */
export async function writeToolFiles({ root, folder, config, tools }) {
  const statePath = toolsStatePath(root, folder);
  let previous = null;
  try { previous = JSON.parse((await readText(statePath)) ?? 'null'); } catch { previous = null; }
  const written = [];
  const kept = [];
  for (const tool of tools) {
    for (const file of tool.files) {
      const path = join(root, file);
      if (!(await ours(path))) { kept.push(file); continue; }
      await mkdir(dirname(path), { recursive: true });
      await writeText(path, bodyFor(tool, file, config, folder));
      written.push(file);
    }
  }
  const noticed = previous ? tools.filter((tool) => !previous.detected.includes(tool.id)) : [];
  await mkdir(dirname(statePath), { recursive: true });
  await writeText(statePath, `${JSON.stringify({ detected: tools.map((tool) => tool.id), written, at: new Date().toISOString() }, null, 2)}\n`);
  return { written, kept, noticed, first: !previous };
}

/** `--tools claude,cursor`: the opt-out. A flag, never a prompt. */
export function parseToolsFlag(value) {
  if (!value) return null;
  const ids = String(value).split(',').map((item) => item.trim().toLowerCase()).filter(Boolean);
  const unknown = ids.filter((id) => !TOOLS.some((tool) => tool.id === id));
  if (unknown.length) throw new Error(`--tools: ${unknown.join(', ')} not known. One of: ${TOOLS.map((tool) => tool.id).join(', ')}.`);
  return ids;
}
