import { extname, basename } from 'node:path';

/**
 * The header is the whole safety mechanism.
 *
 * A generated file carries it on line 1. The generator refuses to overwrite a file that does not,
 * because a missing header means a human edited the file, and a rule a human wrote is a decision.
 * Decisions do not get regenerated. Everything else in the format — safe re-runs, brownfield
 * adoption, the promise that nothing you typed is ever lost — rests on this one check.
 *
 * The refusal is reported by path and the run continues for every other file: one hand-edited
 * file should not cost a team the other nineteen.
 */

export const MARK = 'generated by vibekit · do not edit';

/**
 * The marker VibeKit wrote before this format existed.
 *
 * It counts as ours. The header rule exists to tell "a human owns this now" from "VibeKit wrote
 * this", and a file carrying an older VibeKit marker is plainly the second — refusing to
 * regenerate it would strand every project generated before the folder format on a pointer file
 * nothing could ever update.
 */
export const LEGACY_MARK = 'Generated by VibeKit';
export const LOCAL_MARKER = '<!-- local -->';

const HASH_COMMENT_FILES = new Set(['.gitattributes', '.cursorrules', '.gitignore']);
const HASH_COMMENT_EXTENSIONS = new Set(['.yml', '.yaml', '.toml', '.sh', '.ps1']);

/** Markdown takes an HTML comment; YAML and plain-text rule files take a `#` line. */
export function commentStyle(relativePath) {
  const name = basename(relativePath);
  if (HASH_COMMENT_FILES.has(name) || HASH_COMMENT_EXTENSIONS.has(extname(relativePath))) return 'hash';
  return 'html';
}

export const headerFor = (relativePath, source) => (commentStyle(relativePath) === 'hash'
  ? `# ${MARK} · source: ${source}`
  : `<!-- ${MARK} · source: ${source} -->`);

const firstLine = (content) => String(content).replace(/^﻿/, '').split('\n', 1)[0] ?? '';

export const hasHeader = (content) => {
  const first = firstLine(content);
  return first.includes(MARK) || first.includes(LEGACY_MARK);
};

/** The `source:` a file declares, or null when it carries no header. */
export function headerSource(content) {
  const match = firstLine(content).match(new RegExp(`${MARK} · source: ([\\w.-]+)`));
  return match ? match[1] : null;
}

export const withHeader = (relativePath, source, body) => `${headerFor(relativePath, source)}\n${body.startsWith('\n') ? body.slice(1) : body}`;

export const stripHeader = (content) => (hasHeader(content) ? String(content).split('\n').slice(1).join('\n') : String(content));

/**
 * A team's own additions to a pointer file live below `<!-- local -->` and survive a rewrite.
 * Without this the only way to add a tool-specific line is to break the header, which turns the
 * whole file foreign and stops it being regenerated at all.
 */
export function preserveLocal(existing, fresh) {
  if (typeof existing !== 'string') return fresh;
  const marker = existing.indexOf(LOCAL_MARKER);
  if (marker === -1) return fresh;
  const local = existing.slice(marker);
  return `${fresh.trimEnd()}\n\n${local.trimEnd()}\n`;
}

/**
 * What a re-run may do with a path it is about to write.
 *
 * `write`    — no file there, or it is ours and unchanged by hand
 * `skip`     — a generated path whose file lacks the header: a human owns it now
 * `keep`     — an authored file that already exists
 */
export function decide({ kindIsGenerated, existing }) {
  if (existing === null || existing === undefined) return 'write';
  if (!kindIsGenerated) return 'keep';
  return hasHeader(existing) ? 'write' : 'skip';
}
