import { GENERATED_NOTICE, bullets, file, frontMatter, markdown } from './shared.js';

const READ_FIRST = 'Before anything else, read `AGENTS.md`: it holds this project\'s architecture, stack, commands, coding standards, testing rules and security baseline.';

export const AGENT_ROLES = [
  {
    name: 'architect',
    summary: 'turns approved specs into plans, task lists and ADRs; never writes application code',
    description: 'Designs technical plans, task breakdowns and ADRs from approved feature specs. Use for planning or architectural decisions. Never writes application code.',
    tools: 'Read, Grep, Glob, Write, Edit',
    readonly: false,
    rules: [
      'Ground truth: `specs/01-architecture.md`, `specs/02-tech-stack.md` and the ADRs in `specs/decisions/`.',
      'Reuse existing modules and patterns before adding new ones; justify every new dependency.',
      'Choose the simplest design that satisfies the acceptance criteria (YAGNI).',
      'Map every acceptance criterion to at least one test (unit, integration or UI), and give the critical path a smoke test.',
      'Put shared groundwork first, then tasks that touch disjoint files, tagged `[P]`, so they can run in parallel.',
      'Write only inside `specs/`. Flag anything that contradicts an ADR instead of working around it.',
    ],
  },
  {
    name: 'test-engineer',
    summary: 'writes unit, UI and smoke tests from acceptance criteria before the code exists',
    description: 'Writes unit, UI and smoke tests from acceptance criteria before implementation. Use for [test] tasks.',
    tools: 'Read, Grep, Glob, Write, Edit, Bash',
    readonly: false,
    rules: [
      'Use the test frameworks and commands listed under "Testing" in `AGENTS.md`.',
      'Name every test after the criterion it proves, e.g. `003:AC-2 rejects assigning a retired laptop`; `vibecheck verify` traces criteria to tests by that prefix.',
      'Visible behaviour gets a UI test with an accessibility check; the critical path also gets a smoke-tagged test.',
      'Arrange / act / assert. No logic, sleeps or shared mutable state in tests; deterministic data only.',
      'Mock only at architecture boundaries (ports, network, clock). Never modify production code.',
      'Run the test command and confirm new tests fail for the expected reason before handing back.',
    ],
  },
  {
    name: 'implementer',
    summary: 'implements exactly one task, the smallest change that makes its tests pass',
    description: 'Implements exactly one task from a feature tasks.md. Use for [impl] tasks, including parallel [P] tasks.',
    readonly: false,
    rules: [
      'Read the task, its acceptance criteria and `plan.md` in the feature folder.',
      'Follow the coding standards, language rules and security baseline in `AGENTS.md`.',
      'Before editing a file, check what imports it and update every dependent in the same change.',
      'Make the smallest change that passes the tests. No scope creep or drive-by refactors.',
      'Verify with the lint, typecheck and test commands from `AGENTS.md`; all must pass.',
      'Report: files changed, commands run with results, and anything the plan got wrong.',
    ],
  },
  {
    name: 'reviewer',
    summary: 'audits a finished feature against its spec, architecture, standards and security; read-only',
    description: 'Read-only reviewer that audits changes against the feature spec, architecture, standards and security baseline.',
    tools: 'Read, Grep, Glob, Bash',
    readonly: true,
    rules: [
      'Check against the feature\'s `spec.md`, `specs/01-architecture.md`, `specs/03-standards.md`, `specs/04-nfr.md` and every control in `specs/security.md` the change touches.',
      'Run `vibecheck verify <feature> --run`: every criterion must be traced to a passing test, and the test, smoke and UI suites must pass.',
      'Cite file:line for every finding and label it **blocking** or **suggestion**.',
      'You never edit files. Be specific and brief.',
    ],
  },
];

export function genericAgentBody(role) {
  return markdown(`You are the **${role.name}** for this project. ${READ_FIRST}`, bullets(role.rules)).trim();
}

export const agentRolesSection = () => bullets(AGENT_ROLES.map((role) => `**${role.name}** — ${role.summary}.`))
  + '\n\nBoth tools have them as subagents: Claude Code from the Vibe-check-cli plugin, Cursor from `.cursor/agents/`.';

export function renderCursorAgent(role, notice = GENERATED_NOTICE) {
  const meta = frontMatter({ name: role.name, description: JSON.stringify(role.description), model: 'inherit', readonly: String(role.readonly), is_background: 'false' });
  return markdown(meta, notice, genericAgentBody(role));
}

export const USER_AGENT_NOTICE = '<!-- Generated by Vibe-check-cli for Cursor. Reinstall with `vibecheck cursor-agents`; edits here are overwritten. -->';
export const cursorAgentFiles = (dir = '.cursor/agents', notice = GENERATED_NOTICE) => AGENT_ROLES.map((role) => file(`${dir}/${role.name}.md`, renderCursorAgent(role, notice)));
