import { ARCHITECTURES } from '../architectures.js';
import { LANGUAGE_RULES, normalizeLanguage } from '../languages.js';

export const GENERATED_MARK = 'Generated by Vibe-check-cli';
export const GENERATED_NOTICE = `<!-- ${GENERATED_MARK} from specs/project.json. Edit that file and run \`vibecheck sync\`; manual edits here are overwritten. -->`;

export const file = (path, content) => ({ path, content });
export const bullets = (items) => items.filter(Boolean).map((item) => `- ${item}`).join('\n');
export const section = (title, body) => (body ? `## ${title}\n\n${body}` : '');
export const markdown = (...blocks) => `${blocks.filter(Boolean).join('\n\n')}\n`;
const flatJoin = (value) => [value].flat().filter(Boolean).join(', ');

export function frontMatter(fields) {
  const lines = Object.entries(fields)
    .filter(([, value]) => value !== undefined && value !== '')
    .map(([key, value]) => `${key}: ${value}`);
  return ['---', ...lines, '---'].join('\n');
}

const STACK_LABELS = {
  languages: 'Languages',
  frontend: 'Web frontend',
  mobile: 'Mobile',
  desktop: 'Desktop',
  backend: 'Backend',
  database: 'Database',
  auth: 'Auth',
  hosting: 'Hosting',
  other: 'Other',
};

export function stackTable(stack) {
  const rows = Object.entries(STACK_LABELS)
    .map(([key, label]) => [label, flatJoin(stack[key])])
    .filter(([, value]) => value);
  return ['| Layer | Choice |', '|---|---|', ...rows.map(([label, value]) => `| ${label} | ${value} |`)].join('\n');
}

export function commandBullets(commands) {
  const defined = Object.entries(commands).filter(([, command]) => command);
  return bullets(defined.map(([name, command]) => `${name}: \`${command}\``));
}

export function standardsBullets({ standards }) {
  const { testing } = standards;
  const testFirst = testing.tdd ? '; write the failing test first (TDD)' : '';
  return bullets([
    `Naming: ${standards.naming}`,
    `Testing: ${testing.framework}, ≥ ${testing.coverage}% coverage on changed code${testFirst}.`,
    standards.commits && `Commits: ${standards.commits}.`,
    standards.branching && `Branching: ${standards.branching}.`,
    ...standards.rules,
  ]);
}

export function architectureBullets(project) {
  const style = ARCHITECTURES[project.architecture.style];
  const sharedCore =
    project.targets.length > 1 &&
    'Business logic is written once and shared across targets; platform-specific code stays in presentation/adapter layers.';
  return bullets([...style.rules, sharedCore, ...project.architecture.notes]);
}

const NFR_LABELS = {
  accessibility: 'Accessibility',
  performance: 'Performance',
  security: 'Security',
  privacy: 'Privacy',
  i18n: 'Locales',
};

export function nfrBullets(nfr) {
  return bullets(Object.entries(NFR_LABELS).map(([key, label]) => flatJoin(nfr[key]) && `${label}: ${flatJoin(nfr[key])}`));
}

export function languageRules(project) {
  return project.stack.languages
    .map((name) => ({ name, ...LANGUAGE_RULES[normalizeLanguage(name)] }))
    .filter((language) => language.rules);
}

export function languageBullets(project) {
  return bullets(languageRules(project).map(({ name, rules }) => `**${name}** — ${rules.join(' ')}`));
}
