// Every piece of dashboard markup, written once and used twice.
//
// The server imports this module to render the page it writes to disk. The same file is read as
// text, has its `export` keywords stripped, and is inlined into the served page, where the same
// functions re-render sections as the build moves. That is the whole reason it exists: a
// server-rendered fallback and a live view that are generated by two different code paths drift,
// and the drift is invisible until someone with JavaScript disabled sees a page the team has not
// looked at in months.
//
// Two rules keep it usable in both places:
//
//   * No imports and no Node APIs. It has to run inside a <script> tag with nothing around it.
//   * `export` only ever at the start of a line, so stripping it is a one-line regex and not a
//     parser. `browserSource()` in page-chrome.js does the stripping.
//
// It is pure: state in, HTML string out. It decides nothing about the project and reads no files.

const ENTITIES = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
export const escape = (text) => String(text ?? '').replace(/[&<>"']/g, (char) => ENTITIES[char]);

// ── Icons ───────────────────────────────────────────────────────────────────────────────────
// Stroked 24×24 paths on Atlas's icon grid, drawn by `.ic` so they inherit currentColor.

export const ICONS = {
  home: '<path d="M3 11l9-7 9 7v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1v-9Z"/>',
  board: '<rect x="3" y="4" width="5" height="16" rx="1.5"/><rect x="9.5" y="4" width="5" height="11" rx="1.5"/><rect x="16" y="4" width="5" height="7" rx="1.5"/>',
  features: '<rect x="3" y="4" width="18" height="16" rx="3"/><path d="M3 10h18M9 10v10"/>',
  tests: '<rect x="3" y="3" width="18" height="18" rx="3"/><path d="m8 12 3 3 5-6"/>',
  issues: '<path d="M12 9v4M12 17h.01M10.3 3.9 2.6 17a2 2 0 0 0 1.7 3h15.4a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  cross: '<path d="m6 6 12 12M18 6 6 18"/>',
  dash: '<path d="M5 12h14"/>',
  star: '<path d="m12 3 2.7 5.6 6.3.9-4.5 4.4 1 6.1L12 17l-5.5 3 1-6.1L3 9.5l6.3-.9Z"/>',
  arrow: '<path d="M5 12h14m-6-6 6 6-6 6"/>',
  copy: '<rect x="9" y="9" width="11" height="11" rx="2"/><path d="M5 15V5a2 2 0 0 1 2-2h10"/>',
  cog: '<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/>',
  doc: '<rect x="4" y="3" width="16" height="18" rx="3"/><path d="M8 9h8M8 13h8M8 17h5"/>',
  info: '<circle cx="12" cy="12" r="9"/><path d="M12 8v5M12 16h.01"/>',
  lanes: '<path d="M4 6h16M4 12h10M4 18h13"/>',
  refresh: '<path d="M20 12a8 8 0 1 1-2.3-5.7"/><path d="M20 4v5h-5"/>',
  menu: '<path d="M4 7h16M4 12h16M4 17h16"/>',
  chevron: '<path d="m15 6-6 6 6 6"/>',
  sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',
  moon: '<path d="M20 14.5A8 8 0 0 1 9.5 4a8 8 0 1 0 10.5 10.5Z"/>',
  lock: '<rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',
};

export const icon = (name, className = 'ic') =>
  (ICONS[name] ? `<svg class="${className}" viewBox="0 0 24 24" aria-hidden="true">${ICONS[name]}</svg>` : '');

// ── Vocabulary ──────────────────────────────────────────────────────────────────────────────
// The lifecycle as the CLI defines it. Colour never carries meaning alone: every badge below
// also carries its word, because a red dot means nothing to someone who cannot see red.

export const STAGES = ['draft', 'approved', 'planned', 'in-progress', 'done'];
export const STAGE_WORDS = { draft: 'Draft', approved: 'Approved', planned: 'Planned', 'in-progress': 'In progress', done: 'Done', unknown: 'Unknown' };
export const STAGE_TONE = { draft: 'neutral', approved: 'info', planned: 'info', 'in-progress': 'accent', done: 'ok', unknown: 'neutral' };
export const SUITE_WORDS = { test: 'Unit', smoke: 'Smoke', ui: 'UI' };
// What a task's kind means, said the way you would say it out loud rather than as the notation
// the file carries. A page full of "[impl]" tells a reader nothing they did not already know.
export const TASK_KINDS = { test: 'Write the test first', impl: 'Build it', docs: 'Write it down' };
export const STATE_WORDS = { ok: 'Passing', flaky: 'Flaky', failed: 'Failing', missing: 'Not run' };
export const STATE_TONE = { ok: 'ok', flaky: 'warn', failed: 'danger', missing: 'neutral' };
// A gate switched off in project.json is not passing — it is not in play.
// A lane whose agent is gone. Not finished and not failed by its own account: nobody is working
// on it, which is the one thing a board must never show as work in progress.
export const LANE_WORDS = { ready: 'Ready', running: 'Building', finished: 'Finished', failed: 'Failed', stopped: 'Stopped — its agent is gone' };

export const QUEUE_WORDS = { queued: 'Waiting', running: 'Building', done: 'Finished', failed: 'Failed' };
export const QUEUE_TONE = { queued: 'info', running: 'accent', done: 'ok', failed: 'danger' };

export const GATE_TONE = { ok: 'ok', blocked: 'danger', off: 'neutral' };
export const GATE_MARK = { ok: 'ok', blocked: 'fail', off: 'na' };

export const pct = (done, total) => (total ? Math.round((done / total) * 100) : 0);
// Adding an "s" is right often enough to be worth doing, and wrong in exactly the places this
// page talks about most — "1 acceptance criterion" / "7 acceptance criteria". Irregular plurals
// are listed rather than guessed at.
const PLURALS = { criterion: 'criteria', 'acceptance criterion': 'acceptance criteria' };

export const plural = (count, word) =>
  `${count} ${count === 1 ? word : PLURALS[word] ?? `${word}s`}`;

// Evidence recorded against a different commit describes code that no longer exists. Saying so
// in these words, rather than showing a tick, is the difference between a report and a claim.
export const STALE_NOTE = 'This evidence no longer describes this code: it was recorded against an older commit.';

/**
 * Fill in the parts of a state that a caller left out. The collector always produces all of it,
 * but a page may also be rendered from a state that was saved by an older version, and a missing
 * key should show as nothing known — not throw halfway through drawing the page.
 */
export function normalise(state) {
  const tests = state?.tests ?? {};
  return {
    project: { name: 'Project', generatedAt: new Date().toISOString(), ...(state?.project ?? {}) },
    tests: { ok: 0, flaky: 0, failed: 0, missing: 0, suites: 0, stale: 0, untraced: 0, ...tests },
    next: state?.next ?? null,
    queue: { entries: [], draining: false, ...(state?.queue ?? {}) },
    tunnel: state?.tunnel ?? null,
    setup: state?.setup ?? null,
    problems: state?.problems ?? [],
    features: state?.features ?? [],
  };
}

// ── Derived ─────────────────────────────────────────────────────────────────────────────────

export const blocking = (feature) => feature.gates.filter((gate) => gate.state === 'blocked').length;
export const allSuites = (state) => state.features.flatMap((feature) => feature.tests.suites.map((suite) => ({ ...suite, feature })));

export function stats(state) {
  const features = state.features;
  return {
    featuresDone: features.filter((feature) => feature.status === 'done').length,
    features: features.length,
    tasksDone: features.reduce((total, feature) => total + feature.tasks.done, 0),
    tasks: features.reduce((total, feature) => total + feature.tasks.total, 0),
    healthy: state.tests.ok,
    suites: state.tests.suites,
    gates: features.reduce((total, feature) => total + blocking(feature), 0),
    untraced: state.tests.untraced,
  };
}

/**
 * Turn one of the CLI's problem lines into something a person reads at a glance.
 *
 * The CLI writes a single sentence because a terminal has one line to work with: a gate prefix,
 * the problem, an em dash, and what to do about it, with the command inline. On a page that is a
 * wall of text — so it is taken apart here rather than reworded at the source, because the
 * one-line form is still the right thing in a terminal and there is no second version to keep in
 * step. Anything that does not match the shape is shown exactly as it came.
 */
export function readIssue(text) {
  const withoutGate = String(text ?? '').replace(/^(evidence|review|design|docs|spec|traceability):\s*/i, '');
  const [problem, ...rest] = withoutGate.split(' — ');
  const advice = rest.join(' — ');
  // The command is the actionable part, and it belongs on a chip you can copy, not buried mid-
  // sentence. Both forms the CLI uses are recognised: a quoted shell command, and a slash command
  // with the feature it applies to.
  const quoted = advice.match(/run "([^"]+)"/)?.[1];
  const slash = advice.match(/run (\/[\w:-]+) on (\S+?)[,\s]/);
  return {
    title: problem.charAt(0).toUpperCase() + problem.slice(1),
    // Lifting the command out can leave the sentence hanging on a conjunction ("address them,
    // then and record the verdict"), so the seam is tidied rather than left showing.
    why: advice
      .replace(/run "[^"]+"\s*/, '')
      .replace(/run \/[\w:-]+ on \S+?[,\s]/, '')
      .replace(/,?\s*then\s+and\s+/, ', and ')
      .replace(/^[,;\s]+|[,;\s]+$/g, '')
      .trim(),
    command: quoted ?? (slash ? `${slash[1]} ${slash[2]}` : null),
  };
}

/** Everything the project disagrees with itself about, as one list the Issues page can show. */
export function issuesOf(state) {
  const rows = state.problems.map((text, index) => {
    const read = readIssue(text);
    return { id: `p${index}`, ...read, detail: 'A generated file and its source disagree', command: read.command ?? 'vibekit sync', feature: null };
  });
  for (const feature of state.features) {
    for (const gate of feature.gates) {
      for (const problem of gate.problems) {
        rows.push({
          id: `${feature.id}-${gate.id}-${rows.length}`,
          ...readIssue(problem),
          detail: `${feature.title ?? feature.id} · ${gate.label}`,
          feature: feature.id,
        });
      }
    }
  }
  return rows;
}

// ── Fragments ───────────────────────────────────────────────────────────────────────────────

export const badge = (tone, text, dot = true) => `<span class="badge ${tone}${dot ? '' : ' no-dot'}">${escape(text)}</span>`;
export const bar = (done, total, extra = '') =>
  `<span class="bar sm" ${extra}><i style="--w:${pct(done, total)}%"></i></span>`;

/**
 * A command, with a copy button. This is the honest form of an action the page cannot perform:
 * it hands over the exact thing to run rather than pretending to have run it.
 */
export const cmd = (command) => `<span class="cmd" title="${escape(command)}">${escape(command)}<button type="button" data-copy="${escape(command)}" aria-label="Copy command">${icon('copy')}</button></span>`;

export const gateMarks = (feature) => `<div class="gates">${feature.gates
  .map((gate) => `<span class="${GATE_MARK[gate.state]}" title="${escape(gate.label)}: ${gate.state === 'ok' ? 'passed' : gate.state === 'blocked' ? 'blocking' : 'not in play'}">${escape(gate.label[0])}</span>`)
  .join('')}</div>`;

export const kpi = (name, label, value, sub, delta = '', step = 0) => `<div class="kpi span-3" style="--i:${step}">
        <div class="top"><div class="icon">${icon(name)}</div>${delta}</div>
        <div><div class="label">${escape(label)}</div><div class="value">${escape(value)}</div><div class="t-caption">${escape(sub)}</div></div>
      </div>`;

export const alertBox = (tone, title, lines = []) => `<div class="alert ${tone}">${icon(tone === 'ok' ? 'check' : tone === 'info' ? 'info' : 'issues')}
        <div><b>${escape(title)}</b>${lines.length ? `<p>${lines.map((line) => `· ${escape(line)}`).join('<br>')}</p>` : ''}</div>
      </div>`;

export const empty = (title, detail) => `<div class="empty">${icon('check')}<b>${escape(title)}</b>${escape(detail)}</div>`;

const suiteState = (feature) => {
  const suites = feature.tests.suites;
  if (suites.some((suite) => suite.state === 'failed')) return 'failed';
  if (suites.some((suite) => suite.state === 'flaky')) return 'flaky';
  if (suites.length && suites.every((suite) => suite.state === 'ok')) return 'ok';
  return 'missing';
};

export function featureRow(feature, index) {
  const tests = suiteState(feature);
  return `<tr style="animation-delay:${index * 30}ms" data-key="feature-${escape(feature.id)}" data-feature="${escape(feature.id)}">
            <td><div class="cell-primary"><span class="thumb">${escape(feature.id.split('-')[0])}</span>
              <div><b>${escape(feature.title)}</b><span>${escape(feature.id)}</span></div></div></td>
            <td>${badge(STAGE_TONE[feature.status] ?? 'neutral', STAGE_WORDS[feature.status] ?? feature.status)}</td>
            <td class="num"><div class="flex items-center gap-2" style="justify-content:flex-end">${bar(feature.tasks.done, feature.tasks.total, 'style="width:60px"')}${feature.tasks.done}/${feature.tasks.total}</div></td>
            <td>${badge(STATE_TONE[tests], STATE_WORDS[tests])}</td>
            <td>${gateMarks(feature)}</td>
            <td class="num">${blocking(feature) ? badge('danger', String(blocking(feature))) : badge('ok', 'Clear')}</td>
            <td><div class="row-actions"><a href="#/feature/${escape(feature.id)}" data-tooltip="Open" aria-label="Open ${escape(feature.title)}">${icon('arrow')}</a></div></td>
          </tr>`;
}

export const featuresTable = (features) => (features.length
  ? `<div class="table-wrap"><table class="table">
          <thead><tr><th>Feature</th><th>Stage</th><th class="num">Tasks</th><th>Tests</th><th>Gates</th><th class="num">Blocking</th><th style="width:48px"></th></tr></thead>
          <tbody class="rows-anim">${features.map(featureRow).join('')}</tbody></table></div>`
  : empty('No features yet', 'Run vibekit feature "<name>" to add the first one.'));

// ── Pages ───────────────────────────────────────────────────────────────────────────────────
// `ctx.writable` is true only where a change can actually be written back — the served page with
// a control endpoint. Everywhere else the same affordance is a command to run, never a button
// that appears to change the project and does not.

export function pageOverview(state, ctx) {
  const s = stats(state);
  const next = state.next;
  const issues = issuesOf(state);
  return `
      <div class="page-head seq">
        <div style="--i:0"><h2>Overview</h2><p>Every feature, where it sits in the lifecycle, and what is holding it up.</p></div>
        <div class="cluster" style="--i:1"><a class="btn btn-ghost" href="#/board">Open board</a></div>
      </div>
      <div class="grid seq" style="--seq-base:70ms">
        ${kpi('features', 'Features complete', `${s.featuresDone}/${s.features}`, `${pct(s.featuresDone, s.features)}% of scope`, '', 2)}
        ${kpi('check', 'Tasks ticked', `${s.tasksDone}/${s.tasks}`, `${pct(s.tasksDone, s.tasks)}% of planned work`, '', 3)}
        ${kpi('tests', 'Suites healthy', `${s.healthy}/${s.suites}`, s.suites ? 'passing on a clean commit' : 'no suites defined', '', 4)}
        ${kpi('issues', 'Gates blocking', String(s.gates), s.gates ? 'must clear before done' : 'nothing blocking', s.gates ? `<span class="delta down">Action needed</span>` : '<span class="delta up">Clear</span>', 5)}
        <div class="span-12" style="--i:6">${next ? `<div class="callout">
          <div class="ico">${icon('star')}</div>
          <div><b>Do this next — ${escape(next.step)}${next.feature ? ` · ${escape(next.feature)}` : ''}</b><span>${escape(next.reason)}</span></div>
          ${cmd(next.command)}
        </div>` : ''}</div>
        <div class="card span-12" style="--i:7">
          <div class="card-head"><div class="card-title">Features<small>Open one for its gates, tests and fixes</small></div>
            <a class="btn btn-subtle btn-sm" href="#/features">View all</a></div>
          ${featuresTable(state.features)}
        </div>
        <div class="card span-6" style="--i:8">
          <div class="card-head"><div class="card-title">Tests<small>${plural(s.suites, 'suite')} across all features</small></div>
            ${badge(s.suites && s.healthy === s.suites ? 'ok' : 'warn', `${s.healthy}/${s.suites} healthy`)}</div>
          ${s.untraced ? alertBox('warn', 'One thing to fix', [`${plural(s.untraced, 'acceptance criterion')} with no test`]) : alertBox('ok', 'Every criterion is named by a test')}
          <p class="t-caption mt-3">Flaky is not passing — a suite that passes on some runs and not others does not count as evidence.</p>
        </div>
        <div class="card span-6" style="--i:9">
          <div class="card-head"><div class="card-title">Issues<small>Specs and generated files that disagree</small></div>
            ${issues.length ? badge('warn', plural(issues.length, 'item')) : badge('ok', 'None')}</div>
          ${issues.length ? `<div class="todo">${issues.slice(0, 3).map((issue) => `<div class="item">${badge('warn', 'Fix', false)}
            <div><b>${escape(issue.title)}</b><span>${escape(issue.detail)}</span></div>
            <a class="btn btn-subtle btn-sm" href="#/issues">Open</a></div>`).join('')}</div>`
    : empty('Nothing to fix', 'Specs and generated files agree.')}
        </div>
        ${tunnelCard(state, ctx, 10)}
      </div>`;
}

export function pageBoard(state, ctx) {
  const columns = STAGES.map((stage) => {
    const features = state.features.filter((feature) => feature.status === stage);
    const tone = stage === 'in-progress' ? 'running' : stage === 'done' ? 'done' : stage === 'draft' ? '' : 'review';
    return `<div class="col" data-col="${stage}">
            <div class="col-head ${tone}"><i></i>${STAGE_WORDS[stage]}<span class="count">${features.length}</span></div>
            <div class="col-body">${features.map((feature) => `<div class="task feature-card"${ctx.writable ? ' draggable="true"' : ''} data-key="card-${escape(feature.id)}" data-id="${escape(feature.id)}">
              <div class="top"><span class="repo">${escape(feature.id)}</span><span class="id">${escape(feature.id.split('-')[0])}</span></div>
              <h4><a href="#/feature/${escape(feature.id)}" style="text-decoration:none">${escape(feature.title)}</a></h4>
              <div class="meta">Tasks ${feature.tasks.done}/${feature.tasks.total} · Criteria ${feature.criteria.done}/${feature.criteria.total}</div>
              <div class="foot">${bar(feature.tasks.done, feature.tasks.total)}<span class="pct">${pct(feature.tasks.done, feature.tasks.total)}%</span></div>
              <div class="foot">${gateMarks(feature)}<span style="margin-left:auto">${blocking(feature) ? badge('danger', `${blocking(feature)} blocking`) : badge('ok', 'Gates clear')}</span></div>
            </div>`).join('') || '<div class="board-empty">Nothing here</div>'}</div>
          </div>`;
  }).join('');
  return `
      <div class="page-head seq">
        <div style="--i:0"><h2>Board</h2><p>${ctx.writable
    ? 'Drag a feature to change its status. Done is gated: every gate must be clear first.'
    : 'Read-only: status is written by the CLI. Serve the console with a write token to move features from here.'}</p></div>
        <div class="cluster" style="--i:1">${badge('neutral', `Engine: ${state.project.engine}`, false)}${badge('accent', state.project.autonomy === 'gated' ? 'Gated' : 'Auto-plan', false)}</div>
      </div>
      <div class="card seq" style="--i:2;padding:var(--sp-3)"><div class="board five" id="board">${columns}</div></div>`;
}

export function pageFeatures(state, ctx) {
  const s = stats(state);
  return `
      <div class="page-head seq">
        <div style="--i:0"><h2>Features</h2><p>${plural(s.features, 'feature')} · ${plural(s.gates, 'gate')} blocking</p></div>
        <div class="cluster" style="--i:1"><div class="tabs" id="ftabs"><button type="button" class="on" data-stage="">All</button>${STAGES.map((stage) => `<button type="button" data-stage="${stage}">${STAGE_WORDS[stage]}</button>`).join('')}</div></div>
      </div>
      <div class="card seq" style="--i:2" id="featuresCard">${featuresTable(state.features)}</div>`;
}

export function pageTests(state, ctx) {
  const suites = allSuites(state);
  const counted = (key) => suites.filter((suite) => suite.state === key).length;
  return `
      <div class="page-head seq">
        <div style="--i:0"><h2>Tests</h2><p>${plural(suites.length, 'suite')} across all features${state.tests.stale ? ` · ${state.tests.stale} recorded against an older commit` : ''}</p></div>
        <div class="cluster" style="--i:1">${cmd('vibekit verify --all --run')}</div>
      </div>
      <div class="tests-summary seq" style="--seq-base:60ms">${['ok', 'flaky', 'failed', 'missing'].map((key, index) => `
        <div class="card" style="--i:${index + 2}">${badge(STATE_TONE[key], STATE_WORDS[key])}<div class="value">${counted(key)}<small>suites</small></div></div>`).join('')}
      </div>
      <div class="grid seq" style="--seq-base:60ms">
        <div class="card span-8" style="--i:6">
          <div class="card-head"><div class="card-title">All suites</div></div>
          ${suites.length ? `<div class="table-wrap"><table class="table">
            <thead><tr><th>Feature</th><th>Suite</th><th>Result</th><th class="num">Runs</th><th class="num">Time</th><th>Command</th></tr></thead>
            <tbody class="rows-anim">${suites.map((suite, index) => `<tr style="animation-delay:${index * 25}ms">
              <td><a href="#/feature/${escape(suite.feature.id)}" style="text-decoration:none;font-weight:600">${escape(suite.feature.title)}</a></td>
              <td>${escape(SUITE_WORDS[suite.suite] ?? suite.suite)}</td>
              <td>${badge(STATE_TONE[suite.state], STATE_WORDS[suite.state])}</td>
              <td class="num">${suite.runs ? `${suite.passed}/${suite.runs} runs` : '<span class="t-muted">—</span>'}</td>
              <td class="num">${suite.seconds ? `${suite.seconds}s` : '<span class="t-muted">—</span>'}</td>
              <td>${suite.command ? cmd(suite.command) : '<span class="t-muted">not configured</span>'}</td>
            </tr>`).join('')}</tbody></table></div>` : empty('No suites defined', 'Add test commands to specs/project.json.')}
        </div>
        <div class="span-4 stack" style="--i:7">
          ${state.tests.stale ? alertBox('warn', `${plural(state.tests.stale, 'feature')} with stale evidence`, [STALE_NOTE]) : ''}
          ${state.tests.untraced ? alertBox('warn', 'One thing to fix', [`${plural(state.tests.untraced, 'acceptance criterion')} with no test naming it`]) : alertBox('ok', 'Every criterion is named by a test')}
          <div class="alert info">${icon('info')}<div><b>Flaky is not passing</b><p>A suite that passes on some runs and not others is flaky, and does not count as evidence.</p></div></div>
        </div>
      </div>`;
}

export function pageIssues(state, ctx) {
  const issues = issuesOf(state);
  return `
      <div class="page-head seq">
        <div style="--i:0"><h2>Issues</h2><p>Specs and generated files that disagree</p></div>
        <div class="cluster" style="--i:1">${issues.length ? badge('warn', `${plural(issues.length, 'thing')} to fix`) : badge('ok', 'None')}</div>
      </div>
      <div class="card seq" style="--i:2">
        ${issues.length ? `<div class="todo">${issues.map((issue) => `<div class="item" data-key="issue-${escape(issue.id)}">${badge('warn', 'Fix', false)}
          <div><b>${escape(issue.title)}</b><span>${escape(issue.detail)}</span>
            ${issue.why ? `<p class="t-caption mt-2">${escape(issue.why)}</p>` : ''}
            ${issue.command ? `<div class="mt-2">${cmd(issue.command)}</div>` : ''}</div>
          ${issue.feature ? `<a class="btn btn-subtle btn-sm" href="#/feature/${escape(issue.feature)}">Open feature</a>` : '<span></span>'}
        </div>`).join('')}</div>` : empty('No issues', 'Specs and generated files agree.')}
      </div>`;
}

/**
 * Where this feature stands, as one sentence someone could read out.
 *
 * Every part of it is already on the page somewhere — the stage, the task count, the blocked
 * gates. Saying it in a sentence is not decoration: a column of badges tells you what is true and
 * leaves you to work out what it means, and this is the working out.
 */
export function standing(feature) {
  const left = feature.tasks.total - feature.tasks.done;
  const blocked = feature.gates.filter((gate) => gate.state === 'blocked');
  const where = {
    draft: 'Being written. Nothing is being built yet.',
    approved: 'Agreed, and waiting for a plan.',
    planned: 'Planned and ready to build.',
    'in-progress': left
      ? `Being built — ${plural(left, 'task')} still open of ${feature.tasks.total}.`
      : 'Being built — every task is ticked.',
    done: 'Finished, with the evidence to say so.',
  }[feature.status] ?? 'Status unknown.';
  if (!blocked.length) return where;
  const names = blocked.map((gate) => gate.label.toLowerCase());
  const list = names.length === 1 ? names[0] : `${names.slice(0, -1).join(', ')} and ${names.at(-1)}`;
  return `${where} It cannot be marked done until the ${list} ${plural(blocked.length, 'gate').replace(/^\d+ /, '')} ${blocked.length === 1 ? 'clears' : 'clear'}.`;
}

/** The feature in its own words, or an honest note that nobody has written them. */
export function aboutCard(feature, step) {
  const about = feature.about ?? { problem: '', stories: [] };
  const told = about.problem || about.stories.length;
  return `<div class="card span-12" style="--i:${step}">
          <div class="card-head"><div class="card-title">What this is<small>From the spec, in the words it was written in</small></div>
            ${badge(STAGE_TONE[feature.status] ?? 'neutral', standing(feature).split('.')[0])}</div>
          ${told ? `${about.problem ? `<p>${escape(about.problem)}</p>` : ''}
          ${about.stories.length ? `<ul class="t-body" style="margin:var(--sp-3) 0 0;padding-left:1.1rem;display:grid;gap:6px">
            ${about.stories.map((story) => `<li>${escape(story)}</li>`).join('')}</ul>` : ''}`
    : alertBox('warn', 'Nobody has written down what this is for', [
      'The spec still has the template in it — no problem statement, no user stories.',
      'Everything below describes progress against a plan whose purpose was never recorded.',
    ])}
          <p class="t-caption mt-3">${escape(standing(feature))}</p>
        </div>`;
}

export function pageFeature(state, ctx, id) {
  const feature = state.features.find((entry) => entry.id === id);
  if (!feature) return `<div class="card">${empty('Feature not found', `Nothing here is called ${id ?? ''}.`)}</div>`;
  const at = STAGES.indexOf(feature.status);
  const track = STAGES.map((stage, index) => `<div class="s ${index < at ? 'done' : index === at ? 'now' : ''}">
          <i>${index < at ? icon('check') : index + 1}</i>${STAGE_WORDS[stage]}</div>${index < STAGES.length - 1 ? `<div class="line ${index < at ? 'done' : ''}"></div>` : ''}`).join('');
  const healthy = feature.tests.suites.filter((suite) => suite.state === 'ok').length;
  const fixes = feature.gates.flatMap((gate) => gate.problems.map((problem) => ({ gate, problem })));
  return `
      <div class="page-head seq">
        <div style="--i:0">
          <div class="crumb mb-3"><a href="#/features" style="text-decoration:none">Features</a><span>/</span><b>${escape(feature.id)}</b></div>
          <h2>${escape(feature.title)}</h2><p>${escape(feature.id)}</p>
        </div>
        <div class="cluster" style="--i:1">${badge(STAGE_TONE[feature.status] ?? 'neutral', STAGE_WORDS[feature.status] ?? feature.status)}
          ${feature.status === 'in-progress' ? queueButton(feature, state, ctx) : ''}
          <a class="btn btn-ghost" href="#/overview">Back to overview</a></div>
      </div>
      <div class="card seq" style="--i:2"><div class="stage-track">${track}</div></div>
      <div class="grid seq" style="--seq-base:60ms">
        ${aboutCard(feature, 25)}
        ${kpi('check', 'Criteria proven', `${feature.tests.trace.covered}/${feature.criteria.total}`,
    feature.tests.trace.missing.length ? `untested: ${feature.tests.trace.missing.map((n) => `AC-${n}`).join(', ')}` : 'all proven by a test', '', 3)}
        ${kpi('features', 'Tasks ticked', `${feature.tasks.done}/${feature.tasks.total}`, `${pct(feature.tasks.done, feature.tasks.total)}% of the plan`, '', 4)}
        ${kpi('tests', 'Suites healthy', `${healthy}/${feature.tests.suites.length}`, feature.tests.stale ? 'recorded against an older commit' : feature.tests.at ? 'on a clean commit' : 'never run', '', 5)}
        ${kpi('issues', 'Gates blocking', String(blocking(feature)), blocking(feature) ? 'must clear before done' : 'clear',
      blocking(feature) ? '<span class="delta down">Blocked</span>' : '<span class="delta up">Clear</span>', 6)}
        ${(feature.taskList ?? []).length ? `<div class="card span-12" style="--i:65">
          <div class="card-head"><div class="card-title">Tasks<small>${feature.tasks.done} of ${feature.tasks.total} done, in order</small></div></div>
          <div class="todo">${feature.taskList.map((task) => `<div class="item" data-key="task-${escape(feature.id)}-${escape(task.id)}">
            ${badge(task.done ? 'ok' : 'neutral', task.done ? 'Done' : 'To do', false)}
            <div><b>${escape(task.what)}</b><span>${escape(TASK_KINDS[task.kind] ?? task.kind)}${task.criteria.length ? ` · proves ${task.criteria.map((number) => `AC-${escape(number)}`).join(', ')}` : ' · not tied to a criterion'}${task.files.length ? ` · ${escape(task.files.join(', '))}` : ''}</span></div>
            <span class="t-caption nowrap">${escape(task.id)}${task.parallel ? ' · can run in parallel' : ''}</span>
          </div>`).join('')}</div>
        </div>` : ''}
        <div class="card span-5" style="--i:7">
          <div class="card-head"><div class="card-title">Gates<small>Every gate in play must pass to reach Done</small></div></div>
          ${feature.gates.map((gate) => `<div class="gate">
            <div class="st ${GATE_MARK[gate.state]}">${icon(gate.state === 'ok' ? 'check' : gate.state === 'blocked' ? 'cross' : 'dash')}</div>
            <div><b>${escape(gate.label)}</b><span>${gate.state === 'ok' ? 'Passed' : gate.state === 'off' ? 'Switched off in project.json' : escape(gate.problems[0] ?? 'Blocking')}</span></div>
          </div>`).join('')}
        </div>
        <div class="card span-7" style="--i:8">
          <div class="card-head"><div class="card-title">Tests<small>${feature.tests.trace.covered} of ${feature.criteria.total} criteria proven by a test</small></div>
            <div class="card-actions">${cmd(`vibekit verify ${feature.id} --run`)}</div></div>
          ${feature.tests.suites.length ? `<div class="table-wrap"><table class="table">
            <thead><tr><th>Suite</th><th>Result</th><th class="num">Runs</th><th class="num">Time</th></tr></thead>
            <tbody>${feature.tests.suites.map((suite) => `<tr><td><b>${escape(SUITE_WORDS[suite.suite] ?? suite.suite)}</b></td>
              <td>${badge(STATE_TONE[suite.state], STATE_WORDS[suite.state])}</td>
              <td class="num">${suite.runs ? `${suite.passed}/${suite.runs} runs` : '<span class="t-muted">—</span>'}</td>
              <td class="num">${suite.seconds ? `${suite.seconds}s` : '<span class="t-muted">—</span>'}</td></tr>`).join('')}</tbody></table></div>`
    : empty('No suites defined', 'Add test commands to specs/project.json.')}
          ${feature.tests.stale ? `<div class="mt-3">${alertBox('warn', 'Stale evidence', [STALE_NOTE])}</div>` : ''}
          ${feature.tests.trace.missing.length ? `<div class="mt-3">${alertBox('warn', 'One thing to fix', [`Untested criteria: ${feature.tests.trace.missing.map((n) => `AC-${n}`).join(', ')}`])}</div>` : ''}
        </div>
        ${feature.lanes.length ? `<div class="card span-12" style="--i:9">
          <div class="card-head"><div class="card-title">Lanes<small>Work that can run in parallel</small></div></div>
          <div class="col-body">${feature.lanes.map((lane) => `<div class="task">
            <div class="top"><span class="repo">${escape(lane.name)}</span><span class="id">${escape(LANE_WORDS[lane.state] ?? lane.state)}</span></div>
            <div class="meta">${escape(lane.detail)} · ${plural(lane.tasks.length, 'task')}</div>
          </div>`).join('')}</div>
        </div>` : ''}
        <div class="card span-12" style="--i:10">
          <div class="card-head"><div class="card-title">${fixes.length ? `${plural(fixes.length, 'thing')} to fix` : 'Nothing to fix'}<small>Work through these to clear the gates</small></div></div>
          ${fixes.length ? `<div class="todo">${fixes.map(({ gate, problem }) => `<div class="item">${badge('danger', gate.label, false)}
            <div><b>${escape(problem)}</b><span>${escape(gate.label)} gate</span></div><span></span>
          </div>`).join('')}</div>` : empty('Nothing to fix', 'Every gate in play is clear.')}
        </div>
      </div>`;
}

/** The wall-clock time something happened, which is all anyone wants from a queue. */
export const clock = (iso) => {
  const at = iso ? new Date(iso) : null;
  return at && !Number.isNaN(at.getTime()) ? at.toTimeString().slice(0, 5) : '';
};

/**
 * Queueing a feature is the instruction to build it: the entry is added and an agent starts.
 * There is no second button, because a queue you have to remember to start is a list.
 */
/**
 * The way in from outside, and the switch that closes it.
 *
 * A tunnel is a public hostname pointed at this machine. Being able to put it away without
 * stopping the console is the difference between a session you supervise and one you forget you
 * left open, so the state and the switch belong on the page you are already looking at — not
 * only in the terminal that started it.
 */
export function tunnelCard(state, ctx, step = 10) {
  const tunnel = state.tunnel;
  if (!tunnel) {
    return `<div class="card span-12" style="--i:${step}">
          <div class="card-head"><div class="card-title">Reach this from a phone<small>Only while the console is served</small></div></div>
          ${empty('Not being served', 'This page was written to a file. Run the command below to serve it live.')}
          <div class="mt-3">${cmd('vibekit dashboard --serve --tunnel')}</div>
        </div>`;
  }
  const on = tunnel.open;
  return `<div class="card span-12" style="--i:${step}">
          <div class="card-head"><div class="card-title">Reach this from a phone<small>${on ? 'A public address points here right now' : 'Nothing outside this machine can reach the console'}</small></div>
            ${badge(on ? 'warn' : 'ok', on ? 'Tunnel open' : 'Closed')}</div>
          ${on ? `<p class="t-caption">Open it on your phone. The random path keeps the page private and the write token is what stops a reader changing anything.</p>
          <div class="mt-3">${cmd(tunnel.reach ?? tunnel.url ?? '')}</div>`
    : `<p class="t-caption">Turning one on asks Cloudflare for a fresh address. The one you closed stays closed.</p>`}
          ${tunnel.error ? `<div class="mt-3">${alertBox('warn', 'The tunnel did not open', [tunnel.error])}</div>` : ''}
          ${ctx.writable ? `<div class="cluster mt-3">
            <button type="button" class="btn ${on ? 'btn-ghost' : 'btn-primary'} btn-sm" data-tunnel="${on ? 'stop' : 'start'}">${on ? 'Turn it off' : 'Turn one on'}</button>
            ${on ? '<span class="t-caption">Closing it drops anyone reading over it, including you if you came that way.</span>' : ''}
          </div>` : `<div class="mt-3">${cmd('vibekit dashboard --serve --tunnel')}</div>`}
        </div>`;
}

export function pageQueue(state, ctx) {
  const entries = [...(state.queue?.entries ?? [])].reverse();
  const waiting = entries.filter((entry) => entry.state === 'queued').length;
  const running = entries.filter((entry) => entry.state === 'running').length;
  const eligible = state.features.filter((feature) => feature.status === 'in-progress');
  return `
      <div class="page-head seq">
        <div style="--i:0"><h2>Queue</h2><p>${running ? `${plural(running, 'feature')} building.` : waiting ? `${plural(waiting, 'feature')} waiting.` : 'Nothing queued.'} Queued work starts straight away — one feature at a time, its lanes in parallel.</p></div>
        <div class="cluster" style="--i:1">${entries.length && ctx.writable ? '<button type="button" class="btn btn-ghost" id="queueClear">Clear what has not started</button>' : ''}</div>
      </div>
      <div class="grid seq" style="--seq-base:60ms">
        <div class="card span-7" style="--i:2">
          <div class="card-head"><div class="card-title">In the queue<small>Newest first</small></div>
            ${badge(running ? 'accent' : waiting ? 'info' : 'ok', running ? 'Building' : waiting ? `${waiting} waiting` : 'Idle')}</div>
          ${entries.length ? `<div class="todo">${entries.map((entry) => `<div class="item" data-key="queued-${escape(entry.id)}">
            ${badge(QUEUE_TONE[entry.state] ?? 'neutral', QUEUE_WORDS[entry.state] ?? entry.state, false)}
            <div><b>${escape(entry.feature)}</b><span>${escape(entry.note ?? (entry.state === 'running' ? `started ${clock(entry.startedAt)}` : entry.state === 'queued' ? `queued ${clock(entry.queuedAt)}` : `finished ${clock(entry.finishedAt)}`))}${entry.engine ? ` · ${escape(entry.engine)}` : ''}</span></div>
            ${ctx.writable && entry.state !== 'running' ? `<button type="button" class="btn btn-subtle btn-sm" data-unqueue="${escape(entry.id)}">Remove</button>` : '<span></span>'}
          </div>`).join('')}</div>` : empty('Nothing queued', 'Open a feature that is in progress and press Build it.')}
        </div>
        <div class="card span-5" style="--i:3">
          <div class="card-head"><div class="card-title">Ready to build<small>Features that are in progress</small></div></div>
          ${eligible.length ? `<div class="todo">${eligible.map((feature) => `<div class="item" data-key="ready-${escape(feature.id)}">
            ${badge('neutral', `${feature.tasks.done}/${feature.tasks.total}`, false)}
            <div><b>${escape(feature.title)}</b><span>${escape(feature.id)}</span></div>
            ${queueButton(feature, state, ctx)}
          </div>`).join('')}</div>` : empty('Nothing in progress', 'Move a feature to In progress on the board first.')}
          <p class="t-caption mt-3">An agent gets its own git worktree and only the tasks in its lane. Its output appears in the console at the foot of the page, and <b>vibekit merge</b> brings the work back.</p>
        </div>
      </div>`;
}

/** The one control that starts work. Read-only pages get the command instead of a dead button. */
export function queueButton(feature, state, ctx) {
  const already = (state.queue?.entries ?? []).find((entry) => entry.feature === feature.id && (entry.state === 'queued' || entry.state === 'running'));
  if (!ctx.writable) return cmd(`vibekit dispatch ${feature.id}`);
  if (already) return `<span class="t-caption nowrap">${escape(QUEUE_WORDS[already.state] ?? already.state)}</span>`;
  return `<button type="button" class="btn btn-primary btn-sm" data-queue="${escape(feature.id)}">Build it</button>`;
}

export const PAGES = {
  overview: { title: 'Overview', icon: 'home', render: pageOverview },
  board: { title: 'Board', icon: 'board', render: pageBoard },
  features: { title: 'Features', icon: 'features', render: pageFeatures },
  tests: { title: 'Tests', icon: 'tests', render: pageTests },
  issues: { title: 'Issues', icon: 'issues', render: pageIssues },
  queue: { title: 'Queue', icon: 'lanes', render: pageQueue },
};

/** One page by name. `feature` is the only one that takes an argument. */
export function renderPage(name, arg, given, ctx) {
  const state = normalise(given);
  if (name === 'feature') return pageFeature(state, ctx, arg);
  return (PAGES[name] ?? PAGES.overview).render(state, ctx);
}

/**
 * Every page, one after another. This is what the browser gets before any script runs — and all
 * it ever gets where scripts are blocked — so the anchors are real element ids matching the
 * hashes the sidebar links to, and the whole thing reads top to bottom without routing.
 */
export function renderAll(given, ctx) {
  const state = normalise(given);
  const section = (hash, html) => `<section id="${hash}" style="scroll-margin-top:12px;display:grid;gap:var(--gutter)">${html}</section>`;
  return [
    ...Object.keys(PAGES).map((name) => section(`/${name}`, renderPage(name, null, state, ctx))),
    ...state.features.map((feature) => section(`/feature/${feature.id}`, pageFeature(state, ctx, feature.id))),
  ].join('\n<hr class="divider">\n');
}

/** The sidebar, which is the same in both modes. */
export function navItems(given) {
  const state = normalise(given);
  const issues = issuesOf(state).length;
  const active = (state.queue?.entries ?? []).filter((entry) => entry.state === 'queued' || entry.state === 'running').length;
  return [
    { href: '#/overview', label: 'Overview', icon: 'home', route: 'overview' },
    { href: '#/board', label: 'Board', icon: 'board', route: 'board' },
    { href: '#/features', label: 'Features', icon: 'features', route: 'features', pip: String(state.features.length) },
    { href: '#/tests', label: 'Tests', icon: 'tests', route: 'tests', pip: `${state.tests.ok}/${state.tests.suites}` },
    { href: '#/issues', label: 'Issues', icon: 'issues', route: 'issues', pip: issues ? String(issues) : '' },
    { href: '#/queue', label: 'Queue', icon: 'lanes', route: 'queue', pip: active ? String(active) : '' },
  ];
}
