// Every piece of tracker markup, written once and used twice. Specification §57 and §70.
//
// The server imports this module to render the page it writes to disk. The same file is read as
// text, has its `export` keywords stripped, and is inlined into the served page, where the same
// functions re-render sections as the work moves. That is the whole reason it exists: a
// server-rendered fallback and a live view generated by two different code paths drift, and the
// drift is invisible until someone with JavaScript disabled sees a page nobody has looked at.
//
// Two rules keep it usable in both places:
//   * No imports and no Node APIs. It has to run inside a <script> tag with nothing around it.
//   * `export` only ever at the start of a line, so stripping it is a regex and not a parser.
//
// It is pure: state in, HTML string out. It decides nothing and reads no files.
//
// The writing rule that matters most here is §12's: every line a person reads leads with plain
// language. No file paths, no identifiers, no jargon, and choices phrased as outcomes. The
// technical detail is real and is one tap away, never in the way. §67 adds the second rule for
// screens: show the work, not the identifier — "Creating a list", not REQ-007.

const ENTITIES = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
export const escape = (text) => String(text ?? '').replace(/[&<>"']/g, (char) => ENTITIES[char]);

export const ICONS = {
  home: '<path d="M3 10.5 12 3l9 7.5V21H3z"/>',
  ask: '<path d="M9 9a3 3 0 1 1 4 2.8V14"/><circle cx="12" cy="17.5" r=".8"/>',
  board: '<rect x="3" y="4" width="6" height="16" rx="1"/><rect x="11" y="4" width="6" height="10" rx="1"/>',
  shield: '<path d="M12 3l7 3v6c0 4-3 7-7 9-4-2-7-5-7-9V6z"/>',
  clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  doc: '<path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/>',
  copy: '<rect x="9" y="9" width="11" height="11" rx="2"/><path d="M5 15V5a2 2 0 0 1 2-2h10"/>',
  chevron: '<path d="M9 6l6 6-6 6"/>',
  arrow: '<path d="M5 12h14"/><path d="M13 6l6 6-6 6"/>',
  tick: '<path d="M5 13l4 4L19 7"/>',
  issues: '<circle cx="12" cy="12" r="9"/><path d="M12 8v5"/><circle cx="12" cy="16.5" r=".8"/>',
  features: '<path d="M4 6h16M4 12h16M4 18h10"/>',
  tests: '<path d="M9 3v6l-5 9a2 2 0 0 0 2 3h12a2 2 0 0 0 2-3l-5-9V3"/>',
  lanes: '<path d="M4 5v14M12 5v14M20 5v14"/>',
  bug: '<path d="M8 9a4 4 0 0 1 8 0v5a4 4 0 0 1-8 0z"/><path d="M4 12h4M16 12h4M5 7l3 2M19 7l-3 2M5 17l3-2M19 17l-3-2"/>',
  coin: '<circle cx="12" cy="12" r="8"/><path d="M12 7v10M9.5 9.5h3.5a1.5 1.5 0 0 1 0 3h-2a1.5 1.5 0 0 0 0 3H15"/>',
  people: '<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3 19a6 6 0 0 1 12 0M14 19a4.5 4.5 0 0 1 7 0"/>',
  up: '<path d="M12 19V5M5 12l7-7 7 7"/>',
  down: '<path d="M12 5v14M5 12l7 7 7-7"/>',
  note: '<path d="M4 5h16v11l-4 4H4z"/><path d="M16 20v-4h4"/>',
  play: '<path d="M7 5l12 7-12 7z"/>',
};

export const icon = (name, className = 'ic') =>
  `<svg class="${className}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[name] ?? ICONS.doc}</svg>`;

export const STATUS_WORDS = {
  draft: 'Being written', ready: 'Ready to build', 'in-progress': 'Being built', blocked: 'Waiting on an answer',
  paused: 'Paused', tested: 'Waiting for review', review: 'Reviewed', done: 'Done',
};
export const STATUS_TONE = {
  draft: 'neutral', ready: 'info', 'in-progress': 'accent', blocked: 'danger',
  paused: 'neutral', tested: 'warn', review: 'info', done: 'ok',
};
export const SIZE_WORDS = { S: 'a small change', M: 'a feature', L: 'a new flow' };
export const SEVERITY_WORDS = { high: 'Serious', medium: 'Wrong, with a workaround', low: 'Cosmetic' };
export const VERDICT_TONE = { verified: 'ok', partial: 'warn', failed: 'danger' };

export const badge = (tone, text) => `<span class="badge ${tone}">${escape(text)}</span>`;
export const cmd = (command) => `<span class="cmd" title="${escape(command)}">${escape(command)}<button type="button" data-copy="${escape(command)}" aria-label="Copy command">${icon('copy')}</button></span>`;
export const plural = (count, word) => `${count} ${word}${count === 1 ? '' : 's'}`;

/** "Cancel a booking" → "Cancelling a booking": the work as it is happening (§67). */
export function gerund(title) {
  const text = String(title ?? '').trim();
  const [first, ...rest] = text.split(/\s+/);
  if (!first || !/^[a-z]+$/i.test(first) || /^(?:a|an|the|when|if|while|where)$/i.test(first)) return text;
  const word = first.toLowerCase();
  if (/ing$/.test(word)) return text;
  const irregular = { add: 'adding', run: 'running', set: 'setting', get: 'getting', put: 'putting', stop: 'stopping', plan: 'planning', log: 'logging', map: 'mapping', drop: 'dropping', ship: 'shipping', cancel: 'cancelling', flag: 'flagging', begin: 'beginning', submit: 'submitting', edit: 'editing', see: 'seeing' };
  const ing = irregular[word] ?? (word.endsWith('e') && !word.endsWith('ee') ? `${word.slice(0, -1)}ing` : `${word}ing`);
  return [ing.charAt(0).toUpperCase() + ing.slice(1), ...rest].join(' ');
}

/** Technical detail is never removed, only folded. A person who wants the id can always get it. */
export const details = (summary, body) =>
  `<details class="detail"><summary>${escape(summary)}</summary><div class="detail-body">${body}</div></details>`;

const section = (id, iconName, title, sub, body, count = null) => `
  <section class="card" id="card-${id}">
    <header class="card-head">
      <div class="card-title">${icon(iconName)}<h2>${escape(title)}</h2>${count !== null && count !== 0 ? `<span class="pip">${escape(String(count))}</span>` : ''}</div>
      <p class="card-sub">${escape(sub)}</p>
    </header>
    ${body}
  </section>`;

const empty = (text) => `<p class="empty">${escape(text)}</p>`;
const button = (act, id, label, { tone = '', kind = '', extra = '' } = {}) =>
  `<button type="button" class="act ${tone}" data-act="${escape(act)}" data-id="${escape(id)}"${kind ? ` data-kind="${escape(kind)}"` : ''}${extra}>${label}</button>`;
const readOnly = () => '<div class="actions"><span class="muted small">Read-only — sign in to act</span></div>';

// ---------------------------------------------------------------- the top: where we are, in one line

export function renderHero(state) {
  const s = state.stats ?? { requirements: 0, done: 0, percent: 0, blocked: 0, inProgress: 0 };
  const sprint = state.sprints?.current;
  const where = sprint ? `Sprint ${sprint.n} of ${state.sprints.sprints.length} — ${sprint.title}` : `Stage ${state.stage?.n ?? 0} — ${state.stage?.name ?? ''}`;
  const tiles = [
    { n: (state.needsYou ?? []).length, label: 'need you', tone: (state.needsYou ?? []).length ? 'danger' : 'ok' },
    { n: s.inProgress ?? 0, label: 'being built', tone: 'accent' },
    { n: s.blocked ?? 0, label: 'waiting on an answer', tone: s.blocked ? 'warn' : 'neutral' },
    { n: `${s.done}/${s.requirements}`, label: 'done', tone: 'ok' },
  ];
  return `
  <div class="hero">
    <div class="hero-where"><span class="eyebrow">Where we are</span><h2>${escape(where)}</h2></div>
    <div class="kpis">${tiles.map((tile) => `<div class="kpi ${tile.tone}"><b>${escape(String(tile.n))}</b><span>${escape(tile.label)}</span></div>`).join('')}</div>
    <div class="bar"><i style="width:${s.percent ?? 0}%"></i></div>
  </div>`;
}

// ---------------------------------------------------------------- Needs you (Decide)

const ACTION_WORDS = {
  answer: 'Answer in my own words', reject: 'Not doing it', approve: 'Approve', 'reject-gate': 'Send it back',
  done: 'Call it done', release: 'Release it', keep: 'Keep as a lesson', 'not-lesson': 'Not a lesson',
};

function needsYouItem(item, ctx) {
  // Options as buttons: one tap decides. Each posts the option's words as the answer.
  const options = item.options?.length
    ? `<div class="choices">${item.options.map((option, index) => button('option', item.id, `<span class="n">${index + 1}</span>${escape(option)}`, { tone: 'choice', extra: ` data-option="${escape(option)}"` })).join('')}</div>`
    : '';
  const buttons = ctx.writable && item.actions?.length
    ? `<div class="actions">${item.actions.map((action) =>
      button(action, item.id, escape(ACTION_WORDS[action] ?? action), { tone: /reject|not-lesson/.test(action) ? 'ghost' : '', kind: item.kind })).join('')}</div>`
    : readOnly();

  const waited = item.waitingDays > 0 ? `waiting ${plural(item.waitingDays, 'day')}` : 'new';
  return `
    <article class="item ${item.blocking ? 'blocking' : ''}" data-item="${escape(item.id)}">
      <p class="plain">${escape(item.plain)}</p>
      ${item.why ? `<p class="why">${escape(item.why)}</p>` : ''}
      ${ctx.writable ? options : (item.options?.length ? `<ol class="options">${item.options.map((option) => `<li>${escape(option)}</li>`).join('')}</ol>` : '')}
      ${item.checkpoint ? `<pre class="checkpoint">${escape(item.checkpoint)}</pre>` : ''}
      <div class="item-foot">
        ${item.blocking ? badge('danger', 'Work is stopped') : badge('neutral', waited)}
        ${details('details', `<p class="mono">${escape(item.id)} · ${escape(item.kind)}${item.file ? ` · ${escape(item.file)}` : ''}</p>`)}
      </div>
      ${buttons}
    </article>`;
}

export function cardNeedsYou(state, ctx) {
  const items = state.needsYou ?? [];
  const body = items.length
    ? `<div class="items">${items.map((item) => needsYouItem(item, ctx)).join('')}</div>`
    : empty('Nothing is waiting on you. The work can carry on without a decision.');
  return section('needs-you', 'ask', 'Needs you', 'One decision at a time, most blocking first. Every answer is written to the file and committed.', body, items.length || null);
}

// ---------------------------------------------------------------- Board (Where we are)

function workCard(requirement, ctx, { sprintIds = [] } = {}) {
  const holder = requirement.holder;
  const title = requirement.kind === 'bug' ? requirement.title : gerund(requirement.title);
  const line = requirement.step ?? STATUS_WORDS[requirement.status] ?? requirement.status;
  const evidence = requirement.evidence === 'green' ? badge('ok', 'tests green') : requirement.evidence === 'red' ? badge('danger', 'tests red') : '';
  const index = sprintIds.indexOf(requirement.id);
  const actions = ctx.writable ? [
    requirement.status === 'ready' && !holder ? button('start', requirement.id, `${icon('play', 'ic-sm')} Hand to an agent`) : '',
    holder ? button('release', requirement.id, 'Release', { tone: 'ghost' }) : '',
    requirement.status === 'review' && requirement.reviewed && !holder ? button('done', requirement.id, 'Call it done') : '',
    index > 0 ? button('up', requirement.id, icon('up', 'ic-sm'), { tone: 'ghost sq', extra: ' aria-label="Move up"' }) : '',
    index >= 0 && index < sprintIds.length - 1 ? button('down', requirement.id, icon('down', 'ic-sm'), { tone: 'ghost sq', extra: ' aria-label="Move down"' }) : '',
    index >= 0 && requirement.status !== 'done' ? button('defer', requirement.id, 'Defer', { tone: 'ghost' }) : '',
    button('note', requirement.id, icon('note', 'ic-sm'), { tone: 'ghost sq', extra: ' aria-label="Leave a note"' }),
    requirement.kind !== 'bug' ? `<span class="sizes">${['S', 'M', 'L'].map((size) => button('size', requirement.id, size, { tone: `ghost sq ${requirement.size === size ? 'on' : ''}`, extra: ` data-size="${size}" aria-label="Size ${size}"` })).join('')}</span>` : '',
  ].filter(Boolean).join('') : '';

  const criteria = requirement.criteria?.length
    ? `<ul class="criteria">${requirement.criteria.map((criterion) => `<li><b>${escape(criterion.id)}</b> ${escape(criterion.text)}${requirement.verified?.includes(criterion.id) ? ` ${badge('ok', 'test named')}` : ''}</li>`).join('')}</ul>`
    : '<p class="muted">No acceptance criteria yet.</p>';
  const detail = [
    `<p class="mono">${escape(requirement.id)}${requirement.size ? ` · ${escape(SIZE_WORDS[requirement.size] ?? requirement.size)}` : ''}${requirement.entities?.length ? ` · ${escape(requirement.entities.join(', '))}` : ''}${requirement.tokens ? ` · ~${escape(String(requirement.tokens))} tokens` : ''}</p>`,
    `<p class="mono">${escape(requirement.file ?? '')}</p>`,
    criteria,
    requirement.checkpoint ? `<pre class="checkpoint">${escape(requirement.checkpoint)}</pre>` : '',
    requirement.log?.length ? `<ul class="log">${requirement.log.slice(-4).map((line) => `<li>${escape(line)}</li>`).join('')}</ul>` : '',
  ].join('');

  return `
    <div class="chip ${STATUS_TONE[requirement.status] ?? 'neutral'} ${requirement.kind === 'bug' ? 'bug' : ''}" data-req="${escape(requirement.id)}">
      <b>${escape(title)}</b>
      <span class="step">${escape(line)}${holder ? ` · ${escape(holder.runner)}, ${escape(String(requirement.heldHours ?? 0))}h` : ''}</span>
      <div class="chip-badges">${badge(STATUS_TONE[requirement.status] ?? 'neutral', STATUS_WORDS[requirement.status] ?? requirement.status)}${evidence}${requirement.kind === 'bug' ? badge(`sev-${requirement.severity ?? 'medium'}`, requirement.severity ?? 'bug') : ''}</div>
      ${actions ? `<div class="chip-actions">${actions}</div>` : ''}
      ${details('details', detail)}
    </div>`;
}

export function cardWhereWeAre(state, ctx = {}) {
  const requirements = state.requirements ?? [];
  const sprints = state.sprints?.sprints ?? [];
  const byId = Object.fromEntries(requirements.map((entry) => [entry.id, entry]));

  const columns = sprints.length
    ? sprints.map((sprint) => {
      const items = sprint.ids.map((id) => byId[id]).filter(Boolean);
      const current = state.sprints.current?.n === sprint.n;
      return `
      <div class="column ${current ? 'current' : ''} ${sprint.closed ? 'closed' : ''}">
        <div class="column-head"><span>${escape(`Sprint ${sprint.n}`)}${sprint.title && sprint.title !== `Sprint ${sprint.n}` ? ` <em>${escape(sprint.title)}</em>` : ''}</span><span>${sprint.done}/${sprint.total}${sprint.closed ? ' · closed' : current ? ' · now' : ''}</span></div>
        ${items.length ? items.map((requirement) => workCard(requirement, ctx, { sprintIds: sprint.ids })).join('') : `<p class="muted small">${escape(sprint.lines?.[0] ?? 'Nothing listed here yet.')}</p>`}
      </div>`;
    }).join('')
    : (state.statuses ?? []).map((status) => ({ status, items: requirements.filter((entry) => entry.status === status && entry.kind !== 'bug') }))
      .filter((column) => column.items.length)
      .map((column) => `<div class="column"><div class="column-head"><span>${escape(STATUS_WORDS[column.status] ?? column.status)}</span><span>${column.items.length}</span></div>${column.items.map((requirement) => workCard(requirement, ctx)).join('')}</div>`).join('');

  const unplanned = (state.sprints?.unplanned ?? []).map((id) => byId[id]).filter(Boolean);
  const extra = unplanned.length ? `<div class="column"><div class="column-head"><span>Not in a sprint yet</span><span>${unplanned.length}</span></div>${unplanned.map((requirement) => workCard(requirement, ctx)).join('')}</div>` : '';
  const board = columns || extra ? `<div class="columns">${columns}${extra}</div>` : empty('No requirements yet. Add the first piece of work above.');

  const add = ctx.writable ? `
    <form class="add" data-form="add">
      <input class="input" name="title" placeholder="Add a piece of work, in your words" aria-label="Add a piece of work" required maxlength="140">
      <button type="submit" class="act">Add</button>
      <button type="button" class="act danger" data-act="hotfix" data-id="">Production is broken</button>
    </form>` : '';

  const s = state.stats ?? { done: 0, requirements: 0, blocked: 0 };
  const summary = `<p class="plain">${escape(`${s.done} of ${s.requirements} pieces of work are finished.`)}${s.blocked ? escape(` ${plural(s.blocked, 'piece')} stopped waiting for an answer.`) : ''}</p>`;
  return section('where', 'board', 'Board', 'Sprints as columns, work as cards. Titles say what is being done; the details say how.', `${summary}${add}${board}`);
}

// ---------------------------------------------------------------- Bugs

export function cardBugs(state, ctx = {}) {
  const bugs = state.bugs ?? [];
  const rows = bugs.length ? `<div class="items">${bugs.map((bug) => `
    <article class="item bugrow ${bug.severity === 'high' && bug.status !== 'done' ? 'blocking' : ''}" data-item="${escape(bug.id)}">
      <p class="plain">${escape(bug.title)}</p>
      <p class="why">${escape(SEVERITY_WORDS[bug.severity] ?? bug.severity ?? '')}${bug.foundBy ? escape(` · found by ${bug.foundBy}`) : ''}${bug.test ? '' : ' · no reproducing test yet — not work until there is one'}</p>
      <div class="item-foot">
        ${badge(`sev-${bug.severity ?? 'medium'}`, bug.severity ?? 'medium')}
        ${badge(STATUS_TONE[bug.status] ?? 'neutral', STATUS_WORDS[bug.status] ?? bug.status)}
        ${bug.verdict ? badge(VERDICT_TONE[bug.verdict] ?? 'neutral', bug.verdict) : ''}
        ${details('details', `<p class="mono">${escape(bug.id)}${bug.foundOn ? ` · on ${escape(bug.foundOn)}` : ''}${bug.test ? ` · ${escape(bug.test)}` : ''}</p>${bug.assessment ? `<p>${escape(bug.assessment)}</p>` : ''}`)}
      </div>
      ${ctx.writable && bug.status !== 'done' ? `<div class="actions"><span class="muted small">Severity:</span>${['high', 'medium', 'low'].map((severity) => button('severity', bug.id, severity, { tone: `ghost ${bug.severity === severity ? 'on' : ''}`, extra: ` data-severity="${severity}"` })).join('')}${button('note', bug.id, icon('note', 'ic-sm'), { tone: 'ghost sq', extra: ' aria-label="Leave a note"' })}</div>` : ''}
    </article>`).join('')}</div>` : empty('No bugs. A finding inside a requirement\'s own scope is fixed there and never becomes one.');
  const add = ctx.writable ? `
    <form class="add" data-form="bug">
      <input class="input" name="title" placeholder="Log a defect: what is wrong, as a person sees it" aria-label="Log a bug" required maxlength="140">
      <button type="submit" class="act">Log it</button>
    </form>` : '';
  const open = bugs.filter((bug) => bug.status !== 'done');
  return section('bugs', 'bug', 'Bugs', 'Each with a severity and what caught it. A bug closes only on a verified fix.', `${add}${rows}`, open.length || null);
}

// ---------------------------------------------------------------- Security

export function cardSecurity(state) {
  const security = state.security ?? { classified: [], findings: [], unclassified: [] };
  const open = (security.findings ?? []).filter((finding) => finding.severity === 'error');
  const posture = state.posture?.last ?? null;

  const classified = security.classified?.length
    ? `<p class="plain">${escape(`${plural(security.classified.length, 'kind')} of sensitive information here: ${security.classified.map((entity) => `${entity.name} (${entity.class})`).join(', ')}.`)} ${escape(`${plural(security.touching ?? 0, 'piece')} of work touch it.`)}</p>`
    : `<p class="plain">Nothing here is marked as personal, financial or secret yet.</p>`;

  const frameworks = posture?.frameworks?.length
    ? `<div class="frameworks">${posture.frameworks.map((framework) => {
      const total = Math.max(framework.applicable, 1);
      return `<div class="framework"><span class="fw-name">${escape(framework.id)}</span>
        <div class="stack-bar" title="${framework.met} met · ${framework.failed} failed · ${framework.human} need a person"><i class="ok" style="width:${Math.round((framework.met / total) * 100)}%"></i><i class="danger" style="width:${Math.round((framework.failed / total) * 100)}%"></i><i class="neutral" style="width:${Math.round((framework.human / total) * 100)}%"></i></div>
        <span class="fw-nums">${framework.met}/${framework.applicable}${framework.failed ? ` · ${framework.failed} failed` : ''}${framework.human ? ` · ${framework.human} need a person` : ''}</span></div>`;
    }).join('')}<p class="muted small">${escape(`Measured ${posture.date}. Green is met, red is failed, grey is what only a person can evidence — counted honestly, never as a pass.`)}</p></div>`
    : `<p class="why">No security scan yet. ${escape('vibekit security scan measures against the frameworks that apply and turns findings into bugs.')}</p>`;

  const findings = open.length
    ? `<ul class="findings">${open.map((finding) => `<li>${escape(finding.message)}</li>`).join('')}</ul>`
    : `<p class="ok-line">${icon('tick')} No open security findings in the folder.</p>`;
  const unclassified = security.unclassified?.length
    ? `<p class="why">${escape(`Not yet classified: ${security.unclassified.join(', ')}. Until each one is, nothing downstream can protect it.`)}</p>`
    : '';
  const count = open.length + (posture?.high ?? 0);
  return section('security', 'shield', 'Security', 'What is sensitive, what protects it, and how it measures against the standards that apply.', `${classified}${frameworks}${findings}${unclassified}`, count || null);
}

// ---------------------------------------------------------------- Cost

export function cardCost(state) {
  const cost = state.cost;
  if (!cost) return '';
  const spentPercent = cost.forecast ? Math.min(100, Math.round((cost.spent / cost.forecast) * 100)) : 0;
  const line = cost.sessions
    ? `<p class="plain">${escape(`Spent about ${cost.spent.toLocaleString()} tokens across ${plural(cost.sessions, 'session')}, against a forecast of ${cost.forecast.toLocaleString()} for what is left.`)}</p>`
    : `<p class="plain">${escape(`Nothing spent yet. The forecast for the work ahead is ${cost.forecast.toLocaleString()} tokens — a floor, not a prediction, until sessions are measured.`)}</p>`;
  const tiers = cost.byTier && Object.keys(cost.byTier).length
    ? `<ul class="findings">${Object.entries(cost.byTier).map(([tier, tokens]) => `<li>${escape(tier)}: ${escape(tokens.toLocaleString())} tokens</li>`).join('')}</ul>` : '';
  const escalation = cost.sessions ? `<p class="muted small">${escape(`Escalations: ${cost.escalated} of ${cost.sessions} sessions${cost.escalated / cost.sessions > 0.1 ? ' — over 10%, the cheap tier is too weak for this template' : ''}.`)}</p>` : '';
  return section('cost', 'coin', 'Cost', 'Spend against forecast, from the sessions that actually ran.', `${line}<div class="bar ${spentPercent > 100 ? 'danger' : ''}"><i style="width:${spentPercent}%"></i></div>${tiers}${escalation}`);
}

// ---------------------------------------------------------------- Schedule

export function cardSchedule(state) {
  const schedule = state.schedule ?? { remaining: 0, perWeek: null, basis: '' };
  const headline = schedule.perWeek
    ? `<p class="plain">${escape(`At the rate this team has actually been finishing work — ${schedule.perWeek} a week — the remaining ${plural(schedule.remaining, 'piece')} would take about ${plural(schedule.weeksLeft, 'week')}.`)}</p>`
    : `<p class="plain">${escape(`${plural(schedule.remaining, 'piece')} of work left. Not enough has finished yet to measure a rate.`)}</p>`;
  const sprints = state.sprints?.sprints?.length
    ? `<ol class="timeline-list">${state.sprints.sprints.map((sprint) => `<li class="${sprint.closed ? 'done' : state.sprints.current?.n === sprint.n ? 'now' : ''}"><b>${escape(`Sprint ${sprint.n}`)}</b> ${escape(sprint.title)} <span class="muted">${sprint.closed ? `closed by ${escape(sprint.closed.by)}` : `${sprint.done}/${sprint.total}`}</span></li>`).join('')}</ol>` : '';
  const risk = (state.assumptions ?? []).filter((assumption) => assumption.confidence === 'low' && assumption.bearing > 0);
  const risks = risk.length
    ? `<p class="why">Standing on guesses:</p><ul class="findings">${risk.map((assumption) =>
      `<li>${escape(assumption.text.replace(/·?\s*confidence:\s*\w+/i, '').trim())} — ${escape(`${plural(assumption.bearing, 'piece')} of work depends on it`)}</li>`).join('')}</ul>`
    : '';
  const deferred = state.sprints?.deferred?.length ? `<p class="muted small">${escape(`Deferred: ${state.sprints.deferred.join(', ')}.`)}</p>` : '';
  // §53: estimates are a non-goal. A rate measured from work that actually closed is a different
  // thing from an agent guessing how long something will take, and the page says which it is.
  return section('schedule', 'clock', 'Schedule', 'Derived from what has finished, never from an estimate.', `${headline}${sprints}${risks}${deferred}<p class="muted small">${escape(schedule.basis ?? '')}</p>`);
}

// ---------------------------------------------------------------- Docs and Team

export function cardDocs(state) {
  const docs = state.docs ?? [];
  const body = docs.length
    ? `<ul class="doclist">${docs.map((doc) => `<li>${icon('doc', 'ic-sm')} <b>${escape(doc.title)}</b> <span class="muted small">${escape(doc.path)}${doc.date ? ` · ${escape(doc.date)}` : ''}</span></li>`).join('')}</ul>`
    : `<p class="plain">No documents generated yet. ${escape('vibekit docs writes the HLD, LLD, API reference, data model and runbook from the folder, with diagrams; they cannot go stale because they are regenerated at every gate.')}</p>`;
  return section('docs', 'doc', 'Docs', 'Generated from the same facts the code is checked against.', body);
}

export function cardTeam(state) {
  const team = state.team ?? [];
  const body = team.length
    ? `<ul class="team">${team.map((person) => `<li><span class="avatar sm">${escape(String(person.name ?? '?').slice(0, 1).toUpperCase())}</span><b>${escape(person.name)}</b> <span class="muted">${escape(person.role)}</span>${person.email ? '' : ' <span class="badge warn">no email — cannot sign in</span>'}</li>`).join('')}</ul>`
    : `<p class="plain">Nobody is named as an approver yet, so every gate waits on a name nobody has. ${escape('vibekit team add "<Name> <email>" --role "tech lead"')}</p>`;
  return section('team', 'people', 'Team', 'Who may approve what. A login is mapped to a row here.', body);
}

// ---------------------------------------------------------------- the page

export function renderCards(state, ctx = {}) {
  return [cardNeedsYou(state, ctx), cardWhereWeAre(state, ctx), cardBugs(state, ctx), cardSecurity(state), cardCost(state), cardSchedule(state), cardDocs(state), cardTeam(state)].join('\n');
}

export function renderBudgetStrip(state) {
  const budget = state.budget;
  if (!budget) return '';
  const percent = budget.ceiling ? Math.min(100, Math.round((budget.alwaysLoaded / budget.ceiling) * 100)) : 0;
  return `
  <div class="strip">
    <span>Every task starts with <b>${escape(String(budget.alwaysLoaded))}</b> tokens of context, out of ${escape(String(budget.ceiling))} allowed.</span>
    <div class="bar thin ${percent > 90 ? 'danger' : ''}"><i style="width:${percent}%"></i></div>
  </div>`;
}

export function renderNext(state) {
  if (!state.next) return '';
  return `
  <div class="next ${state.next.forHuman ? 'human' : ''}">
    <div>
      <span class="eyebrow">${state.next.forHuman ? 'Waiting on you' : 'Next'}</span>
      <p>${escape(state.next.detail ?? '')}</p>
    </div>
    ${cmd(state.next.command)}
  </div>`;
}

/** The tunnel panel: how to reach this page from a phone, and whether it is reachable now. */
export function renderTunnel(state) {
  const tunnel = state.tunnel;
  if (!tunnel) {
    return `<div class="tunnel off"><b>Reach this from your phone</b><p class="muted">This page was written to a file. Serve it to open it anywhere:</p>${cmd('vibekit serve --tracker --tunnel cloudflare')}</div>`;
  }
  return `<div class="tunnel on"><b>Reachable from anywhere</b><p class="muted">${escape(tunnel.url ?? '')}</p>${tunnel.qr ? `<img class="qr" alt="QR code to open this page" src="${escape(tunnel.qr)}">` : ''}<p class="why">Behind your access policy. Scanning the code gets a sign-in, not access.</p></div>`;
}

export function renderAll(state, ctx = {}) {
  return [renderHero(state), renderNext(state), renderBudgetStrip(state), `<div class="cards">${renderCards(state, ctx)}</div>`, renderTunnel(state)].join('\n');
}
