import { execFileSync } from 'node:child_process';
import { chmod } from 'node:fs/promises';
import { join } from 'node:path';
import { readFrontMatter } from './frontmatter.js';
import { parseGuardrails } from './folder/checks.js';
import { DEFAULT_FOLDER } from './folder/layout.js';
import { readTasksState } from './folder/requirements.js';
import { exists, readText, writeText } from './fsutil.js';

/**
 * Commit rules, enforced by hooks. Specification §50.
 *
 * "`vibekit init` installs hooks (via `core.hooksPath`, so they are in the repo and versioned)."
 *
 * This is where "every commit carries `VibeKit-Requirement`" stops being a convention. Without it,
 * `why` and `trace` depend on an agent remembering a trailer, and the first one that forgets
 * breaks the provenance chain for every line it wrote. The hooks are shell one-liners that call
 * back into this module, so the rule lives in one place and the scripts never need editing.
 */

export const HOOKS_DIR = '.githooks';
export const HOOK_NAMES = Object.freeze(['pre-commit', 'commit-msg', 'pre-push', 'post-merge']);

const git = (root, ...args) => execFileSync('git', args, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
const tryGit = (root, ...args) => { try { return git(root, ...args); } catch { return ''; } };

/**
 * The script for one hook: find `vibekit`, hand over. Generated, so a team never edits it.
 *
 * A clone without the binary passes with a warning rather than refusing every commit: a hook that
 * blocks a machine that cannot even run the rule is a hook somebody deletes, and then it protects
 * nobody. The warning names what to install; the rule itself is unchanged.
 */
export const hookScript = (name) => [
  '#!/bin/sh',
  '# generated by vibekit · do not edit · source: githooks',
  `# ${name}: the rule is in src/githooks.js; this only finds the binary.`,
  'if command -v vibekit >/dev/null 2>&1; then',
  `  exec vibekit githook ${name} "$@"`,
  'fi',
  'if npx --no-install vibekit version >/dev/null 2>&1; then',
  `  exec npx --no-install vibekit githook ${name} "$@"`,
  'fi',
  `echo "vibekit: not installed on this machine, so the ${name} rule was not checked. Run \\"vibekit setup\\"." >&2`,
  'exit 0',
  '',
].join('\n');

/** Write the four scripts and point git at them. Idempotent; a hand-edited script is left alone. */
export async function installHooks(root) {
  if (!(await exists(join(root, '.git')))) return { installed: [], skipped: 'not a git repository' };
  const installed = [];
  const kept = [];
  for (const name of HOOK_NAMES) {
    const path = join(root, HOOKS_DIR, name);
    const existing = await readText(path);
    if (existing !== null && !existing.includes('generated by vibekit')) {
      kept.push(name);
      continue;
    }
    await writeText(path, hookScript(name));
    await chmod(path, 0o755).catch(() => {});
    installed.push(name);
  }
  tryGit(root, 'config', 'core.hooksPath', HOOKS_DIR);
  return { installed, kept, hooksPath: HOOKS_DIR };
}

// ---------------------------------------------------------------- pre-commit

// The entropy score is the one ingest uses (§31), so a token the hook stops is a token the folder
// would have redacted, and the two never disagree about what a secret looks like.
import { ENTROPY_MIN, highEntropyTokens, shannon } from './sources.js';

export { ENTROPY_MIN, highEntropyTokens, shannon };

/**
 * The staged diff, added lines only, with the file each came from. Only what is about to be
 * committed is judged; a secret already in history is a different problem with a different fix.
 */
export function stagedAdditions(root) {
  const diff = tryGit(root, 'diff', '--cached', '-U0', '--no-color');
  const additions = [];
  let file = null;
  for (const line of diff.split('\n')) {
    const header = line.match(/^\+\+\+ b\/(.+)$/);
    if (header) { file = header[1]; continue; }
    if (line.startsWith('+') && !line.startsWith('+++') && file) additions.push({ file, text: line.slice(1) });
  }
  return additions;
}

export async function preCommit(root, { folder = DEFAULT_FOLDER } = {}) {
  const { detect } = await import('./sources.js');
  const refusals = [];
  const additions = stagedAdditions(root);
  const staged = [...new Set(additions.map((entry) => entry.file))];

  // Secrets and personal data in what is about to land. Lock files and build output are full of
  // integrity hashes and minified names that score like keys and are not; they are skipped whole.
  for (const { file, text } of additions) {
    if (/(?:^|\/)(?:package-lock\.json|pnpm-lock\.yaml|yarn\.lock|Cargo\.lock|composer\.lock|Gemfile\.lock|poetry\.lock|packages\.lock\.json)$|\.(?:lock|min\.js|map|svg|png)$/.test(file)) continue;
    for (const hit of detect(text).filter((entry) => ['EMAIL', 'PHONE'].includes(entry.kind))) {
      if (file.startsWith(`${folder}/agents/`)) continue; // humans.md is where an email belongs
      refusals.push(`${file}: ${hit.kind === 'EMAIL' ? 'an email' : 'a phone number'} (${hit.value}) is about to be committed`);
    }
    if (/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----|sk_live_[A-Za-z0-9]{8,}|AKIA[0-9A-Z]{16}/.test(text)) {
      refusals.push(`${file}: a private key or a live credential`);
      continue; // one line for one secret; the entropy score would only say it again
    }
    for (const token of highEntropyTokens(text)) refusals.push(`${file}: a high-entropy token that looks like a key (${token.slice(0, 8)}…)`);
  }

  // §22 — a denied path in the staged set. `vibekit check --fast`: guardrail paths and entity
  // names in the staged diff only, under two seconds.
  const guardrails = parseGuardrails((await readText(join(root, folder, 'standards/guardrails.md'))) ?? '');
  for (const denied of guardrails.deniedPaths.map((entry) => entry.path).filter((path) => path && !/^TODO/i.test(path))) {
    const prefix = denied.replace(/\*+$/, '');
    for (const file of staged.filter((path) => path.startsWith(prefix))) refusals.push(`${file} is under a denied path (${denied}) in standards/guardrails.md`);
  }

  const entitiesText = (await readText(join(root, folder, 'product/entities.md'))) ?? '';
  const known = new Set([...entitiesText.matchAll(/^##\s+(.+)$/gm)].map((match) => match[1].trim()));
  for (const { file, text } of additions.filter((entry) => /product\/requirements\/.*\.md$/.test(entry.file))) {
    const listed = text.match(/^entities:\s*\[([^\]]*)\]/);
    if (!listed) continue;
    for (const name of listed[1].split(',').map((item) => item.trim()).filter(Boolean)) {
      if (known.size && !known.has(name)) refusals.push(`${file} names the entity "${name}", which is not in product/entities.md`);
    }
  }
  return refusals;
}

// ---------------------------------------------------------------- commit-msg

export const PROTECTED = (base) => new Set([base, 'main', 'master']);

/**
 * §50 — on a `req/*` or `hotfix/*` branch the message starts with the requirement's id and
 * carries the `VibeKit-Requirement` trailer; a commit straight onto the base branch is refused.
 * `git commit --no-verify` is git's own way past this, and it is deliberately not replaced with a
 * flag of ours: an escape hatch nobody can audit is not an escape hatch.
 */
export async function commitMsg(root, message, { folder = DEFAULT_FOLDER, branch = tryGit(root, 'rev-parse', '--abbrev-ref', 'HEAD') } = {}) {
  const profile = readFrontMatter((await readText(join(root, folder, 'profile.md'))) ?? '');
  const base = profile.base ?? 'main';
  const refusals = [];
  const subject = String(message ?? '').split('\n')[0];

  if (PROTECTED(base).has(branch)) {
    refusals.push(`a commit straight onto ${branch} is refused: work lands there by pull request. Branch with \`vibekit start <REQ>\`, or use --no-verify if you mean it.`);
    return refusals;
  }
  const work = branch.match(/^(?:req|hotfix)\/((?:REQ|MIG|BUG)-[\w.-]+)/);
  if (!work) return refusals;

  const id = work[1];
  if (!new RegExp(`\\b${id.replace('.', '\\.')}\\b`).test(subject) && !/^(?:feat|fix|chore|refactor|test|docs)\((?:REQ|MIG|BUG)-[\w.-]+\)/.test(subject)) {
    refusals.push(`the subject must carry ${id}: \`feat(${id}): …\`. A commit nobody can trace to a requirement is a line \`vibekit why\` cannot explain.`);
  }
  if (!/^VibeKit-Requirement:\s*(?:REQ|MIG|BUG)-[\w.-]+/m.test(message)) {
    refusals.push(`the trailer is missing: add \`VibeKit-Requirement: ${id}\` as the last line. \`trace\` and the reports read it.`);
  }
  return refusals;
}

// ---------------------------------------------------------------- pre-push

/**
 * `pre-push` reads `<local ref> <local sha> <remote ref> <remote sha>` lines. A push whose remote
 * sha is not an ancestor of the local one is a force push, whatever flag produced it; to a
 * protected branch that is refused. A `req/*` branch may only be pushed by the session holding it.
 */
export async function prePush(root, lines, { folder = DEFAULT_FOLDER } = {}) {
  const profile = readFrontMatter((await readText(join(root, folder, 'profile.md'))) ?? '');
  const base = profile.base ?? 'main';
  const held = (await readTasksState(root, folder)).held;
  const refusals = [];

  for (const line of String(lines ?? '').split('\n').filter(Boolean)) {
    const [, localSha, remoteRef, remoteSha] = line.trim().split(/\s+/);
    const branch = String(remoteRef ?? '').replace(/^refs\/heads\//, '');
    const deleting = /^0+$/.test(localSha ?? '');
    const creating = /^0+$/.test(remoteSha ?? '');

    if (PROTECTED(base).has(branch) && !creating && !deleting) {
      const fastForward = tryGit(root, 'merge-base', '--is-ancestor', remoteSha, localSha) === '' && !tryGit(root, 'rev-parse', '--verify', `${remoteSha}^{commit}`).startsWith('fatal');
      // merge-base --is-ancestor exits non-zero when it is not; tryGit returns '' either way, so ask directly.
      let ancestor = true;
      try { execFileSync('git', ['merge-base', '--is-ancestor', remoteSha, localSha], { cwd: root, stdio: 'ignore' }); } catch { ancestor = false; }
      if (!ancestor && fastForward !== undefined) refusals.push(`a force push to ${branch} is refused: the remote has commits this push would discard.`);
    }

    const work = branch.match(/^req\/((?:REQ|MIG|BUG)-[\w.-]+)/);
    if (work && !held[work[1]]) {
      refusals.push(`${branch} is not held by this session (\`vibekit start ${work[1]} --as <role>\`). A push from a requirement nobody holds is work nobody can attribute.`);
    }
  }
  return refusals;
}

// ---------------------------------------------------------------- post-merge

/** §50 — when a `req/*` branch lands, status and the requirements index are regenerated. */
export async function postMerge(root, { folder = DEFAULT_FOLDER } = {}) {
  const { renderStatus } = await import('./folder/workflow.js');
  const status = await renderStatus(root, folder, {}).catch(() => null);
  if (status === null) return { regenerated: [] };
  const path = join(root, folder, 'workflow/status.md');
  const existing = await readText(path);
  if (existing !== null) await writeText(path, `${existing.split('\n', 1)[0]}\n${status}`);
  return { regenerated: [`${folder}/workflow/status.md`] };
}
