import { readdir, readFile } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';
import { readFrontMatter } from './features.js';

export const STANDARDS_DIR = 'standards';
export const INDEX_FILE = `${STANDARDS_DIR}/index.yml`;
// Reserved for standards that sit in the root of standards/ rather than a domain folder.
export const ROOT_DOMAIN = 'root';

const STOP_WORDS = new Set(['the', 'a', 'an', 'and', 'or', 'for', 'to', 'of', 'in', 'on', 'with', 'my', 'our', 'this', 'that', 'add', 'new', 'use', 'using', 'build', 'make', 'when', 'how', 'code', 'file', 'files']);
const terms = (text) => [...new Set(String(text).toLowerCase().match(/[a-z0-9]+/g) ?? [])].filter((word) => word.length > 2 && !STOP_WORDS.has(word));

/** Every standards file on disk, with the description and globs it declares. */
export async function scanStandards(root) {
  const base = join(root, STANDARDS_DIR);
  const found = [];

  async function walk(dir, domain) {
    let entries = [];
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        // One level of domain folders, matching the flat index shape.
        if (domain === ROOT_DOMAIN) await walk(full, entry.name);
        continue;
      }
      if (!entry.name.endsWith('.md')) continue;
      const body = await readFile(full, 'utf8');
      const meta = readFrontMatter(body);
      found.push({
        domain,
        name: entry.name.replace(/\.md$/, ''),
        path: relative(root, full).split(sep).join('/'),
        description: meta.description ?? '',
        globs: meta.globs ?? '',
        body,
      });
    }
  }

  await walk(base, ROOT_DOMAIN);
  return found.sort((a, b) => `${a.domain}/${a.name}`.localeCompare(`${b.domain}/${b.name}`));
}

const quote = (text) => `"${String(text).replace(/"/g, '\\"')}"`;

/**
 * The index is deliberately tiny: an agent reads it instead of every standard,
 * then loads only the files that match the task.
 */
export function renderIndex(entries) {
  const byDomain = new Map();
  for (const entry of entries) {
    if (!byDomain.has(entry.domain)) byDomain.set(entry.domain, []);
    byDomain.get(entry.domain).push(entry);
  }
  // Domain folders first, then the reserved root bucket, so the file reads top-down.
  const domains = [...byDomain.keys()].filter((name) => name !== ROOT_DOMAIN).sort();
  if (byDomain.has(ROOT_DOMAIN)) domains.push(ROOT_DOMAIN);

  const lines = ['# Generated by `vibecheck standards index`. Descriptions come from each file\'s front matter.'];
  for (const domain of domains) {
    lines.push('', `${domain}:`);
    for (const entry of byDomain.get(domain)) {
      lines.push(`  ${entry.name}:`, `    description: ${quote(entry.description)}`);
      if (entry.globs) lines.push(`    globs: ${quote(entry.globs)}`);
    }
  }
  return `${lines.join('\n')}\n`;
}

/** Parses the two-level shape renderIndex writes; anything else is ignored rather than guessed at. */
export function parseIndex(text) {
  const entries = [];
  let domain = null;
  let current = null;
  for (const raw of String(text).replace(/\r\n/g, '\n').split('\n')) {
    if (!raw.trim() || raw.trimStart().startsWith('#')) continue;
    const domainMatch = raw.match(/^([\w.-]+):\s*$/);
    if (domainMatch) {
      domain = domainMatch[1];
      current = null;
      continue;
    }
    const nameMatch = raw.match(/^ {2}([\w.-]+):\s*$/);
    if (nameMatch && domain) {
      current = { domain, name: nameMatch[1], description: '', globs: '' };
      current.path = domain === ROOT_DOMAIN ? `${STANDARDS_DIR}/${current.name}.md` : `${STANDARDS_DIR}/${domain}/${current.name}.md`;
      entries.push(current);
      continue;
    }
    const fieldMatch = raw.match(/^ {4}(description|globs):\s*"?(.*?)"?\s*$/);
    if (fieldMatch && current) current[fieldMatch[1]] = fieldMatch[2];
  }
  return entries;
}

const globToRegExp = (glob) => new RegExp(`^${glob.trim()
  .replace(/[.+^${}()|[\]\\]/g, '\\$&')
  .replace(/\*\*\//g, '::DEEP::')
  .replace(/\*/g, '[^/]*')
  .replace(/::DEEP::/g, '(?:.*/)?')}$`);

const matchesGlobs = (globs, paths) => globs
  .split(',')
  .filter((glob) => glob.trim())
  .some((glob) => paths.some((path) => globToRegExp(glob).test(path)));

/**
 * Picks the standards relevant to a task, so only those need to be read.
 * A standard whose globs match a touched file is always relevant; otherwise it is
 * scored on shared words with the query. Nothing matching means nothing injected.
 */
export function selectStandards(entries, { query = '', paths = [] } = {}) {
  const wanted = terms(query);
  const scored = entries.map((entry) => {
    if (entry.globs && paths.length && matchesGlobs(entry.globs, paths)) return { entry, score: Infinity, reason: 'globs' };
    const haystack = terms(`${entry.domain} ${entry.name.replace(/-/g, ' ')} ${entry.description}`);
    const score = wanted.filter((word) => haystack.includes(word)).length;
    return { entry, score, reason: 'description' };
  });
  return scored
    .filter((hit) => hit.score > 0)
    .sort((a, b) => b.score - a.score || a.entry.path.localeCompare(b.entry.path))
    .map((hit) => ({ ...hit.entry, matchedBy: hit.reason }));
}
