import { cp, readdir, rm } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { EXAMPLE_JSON } from './example.js';
import { exists, readText, writeText } from './fsutil.js';
import { AGENT_ROLES } from './generators/agents.js';
import { pluginAgents, renderAgent, renderSkill } from './generators/claude.js';
import { PLUGIN_CONTEXT, SKILLS } from './generators/workflow.js';
import { probe } from './machine/probe.js';

export const BUILD_NOTICE = '<!-- Generated by `npm run build` from src/generators/. Edit the source, not this file. -->';
export const DEFAULT_REPO = fileURLToPath(new URL('../../', import.meta.url)).replace(/[\\/]$/, '');
export const teamRepo = () => process.env.VIBEKIT_REPO_DIR || DEFAULT_REPO;
export const claudeDir = () => process.env.CLAUDE_CONFIG_DIR || join(homedir(), '.claude');
const RESERVED_SKILLS = SKILLS.map((skill) => skill.name);
const RESERVED_AGENTS = AGENT_ROLES.map((role) => role.name);

export const teamPaths = (repo = teamRepo()) => ({
  skills: join(repo, 'team', 'skills'),
  agents: join(repo, 'team', 'agents'),
  plugins: join(repo, 'team', 'plugins.json'),
});

const listDirs = async (dir) => (await readdir(dir, { withFileTypes: true }).catch(() => [])).filter((entry) => entry.isDirectory() || entry.isSymbolicLink()).map((entry) => entry.name);
const listMarkdown = async (dir) => (await readdir(dir).catch(() => [])).filter((name) => name.endsWith('.md'));

export function teamPluginsSync(repo = teamRepo()) {
  try {
    return JSON.parse(readFileSync(teamPaths(repo).plugins, 'utf8'));
  } catch {
    return [];
  }
}

export async function readTeam(repo = teamRepo()) {
  const paths = teamPaths(repo);
  const skills = [];
  for (const name of await listDirs(paths.skills)) if (await exists(join(paths.skills, name, 'SKILL.md'))) skills.push(name);
  return { skills, agents: await listMarkdown(paths.agents), plugins: teamPluginsSync(repo) };
}

function assertNoClash(kind, names, reserved) {
  const clashes = names.filter((name) => reserved.includes(name.replace(/\.md$/, '')));
  if (clashes.length) throw new Error(`Team ${kind} ${clashes.join(', ')} clash with VibeKit's built-in ${kind}. Rename them in team/${kind}/.`);
}

async function updateManifests(repo, plugins) {
  const manifestPath = join(repo, 'plugin', '.claude-plugin', 'plugin.json');
  const marketplacePath = join(repo, '.claude-plugin', 'marketplace.json');
  const manifest = JSON.parse(await readText(manifestPath));
  const marketplace = JSON.parse(await readText(marketplacePath));
  const dependencies = plugins.map((plugin) => ({ name: plugin.name, marketplace: plugin.marketplace }));
  const marketplaces = [...new Set(plugins.map((plugin) => plugin.marketplace))];
  if (dependencies.length) manifest.dependencies = dependencies;
  else delete manifest.dependencies;
  if (marketplaces.length) marketplace.allowCrossMarketplaceDependenciesOn = marketplaces;
  else delete marketplace.allowCrossMarketplaceDependenciesOn;
  await writeText(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  await writeText(marketplacePath, `${JSON.stringify(marketplace, null, 2)}\n`);
}

export function pluginSkillFiles() {
  return [
    ...SKILLS.map((skill) => ({ path: `${skill.name}/SKILL.md`, content: renderSkill(skill, PLUGIN_CONTEXT, BUILD_NOTICE) })),
    { path: 'new-project/project.example.json', content: EXAMPLE_JSON },
  ];
}

export async function buildPlugin(repo = teamRepo()) {
  const skillsDir = join(repo, 'plugin', 'skills');
  const agentsDir = join(repo, 'plugin', 'agents');
  const team = await readTeam(repo);
  assertNoClash('skills', team.skills, RESERVED_SKILLS);
  assertNoClash('agents', team.agents, RESERVED_AGENTS);

  await rm(skillsDir, { recursive: true, force: true });
  for (const file of pluginSkillFiles()) await writeText(join(skillsDir, file.path), file.content);
  for (const name of team.skills) await cp(join(teamPaths(repo).skills, name), join(skillsDir, name), { recursive: true, dereference: true });

  await rm(agentsDir, { recursive: true, force: true });
  for (const agent of pluginAgents()) await writeText(join(agentsDir, `${agent.name}.md`), renderAgent(agent, BUILD_NOTICE));
  for (const name of team.agents) await cp(join(teamPaths(repo).agents, name), join(agentsDir, name));

  const notice = await readText(join(repo, 'team', 'THIRD_PARTY_NOTICES.md'));
  if (notice) await writeText(join(repo, 'plugin', 'THIRD_PARTY_NOTICES.md'), notice);
  else await rm(join(repo, 'plugin', 'THIRD_PARTY_NOTICES.md'), { force: true });
  await updateManifests(repo, team.plugins);
  return { skills: SKILLS.length + team.skills.length, agents: AGENT_ROLES.length + team.agents.length, team };
}

export async function bumpVersion(repo = teamRepo()) {
  const files = [join(repo, 'plugin', '.claude-plugin', 'plugin.json'), join(repo, 'plugin', 'package.json')];
  const current = JSON.parse(await readText(files[0])).version;
  const next = current.replace(/^(\d+)\.(\d+)\.(\d+)/, (_, major, minor, patch) => `${major}.${minor}.${Number(patch) + 1}`);
  for (const path of files) {
    const data = JSON.parse(await readText(path));
    data.version = next;
    await writeText(path, `${JSON.stringify(data, null, 2)}\n`);
  }
  const marketplacePath = join(repo, '.claude-plugin', 'marketplace.json');
  const marketplace = JSON.parse(await readText(marketplacePath));
  marketplace.plugins = marketplace.plugins.map((entry) => (entry.name === 'vibekit' ? { ...entry, version: next } : entry));
  await writeText(marketplacePath, `${JSON.stringify(marketplace, null, 2)}\n`);
  return next;
}

function claudeJson(args) {
  const result = probe('claude', args);
  if (!result.ok) return null;
  try {
    return JSON.parse(result.output);
  } catch {
    return null;
  }
}

const SHAREABLE = { github: (entry) => ({ source: 'github', repo: entry.repo }), git: (entry) => ({ source: 'git', url: entry.url }), url: (entry) => ({ source: 'url', url: entry.url }) };

export function installedPlugins() {
  const plugins = claudeJson(['plugin', 'list', '--json']);
  const marketplaces = claudeJson(['plugin', 'marketplace', 'list', '--json']);
  if (!plugins || !marketplaces) return null;
  const byName = new Map(marketplaces.map((entry) => [entry.name, entry]));
  return plugins
    .filter((plugin) => !plugin.id.startsWith('vibekit@'))
    .map((plugin) => {
      const [name, marketplace] = plugin.id.split('@');
      const entry = byName.get(marketplace);
      const share = entry && SHAREABLE[entry.source];
      return { name, marketplace, source: share ? share(entry) : null, local: entry ? entry.source === 'directory' || entry.source === 'file' : true };
    });
}

export async function captureTeam(repo = teamRepo(), { skip = [] } = {}) {
  const home = claudeDir();
  const paths = teamPaths(repo);
  const report = { skills: [], agents: [], plugins: [], skipped: [], localPlugins: [] };

  for (const name of await listDirs(join(home, 'skills'))) {
    if (skip.includes(name) || !(await exists(join(home, 'skills', name, 'SKILL.md')))) continue;
    if (RESERVED_SKILLS.includes(name)) { report.skipped.push(`skill ${name} (name used by VibeKit)`); continue; }
    await rm(join(paths.skills, name), { recursive: true, force: true });
    await cp(join(home, 'skills', name), join(paths.skills, name), { recursive: true, dereference: true });
    report.skills.push(name);
  }
  for (const file of await listMarkdown(join(home, 'agents'))) {
    const name = file.replace(/\.md$/, '');
    if (skip.includes(name)) continue;
    if (RESERVED_AGENTS.includes(name)) { report.skipped.push(`subagent ${name} (name used by VibeKit)`); continue; }
    await cp(join(home, 'agents', file), join(paths.agents, file));
    report.agents.push(name);
  }
  const plugins = installedPlugins();
  if (plugins) {
    const shareable = plugins.filter((plugin) => plugin.source && !skip.includes(plugin.name));
    report.plugins = shareable.map((plugin) => `${plugin.name}@${plugin.marketplace}`);
    report.localPlugins = plugins.filter((plugin) => !plugin.source).map((plugin) => `${plugin.name}@${plugin.marketplace}`);
    await writeText(paths.plugins, `${JSON.stringify(shareable.map(({ name, marketplace, source }) => ({ name, marketplace, source })), null, 2)}\n`);
  } else {
    report.skipped.push('plugins (could not read Claude Code\'s plugin list)');
  }
  return report;
}

export const marketplaceAddArg = (source) => (source.source === 'github' ? source.repo : source.url);
